# Downloading MGnify Study data

The MGnify API provides access to study and analyses datasets for download. On this page we demonstrate how to:

-  **Discover** what datasets are available
-  **Download** the datasets
-  **Stream** or read in the datasets

```{margin}
After clicking the "Activate Notebook" button you can run the cells in this browser. Alternatively, you can also click on the 🚀 to launch in colab or binder.
```
<button title="Make live" style="display:inline-flex;align-items:center;gap:0.4rem;padding:0.5rem 1rem;border:0;border-radius:20px;background:linear-gradient(135deg,#0f766e,#14b8a6);color:white;cursor:pointer;font-size:1rem;" class="thebe-button" onclick="initThebeSBT()">Activate Notebook</button>

---

In [1]:
# uncomment below if colab
#!pip install mgnipy



## 🎯 The Goal: Retrieve taxonomic datasets of tomato rhizosphere studies

Let's request tomato rhizosphere datasets and metadata from MGnify API.

Recall the typical workflow (from [What is MGni.Py?](https://mgnipy.mgnify.org/notebooks/getting-started/1_what_is_mgnipy.html)):

1. Start up a `mgnipy.MGnipy` client with your desired configuration

2. Search in MGnify resources using a MGnifier glass

3. Receive a MGazine of MGnify datasets

which we will follow in this notebook

## 1. and 2. `mgnipy.MGnipy().studies`

In the below cell we take care of
- ✅ 1. set up of our MGnipy instance and
- ✅ 2.a) preparing search for a list of tomato studies using the studies-specific `MGnifier` aka `mgnipy.V2.proxies.studies.Studies`
- ✅ 2.b) populating list of studies
- ✅ 2.c) retrieving details (i.e., ALL `StudyDetail`s) for every study in the list


````{margin} What is happening behind the scenes of:
**2.b)** .bulk_fetch()
```python
for _ in range(
    tomato_studies.num_requests
):
    tomato_studies.get()
```

**2.c)** .enrich_details()
```python
for _ in range(
    len(tomato_studies)
):
    tomato_studies.get_detail()
```
````

In [2]:
from mgnipy import MGnipy

# 1. init with default config
MG = MGnipy(
    #cache_dir="downloads"
)

# 2.a) setup studies mgnifier (build queries)
tomato_studies = MG.studies(
    biome_lineage="root:Host-associated:Plants:Rhizosphere", search="tomato"
)

# 2.b) execute the list query (get the study list)
tomato_studies.bulk_fetch()

# 2.c) get the study list (execute all detail queries)
tomato_studies.enrich_details()

# take a look at the studies details results as a pandas df
tomato_studies.to_df(expand_nested_dicts=True)

DEBUG:numcodecs:Registering codec 'zlib'
DEBUG:numcodecs:Registering codec 'gzip'
DEBUG:numcodecs:Registering codec 'bz2'
DEBUG:numcodecs:Registering codec 'lzma'
DEBUG:numcodecs:Registering codec 'blosc'
DEBUG:numcodecs:Registering codec 'zstd'
DEBUG:numcodecs:Registering codec 'lz4'
DEBUG:numcodecs:Registering codec 'astype'
DEBUG:numcodecs:Registering codec 'delta'
DEBUG:numcodecs:Registering codec 'quantize'
DEBUG:numcodecs:Registering codec 'fixedscaleoffset'
DEBUG:numcodecs:Registering codec 'packbits'
DEBUG:numcodecs:Registering codec 'categorize'
DEBUG:numcodecs:Registering codec 'pickle'
DEBUG:numcodecs:Registering codec 'base64'
DEBUG:numcodecs:Registering codec 'shuffle'
DEBUG:numcodecs:Registering codec 'bitround'
DEBUG:numcodecs:Registering codec 'crc32'
DEBUG:numcodecs:Registering codec 'adler32'
DEBUG:numcodecs:Registering codec 'jenkins_lookup3'
DEBUG:numcodecs:Registering codec 'json2'
DEBUG:numcodecs:Registering codec 'vlen-utf8'
DEBUG:numcodecs:Registering codec 'vlen-bytes'
DEBUG:numcodecs:Registering codec 'vlen-array'
DEBUG:numcodecs:Registering codec 'fletcher32'
DEBUG:numcodecs:Registering codec 'crc32c'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource studies
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11f19a1d0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x1207ce690> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11f1fde10>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:01 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for studies
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for studies
INFO:mgnipy.V2.query_set:Attempting to load cached results for studies
DEBUG:mgnipy.V2.mixins:Computed cache key for studies: 548649ce566f131cec498682d701e6335235a8f634546f3cadae6892147a89b6
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/548649ce566f131cec498682d701e6335235a8f634546f3cadae6892147a89b6
INFO:mgnipy.V2.mixins:No cache directory found at /Users/anglup/Library/Caches/mgnipy/548649ce566f131cec498682d701e6335235a8f634546f3cadae6892147a89b6
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource studies
DEBUG:mgnipy.V2.mixins:Computed cache key for studies: 548649ce566f131cec498682d701e6335235a8f634546f3cadae6892147a89b6
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource studies
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11ffe4910>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x1207ce960> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120030950>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:01 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for studies
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for studies
INFO:mgnipy.V2.query_set:Attempting to load cached results for studies
DEBUG:mgnipy.V2.mixins:Computed cache key for studies: cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a
INFO:mgnipy.V2.mixins:Loading cached page from /Users/anglup/Library/Caches/mgnipy/cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a/mgnipy_page_1.json
INFO:mgnipy.V2.query_set:Loaded pages [1] from cache for resource studies
DEBUG:mgnipy.V2.mixins:Computed cache key for studies: cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a
INFO:mgnipy.V2.mixins:Loading cache manifest from /Users/anglup/Library/Caches/mgnipy/cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a/mgnipy_manifest.json
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=1 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 17 items (max page 1): [1]
Retrieving list_mgnify_studies pages:   0%|          | 0/1 [00:00<?, ?it/s]INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 17, 1
DEBUG:mgnipy.V2.query_set:Result presence check for studies page 1: True
INFO:mgnipy.V2.query_executor:Page 1 already retrieved.
Retrieving list_mgnify_studies pages: 100%|██████████| 1/1 [00:00<00:00, 503.22it/s]
DEBUG:mgnipy.V2.proxies:Starting enrichment of study details with limit 200.
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Flattening paginated results for studies
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Flattening paginated results for studies
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Flattening paginated results for studies
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
Enriching study details:   0%|          | 0/17 [00:00<?, ?it/s]INFO:mgnipy.V2.proxies:Enriching detail MGYS00010296. Count: 0
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'study': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource study
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11ffef110>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x1207ce9f0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1206ae110>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:02 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for study
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for study
INFO:mgnipy.V2.query_set:Attempting to load cached results for study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 543ed63baf46ceb583dd3af1ab114e09d4fd4b4f0ba6d18455b6c5d6d7ddec29
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/543ed63baf46ceb583dd3af1ab114e09d4fd4b4f0ba6d18455b6c5d6d7ddec29
INFO:mgnipy.V2.mixins:No cache directory found at /Users/anglup/Library/Caches/mgnipy/543ed63baf46ceb583dd3af1ab114e09d4fd4b4f0ba6d18455b6c5d6d7ddec29
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 543ed63baf46ceb583dd3af1ab114e09d4fd4b4f0ba6d18455b6c5d6d7ddec29
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_set:Built request URL for study: https://www.ebi.ac.uk/metagenomics/api/v2/studies/None
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 543ed63baf46ceb583dd3af1ab114e09d4fd4b4f0ba6d18455b6c5d6d7ddec29
DEBUG:mgnipy.V2.proxies:Got detail class MGnifier instance for resource: study
I.e., mgnipy.V2.proxies.studies.StudyDetail
----------------------------------------
Base URL: https://www.ebi.ac.uk/
Parameters: {'accession': None}
Example request URL: https://www.ebi.ac.uk/metagenomics/api/v2/studies/None
Endpoint module: mgnipy.emgapi_v2_client.api.studies.get_mgnify_study
Is list endpoint (returns paginated results): False
Cache directory: /Users/anglup/Library/Caches/mgnipy/543ed63baf46ceb583dd3af1ab114e09d4fd4b4f0ba6d18455b6c5d6d7ddec29
 for child resource <SupportedEndpoints.STUDY: 'study'>
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Flattening paginated results for studies
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Flattening paginated results for studies
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Flattening paginated results for studies
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.proxies:Resolved id param for detail: {'accession': 'MGYS00010296'}
INFO:mgnipy.V2.query_set:Filtering QuerySet for study with keys: ['accession']
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'study': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource study
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120874910>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x1207cfda0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11ffe7050>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:02 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for study
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for study
INFO:mgnipy.V2.query_set:Attempting to load cached results for study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
INFO:mgnipy.V2.mixins:Loading cached page from /Users/anglup/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848/mgnipy_page_1.json
INFO:mgnipy.V2.query_set:Loaded pages [1] from cache for resource study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
INFO:mgnipy.V2.mixins:Loading cache manifest from /Users/anglup/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848/mgnipy_manifest.json
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.query_set:Reassigning endpoint module for study
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for study
INFO:mgnipy.V2.query_set:Attempting to load cached results for study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
INFO:mgnipy.V2.mixins:Loading cached page from /Users/anglup/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848/mgnipy_page_1.json
INFO:mgnipy.V2.query_set:Loaded pages [1] from cache for resource study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
INFO:mgnipy.V2.mixins:Loading cache manifest from /Users/anglup/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848/mgnipy_manifest.json
DEBUG:mgnipy.V2.query_set:Built request URL for study: https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010296
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
DEBUG:mgnipy.V2.proxies:Initialized detail proxy MGnifier instance for resource: study
I.e., mgnipy.V2.proxies.studies.StudyDetail
----------------------------------------
Base URL: https://www.ebi.ac.uk/
Parameters: {'accession': 'MGYS00010296'}
Example request URL: https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010296
Endpoint module: mgnipy.emgapi_v2_client.api.studies.get_mgnify_study
Is list endpoint (returns paginated results): False
Cache directory: /Users/anglup/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
 with params {'accession': 'MGYS00010296'}
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for study page 1: True
INFO:mgnipy.V2.query_executor:Page 1 already retrieved.
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.mixins:Converting results to pandas DataFrame; expand_nested_dicts=False
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning record iterator for study
DEBUG:mgnipy.V2.query_set:Flattening paginated results for study
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.proxies:Updating download info with identifier 'MGYS00010296' to id_param_key 'accession'
DEBUG:mgnipy.V2.mixins:Converting results to pandas DataFrame; expand_nested_dicts=False

,accession,ena_accessions,title,updated_at,biome__biome_name,biome__lineage
0,MGYS00010296,"[ERP166137, PRJEB82448]",Microbiome-mediated tolerance of wild tomato t...,2026-05-28T15:46:48.615000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
1,MGYS00010297,"[SRP333165, PRJNA755742]",Tomato rhizosphere microbiome in the pot exper...,2026-05-28T15:46:48.649000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
2,MGYS00006231,"[ERP139927, PRJEB55060]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:46:58.486000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
3,MGYS00006204,"[ERP140102, PRJEB55219]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:47:01.715000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
4,MGYS00006205,"[ERP140107, PRJEB55224]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:47:01.734000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
5,MGYS00006208,"[ERP140115, PRJEB55232]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:47:01.747000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
6,MGYS00006230,"[ERP139923, PRJEB55057]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:47:01.755000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
7,MGYS00010257,"[SRP456588, PRJNA1004080]",Combined effect of microplastics and fungicide...,2026-05-28T15:46:48.538000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
8,MGYS00010264,[PRJEB91717],Metagenome assembly of PRJNA1127303 data set (...,2026-05-28T15:46:48.743000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
9,MGYS00010251,"[SRP338795, PRJNA766489]",Culture-independent analysis of rhizosphere mi...,2026-05-28T15:46:48.756000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
10,MGYS00010245,"[PRJEB82447, ERP166136]",Unveiling diversity and adaptations of the wil...,2026-05-28T15:46:48.558000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
11,MGYS00010324,[PRJEB95772],Metagenome assembly of PRJNA777724 data set (T...,2026-05-28T15:46:48.576000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
12,MGYS00010258,"[SRP517058, PRJNA1127303]",Metagenomic data of rhizosphere soil during to...,2026-05-28T15:46:48.578000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
13,MGYS00010298,"[PRJNA777724, SRP344777]",Tomato heritable microbiome,2026-05-28T15:46:48.670000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
14,MGYS00010262,[PRJEB91684],Metagenome assembly of PRJNA1004080 data set (...,2026-05-28T15:46:48.688000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
15,MGYS00010250,"[PRJNA755741, SRP333163]",Tomato rhizosphere microbiome in the belowgrou...,2026-05-28T15:46:48.730000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
16,MGYS00010253,"[PRJNA789467, SRP351203]",Disentangling the genetic basis of rhizosphere...,2026-05-28T15:46:48.818000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil

## 3. Accessing the `MGazine` of datasets

- study details have a `mgnipy.MGazine` which allow us to download and interact with study-level datasets outputed from MGnify.

- We can use `mgnipy.MGazine` to download the datasets onto disk or read them into our notebook.

- To access the study's mgazine use `.datasets`

- the __str__ representaiton of mgazine gives us a peak into the pipeline versions within, number of downloads and the short_description categories

In [3]:
# access study mgazine
MZ = tomato_studies.datasets

# print for more info
print(MZ)

# also can view more as df
MZ.downloads_df()

DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.mixins:Converting results to list

MGazine containing:
- MGnify pipeline versions: ['v5']
- Number of downloads: 35
- Short descriptions: ['Complete GO annotation',
 'GO slim annotation',
 'InterPro matches',
 'Phylum level taxonomies LSU',
 'Phylum level taxonomies SSU',
 'Taxonomic assignments LSU',
 'Taxonomic assignments SSU']

,file_type,download_type,short_description,long_description,alias,download_group,file_size_bytes,index_files,url,accession,pipeline_version
0,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP139927_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
1,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP139927_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
2,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP139927_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
3,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP139927_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
4,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP139927_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
5,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP139927_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
6,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP139927_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
7,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP140102_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
8,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140102_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
9,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP140102_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
10,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP140102_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
11,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP140102_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
12,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP140102_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
13,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP140102_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
14,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP140107_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
15,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140107_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
16,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP140107_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
17,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP140107_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
18,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP140107_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
19,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP140107_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
20,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP140107_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
21,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP140115_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
22,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140115_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
23,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP140115_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
24,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP140115_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
25,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP140115_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
26,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP140115_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
27,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP140115_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
28,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP139923_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
29,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP139923_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
30,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP139923_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
31,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP139923_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
32,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP139923_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
33,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP139923_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
34,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP139923_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5

You can filter by short descriptioins by passing them as you would an index into square brackets i..e, __getitem__

In [4]:
# we want the taxonomic assignments
ssu = MZ["Taxonomic assignments SSU"]

# checking out what it is
print(type(ssu))
print(ssu)

# downloads_df again
ssu.downloads_df()

INFO:mgnipy.V2.datasets:Download type for Taxonomic assignments SSU: taxonomic analysis
DEBUG:mgnipy.V2.datasets:getting taxonomic datasets of short description Taxonomic assignments SSU via item access.
INFO:mgnipy.V2.datasets.taxonomic:TaxaMGazine initialized for short description: Taxonomic assignments SSU
INFO:mgnipy.V2.datasets.taxonomic:TaxaMGazine long to short rank mapping set: {'Superkingdom': 'sk', 'Kingdom': 'k', 'Phylum': 'p', 'Class': 'c', 'Order': 'o', 'Family': 'f', 'Genus': 'g', 'Species': 's'}

MGazine Curation TaxaMGazine containing:
- MGnify pipeline versions: ['v5']
- Number of downloads: 5
- Short descriptions: ['Taxonomic assignments SSU']
-----------------------
Next steps: Use `.load()` to initialize.

<class 'mgnipy.V2.datasets.taxonomic.TaxaMGazine'>
MGazine Curation TaxaMGazine containing:
- MGnify pipeline versions: ['v5']
- Number of downloads: 5
- Short descriptions: ['Taxonomic assignments SSU']

,file_type,download_type,short_description,long_description,alias,download_group,file_size_bytes,index_files,url,accession,pipeline_version
0,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP139927_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
1,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140102_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
2,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140107_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
3,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140115_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
4,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP139923_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5

- for more options over the filtering of mgazines see the [MGazine informtion page](https://mgnipy.mgnify.org/notebooks/fundamentals/7_mgazine.html).

- additionally the info page delves into how to downloads the files

We will carry on with our filtered TaxaMGazine given [our goal](#-the-goal-retrieve-taxonomic-datasets-of-tomato-rhizosphere-studies) for now. There are analysis type-specific mgazines, such as this TaxaMGazine

for example, we can also combine the taxonomic assignment results into one dataframe e.g. `.to_pandas()`, `.to_polars`, `.X()`

In [5]:
# first loading
ssu.load()

ssu.to_pandas().head()

DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120859090>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x1208e39b0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120860090>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:10 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP139927_taxonomy_abundances_SSU_v5.0.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP139/ERP139927/version_5.0/project-summary/taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1208e7650>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x1208e3bf0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1200325d0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:10 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP140102_taxonomy_abundances_SSU_v5.0.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP140/ERP140102/version_5.0/project-summary/taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x10a17cd10>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x1209ec050> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1208ac790>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:10 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP140107_taxonomy_abundances_SSU_v5.0.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP140/ERP140107/version_5.0/project-summary/taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x12088d250>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x1209ec440> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1208e6690>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:10 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP140115_taxonomy_abundances_SSU_v5.0.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP140/ERP140115/version_5.0/project-summary/taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120858c50>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x1209ec830> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1208e75d0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:11 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP139923_taxonomy_abundances_SSU_v5.0.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP139/ERP139923/version_5.0/project-summary/taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for TaxaMGazine_Taxonomic assignments SSU
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.datasets.taxonomic:Initialized DiskCheckpointer for TaxaMGazine with cache dir: /Users/anglup/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.mixins:Loading cache for TaxaMGazine_Taxonomic assignments SSU from /Users/anglup/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.mixins:No cache directory found at /Users/anglup/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.mixins:Loaded 0 cached pages

TaxaMGazine loaded with 5 datasets.
Cached runs results: 0 of total 149.

,taxonomy,ERZ12343720,ERZ12343730,ERZ12343740,ERZ12343750,ERZ12343760,ERZ12343770,ERZ12343780,ERZ12343721,ERZ12343731,...,ERZ12633581,ERZ12633572,ERZ12633582,ERZ12633573,ERZ12633574,ERZ12633594,ERZ12633576,ERZ12633579,ERZ12590661,ERZ12590669
0,sk__Archaea,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0
1,sk__Archaea;k__;p__Crenarchaeota,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,sk__Archaea;k__;p__Crenarchaeota;c__Thermoprot...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,sk__Archaea;k__;p__Thaumarchaeota;c__Nitrososp...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,sk__Archaea;k__;p__Thaumarchaeota;c__Nitrososp...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,3.0

There is also option to enrich with additional metadata!

1)  From *already* retrieved `MGnifier` results you can set to `runs_results`, `samples_results`, `studies_results` etc, or

2) use `.enrich_runs()` etc or `.enrich_biosamples` which will make the get requests for the additional metadata

In [6]:
ssu.enrich_runs(
    limit=200#default
)

DEBUG:mgnipy.V2.datasets.taxonomic:Starting enrichment of runs for short description Taxonomic assignments SSU with limit 200.
Enriching runs:   0%|          | 0/149 [00:00<?, ?it/s]INFO:mgnipy.V2.datasets.taxonomic:Enriching run ERZ12343720 for short description Taxonomic assignments SSU. Count: 0
DEBUG:mgnipy.V2.datasets.taxonomic:Run ERZ12343720 appears to be an assembly. Using AssemblyDetail proxy for enrichment.
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'assembly': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource assembly
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11f150e90>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x1209ec200> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120851710>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:20 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for assembly
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for assembly
INFO:mgnipy.V2.query_set:Attempting to load cached results for assembly
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: fdd30e6cbbffc002adfa87252a370b80061e7efe49358fc43cc36173aafb01f6
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/fdd30e6cbbffc002adfa87252a370b80061e7efe49358fc43cc36173aafb01f6
INFO:mgnipy.V2.mixins:No cache directory found at /Users/anglup/Library/Caches/mgnipy/fdd30e6cbbffc002adfa87252a370b80061e7efe49358fc43cc36173aafb01f6
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource assembly
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: fdd30e6cbbffc002adfa87252a370b80061e7efe49358fc43cc36173aafb01f6
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Total items is unknown (no dry run) running set_counts() to retrieve count.
DEBUG:mgnipy.V2.query_executor:Computed count and num_requests: 1, 1
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=0 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 1 items (max page 1): [1]
INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for assembly page 1: False
INFO:mgnipy.V2.query_set:Building query plan for assembly
DEBUG:mgnipy.V2.query_set:Built single-query plan for assembly
INFO:mgnipy.V2.query_executor:Fetching request num 1 with params: {'accession': 'ERZ12343720'}
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1208a5790>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120a19c70> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1209f59d0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:20 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'529')])
INFO:httpx:HTTP Request: GET https://www.ebi.ac.uk/metagenomics/api/v2/assemblies/ERZ12343720 "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
INFO:mgnipy.V2.query_executor:Response status code: 200
DEBUG:mgnipy.V2.query_executor:Endpoint is not a list endpoint, returning full response as items.
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: fdd30e6cbbffc002adfa87252a370b80061e7efe49358fc43cc36173aafb01f6
INFO:mgnipy.V2.mixins:Writing cached results for page 1
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: fdd30e6cbbffc002adfa87252a370b80061e7efe49358fc43cc36173aafb01f6
INFO:mgnipy.V2.mixins:Writing page 1 to /Users/anglup/Library/Caches/mgnipy/fdd30e6cbbffc002adfa87252a370b80061e7efe49358fc43cc36173aafb01f6/mgnipy_page_1.json and manifest to /Users/anglup/Library/Caches/mgnipy/fdd30e6cbbffc002adfa87252a370b80061e7efe49358fc43cc36173aafb01f6/mgnipy_manifest.json
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.mixins:Writing cached results for page 1
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.mixins:Writing page 1 to /Users/anglup/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9/mgnipy_page_1.json and manifest to /Users/anglup/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9/mgnipy_manifest.json
Enriching runs:   1%|          | 1/149 [00:00<01:11,  2.08it/s]INFO:mgnipy.V2.datasets.taxonomic:Enriching run ERZ12343730 for short description Taxonomic assignments SSU. Count: 1
DEBUG:mgnipy.V2.datasets.taxonomic:Run ERZ12343730 appears to be an assembly. Using AssemblyDetail proxy for enrichment.
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'assembly': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource assembly
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1208b5590>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x1209ec830> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1208b4f10>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:20 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for assembly
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for assembly
INFO:mgnipy.V2.query_set:Attempting to load cached results for assembly
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: 426c886489a0f987d21e70b3ae3c453140d272de0c2392ba685fe031b46b8ac9
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/426c886489a0f987d21e70b3ae3c453140d272de0c2392ba685fe031b46b8ac9
INFO:mgnipy.V2.mixins:No cache directory found at /Users/anglup/Library/Caches/mgnipy/426c886489a0f987d21e70b3ae3c453140d272de0c2392ba685fe031b46b8ac9
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource assembly
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: 426c886489a0f987d21e70b3ae3c453140d272de0c2392ba685fe031b46b8ac9
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Total items is unknown (no dry run) running set_counts() to retrieve count.
DEBUG:mgnipy.V2.query_executor:Computed count and num_requests: 1, 1
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=0 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 1 items (max page 1): [1]
INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for assembly page 1: False
INFO:mgnipy.V2.query_set:Building query plan for assembly
DEBUG:mgnipy.V2.query_set:Built single-query plan for assembly
INFO:mgnipy.V2.query_executor:Fetching request num 1 with params: {'accession': 'ERZ12343730'}
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120a01490>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120a1a060> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11ffe6850>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:20 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'529')])
INFO:httpx:HTTP Request: GET https://www.ebi.ac.uk/metagenomics/api/v2/assemblies/ERZ12343730 "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
INFO:mgnipy.V2.query_executor:Response status code: 200
DEBUG:mgnipy.V2.query_executor:Endpoint is not a list endpoint, returning full response as items.
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: 426c886489a0f987d21e70b3ae3c453140d272de0c2392ba685fe031b46b8ac9
INFO:mgnipy.V2.mixins:Writing cached results for page 1
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: 426c886489a0f987d21e70b3ae3c453140d272de0c2392ba685fe031b46b8ac9
INFO:mgnipy.V2.mixins:Writing page 1 to /Users/anglup/Library/Caches/mgnipy/426c886489a0f987d21e70b3ae3c453140d272de0c2392ba685fe031b46b8ac9/mgnipy_page_1.json and manifest to /Users/anglup/Library/Caches/mgnipy/426c886489a0f987d21e70b3ae3c453140d272de0c2392ba685fe031b46b8ac9/mgnipy_manifest.json
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.mixins:Writing cached results for page 1
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.mixins:Writing page 1 to /Users/anglup/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9/mgnipy_page_1.json and manifest to /Users/anglup/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9/mgnipy_manifest.json
Enriching runs:   1%|▏         | 2/149 [00:00<01:12,  2.02it/s]INFO:mgnipy.V2.datasets.taxonomic:Enriching run ERZ12343740 for short description Taxonomic assignments SSU. Count: 2
DEBUG:mgnipy.V2.datasets.taxonomic:Run ERZ12343740 appears to be an assembly. Using AssemblyDetail proxy for enrichment.
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'assembly': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource assembly
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1206aee50>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120a1a2a0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1209f6050>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Thu, 04 Jun 2026 01:23:21 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for assembly
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for assembly
INFO:mgnipy.V2.query_set:Attempting to load cached results for assembly
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: 04e1a1a6ea7311f99367e22717eb83588ed4369776b692a3b2acbf7e425ad63a
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/04e1a1a6ea7311f99367e22717eb83588ed4369776b692a3b2acbf7e425ad63a
INFO:mgnipy.V2.mixins:No cache directory found at /Users/anglup/Library/Caches/mgnipy/04e1a1a6ea7311f99367e22717eb83588ed4369776b692a3b2acbf7e425ad63a
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource assembly
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: 04e1a1a6ea7311f99367e22717eb83588ed4369776b692a3b2acbf7e425ad63a
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Total items is unknown (no dry run) running set_counts() to retrieve count.
DEBUG:mgnipy.V2.query_executor:Computed count and num_requests: 1, 1
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=0 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 1 items (max page 1): [1]
INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for assembly page 1: False
INFO:mgnipy.V2.query_set:Building query plan for assembly
DEBUG:mgnipy.V2.query_set:Built single-query plan for assembly
INFO:mgnipy.V2.query_executor:Fetching request num 1 with params: {'accession': 'ERZ12343740'}
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120a01dd0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120a1a690> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120031fd0>

In [8]:
ssu.to_anndata()

DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.mixins:Converting results to pandas DataFrame; expand_nested_dicts=True
/Users/anglup/.pyenv/versions/3.11.7/lib/python3.11/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

AnnData object with n_obs × n_vars = 558 × 149
    obs: 'Superkingdom', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'
    var: 'updated_at', 'run_accession', 'sample_accession', 'reads_study_accession', 'assembly_study_accession', 'assembler_name', 'assembler_version', 'status'

In [9]:
ssu.clear_cache()

WARNING:mgnipy.mgnipy:Clearing ALL cache subdirectories in /Users/anglup/Library/Caches/mgnipy
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/5a6d683697e2926aa5360de4a780b166eca42c7e5917d89d628041b748dfc1ab
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/5a6d683697e2926aa5360de4a780b166eca42c7e5917d89d628041b748dfc1ab/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/5a6d683697e2926aa5360de4a780b166eca42c7e5917d89d628041b748dfc1ab/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/0f0c1e9a4900afb167a264bb9cf3ee3614afa36e88b280243bf99bf4a2416ca5
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/0f0c1e9a4900afb167a264bb9cf3ee3614afa36e88b280243bf99bf4a2416ca5/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/0f0c1e9a4900afb167a264bb9cf3ee3614afa36e88b280243bf99bf4a2416ca5/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/b477ef2f7fca9923b9d417d588a55f5432278ae57523038884a168cba423a3e4
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/b477ef2f7fca9923b9d417d588a55f5432278ae57523038884a168cba423a3e4/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/b477ef2f7fca9923b9d417d588a55f5432278ae57523038884a168cba423a3e4/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/5de6ba3237d534edeb8e44e5cdc451e096ebdc9cfd282ca98546bc69c24d38be
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/5de6ba3237d534edeb8e44e5cdc451e096ebdc9cfd282ca98546bc69c24d38be/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/5de6ba3237d534edeb8e44e5cdc451e096ebdc9cfd282ca98546bc69c24d38be/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/631c4d37e4146534e7402e8d4e512e748e42a1ce62d967c695af44f6adcdcf57
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/631c4d37e4146534e7402e8d4e512e748e42a1ce62d967c695af44f6adcdcf57/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/631c4d37e4146534e7402e8d4e512e748e42a1ce62d967c695af44f6adcdcf57/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/b8311f12f5bae4844e63098d2d1521382a7f99e961bd8ff3a3e66fc56a3d8602
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/b8311f12f5bae4844e63098d2d1521382a7f99e961bd8ff3a3e66fc56a3d8602/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/b8311f12f5bae4844e63098d2d1521382a7f99e961bd8ff3a3e66fc56a3d8602/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/e4b5c883e64e0ce1673091681fe297cbf1bce66187066b52880f8d731a4eb3fb
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/e4b5c883e64e0ce1673091681fe297cbf1bce66187066b52880f8d731a4eb3fb/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/e4b5c883e64e0ce1673091681fe297cbf1bce66187066b52880f8d731a4eb3fb/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/b98dee1ca2e27a3efe83be7d570dbaaae6c09906bbd43fb1b2a2a9395357783a
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/b98dee1ca2e27a3efe83be7d570dbaaae6c09906bbd43fb1b2a2a9395357783a/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/b98dee1ca2e27a3efe83be7d570dbaaae6c09906bbd43fb1b2a2a9395357783a/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/6046ae9f292460400697199e9fa0fddf8b043b5c06d728717500da43eb6c7219
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/6046ae9f292460400697199e9fa0fddf8b043b5c06d728717500da43eb6c7219/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/6046ae9f292460400697199e9fa0fddf8b043b5c06d728717500da43eb6c7219/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/c515ca564b4f7955cf9a8853014c1185f66c4328f874274e63ee67f7ae974ff1
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/c515ca564b4f7955cf9a8853014c1185f66c4328f874274e63ee67f7ae974ff1/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/c515ca564b4f7955cf9a8853014c1185f66c4328f874274e63ee67f7ae974ff1/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/8f5a09841ff64f92f0cd20602caccaea084a1091cf298210070de0f811d8e407
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/8f5a09841ff64f92f0cd20602caccaea084a1091cf298210070de0f811d8e407/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/8f5a09841ff64f92f0cd20602caccaea084a1091cf298210070de0f811d8e407/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/40a2a57db1503510d08dde3abbfd37ed326ae1904181a87ecb55f97ef5aef21b
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/40a2a57db1503510d08dde3abbfd37ed326ae1904181a87ecb55f97ef5aef21b/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/40a2a57db1503510d08dde3abbfd37ed326ae1904181a87ecb55f97ef5aef21b/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/cf073d5890535d8291b524a73dac04a54ef5680c9a0221f5e683bea1ab5cda9d
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/cf073d5890535d8291b524a73dac04a54ef5680c9a0221f5e683bea1ab5cda9d/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/cf073d5890535d8291b524a73dac04a54ef5680c9a0221f5e683bea1ab5cda9d/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/0e29b403e5c0ca0e3d39358c1a6c458e6bd1995ad5bebbed6c6c6ff042240047
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/0e29b403e5c0ca0e3d39358c1a6c458e6bd1995ad5bebbed6c6c6ff042240047/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/0e29b403e5c0ca0e3d39358c1a6c458e6bd1995ad5bebbed6c6c6ff042240047/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/51dac416f165abde025d7c4a91ba9eae709760cf8316a4c8da452d3a574c465a
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/51dac416f165abde025d7c4a91ba9eae709760cf8316a4c8da452d3a574c465a/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/51dac416f165abde025d7c4a91ba9eae709760cf8316a4c8da452d3a574c465a/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/69d24ccca95f5dacebc4e690bc2240c0e4451134b8d998f786837293a0e1fc1b
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/69d24ccca95f5dacebc4e690bc2240c0e4451134b8d998f786837293a0e1fc1b/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/69d24ccca95f5dacebc4e690bc2240c0e4451134b8d998f786837293a0e1fc1b/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/86f363b7cc9b8bf22a88e263c2183917cc7e34ea099cc9cecbf9cc6061a34288
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/86f363b7cc9b8bf22a88e263c2183917cc7e34ea099cc9cecbf9cc6061a34288/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/86f363b7cc9b8bf22a88e263c2183917cc7e34ea099cc9cecbf9cc6061a34288/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/442c8383640ad7c329411f9fea2e06b023a6b56e9cd032a92c43ae376a860e36
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/442c8383640ad7c329411f9fea2e06b023a6b56e9cd032a92c43ae376a860e36/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/442c8383640ad7c329411f9fea2e06b023a6b56e9cd032a92c43ae376a860e36/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/2c7cd9d39220844d9ba803e686ecb4a2e44f7070c217b3d1fbb1baba30c7c5ff
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/2c7cd9d39220844d9ba803e686ecb4a2e44f7070c217b3d1fbb1baba30c7c5ff/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/2c7cd9d39220844d9ba803e686ecb4a2e44f7070c217b3d1fbb1baba30c7c5ff/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/69796df172f506b582a4f22596ed097744b9c7c43e15f51a7336ef4366f2c993
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/69796df172f506b582a4f22596ed097744b9c7c43e15f51a7336ef4366f2c993/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/69796df172f506b582a4f22596ed097744b9c7c43e15f51a7336ef4366f2c993/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/534a56350bb0d998e62e3833dc390d4850fe1be49744ab3b7c49158884669f16
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/534a56350bb0d998e62e3833dc390d4850fe1be49744ab3b7c49158884669f16/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/534a56350bb0d998e62e3833dc390d4850fe1be49744ab3b7c49158884669f16/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/e5396f91c04c5be612ed12bba26abf15c968c1c7614a2f9e00965605e9872a84
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/e5396f91c04c5be612ed12bba26abf15c968c1c7614a2f9e00965605e9872a84/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/e5396f91c04c5be612ed12bba26abf15c968c1c7614a2f9e00965605e9872a84/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/f39b29816f3d70a052e9f34623b77230a3b8a1ee8f1ac81b98b40fd49720ef60
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/f39b29816f3d70a052e9f34623b77230a3b8a1ee8f1ac81b98b40fd49720ef60/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/f39b29816f3d70a052e9f34623b77230a3b8a1ee8f1ac81b98b40fd49720ef60/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/a81d7a12c09857cf7823c1e5ed582f377b3891980ca76b9a8254c04d08ed0d29
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/a81d7a12c09857cf7823c1e5ed582f377b3891980ca76b9a8254c04d08ed0d29/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/a81d7a12c09857cf7823c1e5ed582f377b3891980ca76b9a8254c04d08ed0d29/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/8d97eda42cd3abf76bae5e89376185934d443099afb66052d28d6e7da8643c80
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/8d97eda42cd3abf76bae5e89376185934d443099afb66052d28d6e7da8643c80/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/8d97eda42cd3abf76bae5e89376185934d443099afb66052d28d6e7da8643c80/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/02117a2792592abf8d776f9b09e2239eb615b388f88c232db68adab987d1b2ac
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/02117a2792592abf8d776f9b09e2239eb615b388f88c232db68adab987d1b2ac/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/02117a2792592abf8d776f9b09e2239eb615b388f88c232db68adab987d1b2ac/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/a47ee82a9d2597d9424a207732b096855f35dc6af18d95ea0f22eb5059a7d41c
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/a47ee82a9d2597d9424a207732b096855f35dc6af18d95ea0f22eb5059a7d41c/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/a47ee82a9d2597d9424a207732b096855f35dc6af18d95ea0f22eb5059a7d41c/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/5d96ed706b361b51ea035f19be0c142c5f6e87f8cb4baf5d6826606aecc0cef0
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/5d96ed706b361b51ea035f19be0c142c5f6e87f8cb4baf5d6826606aecc0cef0/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/5d96ed706b361b51ea035f19be0c142c5f6e87f8cb4baf5d6826606aecc0cef0/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/1326c5f5afb142919842dd653e8e9b6e14c4b124452b48a6ac1b9a48c58a1e25
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/1326c5f5afb142919842dd653e8e9b6e14c4b124452b48a6ac1b9a48c58a1e25/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/1326c5f5afb142919842dd653e8e9b6e14c4b124452b48a6ac1b9a48c58a1e25/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/91370bf3adfc5a56e6e89651f1a013528584fdad7f8ab0d5c6f0471726117f6a
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/91370bf3adfc5a56e6e89651f1a013528584fdad7f8ab0d5c6f0471726117f6a/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/91370bf3adfc5a56e6e89651f1a013528584fdad7f8ab0d5c6f0471726117f6a/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/3d488bc2be5cb534884caefc24b78a824363e64d5d9717b8c212531c175deac7
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/3d488bc2be5cb534884caefc24b78a824363e64d5d9717b8c212531c175deac7/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/3d488bc2be5cb534884caefc24b78a824363e64d5d9717b8c212531c175deac7/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/e26b44cbd094a7e564629c2e7b16fe27929a67be5e6263b58885e4b2d8fe68d5
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/e26b44cbd094a7e564629c2e7b16fe27929a67be5e6263b58885e4b2d8fe68d5/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/e26b44cbd094a7e564629c2e7b16fe27929a67be5e6263b58885e4b2d8fe68d5/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/5ff8a887efc4827ef49c27184b1cc7c30abf63e8835cb5fc4263d70978309f0f
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/5ff8a887efc4827ef49c27184b1cc7c30abf63e8835cb5fc4263d70978309f0f/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/5ff8a887efc4827ef49c27184b1cc7c30abf63e8835cb5fc4263d70978309f0f/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/6e6dbafac200825fd473107f01c401ec3c84a6d55f516f9820d7e5ff5be5803c
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/6e6dbafac200825fd473107f01c401ec3c84a6d55f516f9820d7e5ff5be5803c/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/6e6dbafac200825fd473107f01c401ec3c84a6d55f516f9820d7e5ff5be5803c/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/7563c0d80f403b4ffc5c1354769310b1f406c6f898d5ef892193def811ef384c
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/7563c0d80f403b4ffc5c1354769310b1f406c6f898d5ef892193def811ef384c/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/7563c0d80f403b4ffc5c1354769310b1f406c6f898d5ef892193def811ef384c/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/56f95ec5cf0c610d223ce1af230e321f535adb7940d9ac5e3053bc480ac3d2c3
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/56f95ec5cf0c610d223ce1af230e321f535adb7940d9ac5e3053bc480ac3d2c3/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/56f95ec5cf0c610d223ce1af230e321f535adb7940d9ac5e3053bc480ac3d2c3/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/96bfbdd5745cf40d17638bb3b4da68e8d1f662a74387c4de854befcebcda3c03
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/96bfbdd5745cf40d17638bb3b4da68e8d1f662a74387c4de854befcebcda3c03/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/96bfbdd5745cf40d17638bb3b4da68e8d1f662a74387c4de854befcebcda3c03/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/34913b6668104dd098844e7840bd4f4bcaf1566c4843e9dc32d6ab7c8edc7e1b
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/34913b6668104dd098844e7840bd4f4bcaf1566c4843e9dc32d6ab7c8edc7e1b/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/34913b6668104dd098844e7840bd4f4bcaf1566c4843e9dc32d6ab7c8edc7e1b/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/49a0d58288b1a57e55dda00180b1859455ba5249a8c200ddb10ccf9c90bc56ca
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/49a0d58288b1a57e55dda00180b1859455ba5249a8c200ddb10ccf9c90bc56ca/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/49a0d58288b1a57e55dda00180b1859455ba5249a8c200ddb10ccf9c90bc56ca/mgnipy_page_1.json
DEBUG:mgnipy.mgnipy:Processing cache subdirectory /Users/anglup/Library/Caches/mgnipy/8edc9be2ffaaf9a909893f67c55649d0c2e1ede755f891a87829908688ba9a99
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/8edc9be2ffaaf9a909893f67c55649d0c2e1ede755f891a87829908688ba9a99/mgnipy_manifest.json
DEBUG:mgnipy.mgnipy:Clearing cache file /Users/anglup/Library/Caches/mgnipy/8edc9be2ffaaf9a909893f67c55649d0c2e1ede755f891a87829908688ba9a99/mgnipy_page_1.json

---

## Wrap Up:

This page was a quick start demonstration of:

1. ✅ Start up a `mgnipy.MGnipy` client with your desired configuration

2. ✅ Search in MGnify resources using a MGnifier glass

3. ✅ Receive a MGazine of MGnify datasets