# Demo: Integrating multiple studies

In this notebook we will try to recreate the analyses: 

[ABaCo demo: Parkinson's disease gut microbiome](https://mona-abaco.readthedocs.io/en/latest/tutorial/demo-parkinson.html)

> _This notebook is used as a demo of ABaCo's capabilities on integrating multiple studies with multiple biomes. In this case, the Parkinson's dataset contains samples from the gut microbiome from 5 different studies._

but starting from mgnipy to get taxa tables and metadata

In [2]:
from mgnipy import MGnipy

# configuring
mg = MGnipy(
    # configuration
    cache_dir="cache",
)

## Finding the studies

In [3]:
# search for parkinson's disease gut microbiome studies
mg_pd = mg.studies(
    biome_lineage='root:Host-associated:Human:Digestive system:Large intestine:Fecal',
    search=["parkinson's"]
)

# preview how many requests
mg_pd.explain()

https://www.ebi.ac.uk/metagenomics/api/v2/studies?biome_lineage=root%3AHost-associated%3AHuman%3ADigestive+system%3ALarge+intestine%3AFecal&search=parkinson%27s&page=1

now making the one get request to see the initial list of studies matching our above filter criteria

In [4]:
# getting the initial list of pd studies
mg_pd.get()

# view results as df, optional 
mg_pd.to_df(expand_nested_dicts=True)

,accession,ena_accessions,title,updated_at,biome__biome_name,biome__lineage
0,MGYS00006121,"[ERP142200, PRJEB57228]",Dietary intervention of people with Parkinson'...,2026-04-30T20:43:39.212000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
1,MGYS00001650,"[ERP004264, PRJEB4927]",Alterations of the Fecal Microbiome in Parkins...,2026-05-05T20:40:26.274000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
2,MGYS00005129,"[ERP109659, PRJEB27564]",Gut microbiota in Parkinson's disease: tempora...,2026-05-06T12:25:31.349000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
3,MGYS00006759,"[ERP146353, PRJEB61255]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-01T18:17:46.386000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
4,MGYS00006760,"[ERP148661, PRJEB63522]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-01T18:22:34.794000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
5,MGYS00005130,"[ERP112853, PRJEB30401]",Gut Microbiome Alterations Drive Distinct Meta...,2026-05-06T10:02:48.163000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
6,MGYS00005755,"[PRJNA510730, SRP173877]",Microbiota composition of Parkinson's disease ...,2026-05-06T11:35:50.490000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...

## Getting some Metadata

that's nice but let's take a look at the studies details. We can use `.enrich_details()` which will basically `.get_detail()` for all studies. 

Below we use the async version `.aenrich_details()`

In [5]:
await mg_pd.aenrich_details(
    limit=10, #optional, number of details to enrich in this call
    hide_progress=False # optional, whether to hide progress bar
)

Enriching details: 100%|██████████| 7/7 [00:03<00:00,  2.06it/s]

to check it out we can use `.details_results` or `.details_df()`

In [6]:
mg_pd.details_df(expand_nested_dicts=True)

,accession,ena_accessions,title,updated_at,downloads,first_accession,metadata__study_name,metadata__center_name,metadata__study_title,metadata__study_accession,metadata__study_description,metadata__secondary_study_accession,biome__biome_name,biome__lineage
0,MGYS00006121,"[ERP142200, PRJEB57228]",Dietary intervention of people with Parkinson'...,2026-04-30T20:43:39.212000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",ERP142200,NaN,NaN,NaN,NaN,NaN,NaN,Fecal,root:Host-associated:Human:Digestive system:La...
1,MGYS00001650,"[ERP004264, PRJEB4927]",Alterations of the Fecal Microbiome in Parkins...,2026-05-05T20:40:26.274000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",ERP004264,Fecal Microbiome in Parkinson's Disease,Institute of Biotechnology;University of Helsi...,Alterations of the Fecal Microbiome in Parkins...,PRJEB4927,"In the course of Parkinson’s disease (PD), the...",ERP004264,Fecal,root:Host-associated:Human:Digestive system:La...
2,MGYS00005129,"[ERP109659, PRJEB27564]",Gut microbiota in Parkinson's disease: tempora...,2026-05-06T12:25:31.349000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",ERP109659,Parkinson's disease gut microbiota follow-up,Institute of Biotechnology;University of Helsi...,Gut microbiota in Parkinson's disease: tempora...,PRJEB27564,Aiming to explore the temporal stability of gu...,ERP109659,Fecal,root:Host-associated:Human:Digestive system:La...
3,MGYS00006759,"[ERP146353, PRJEB61255]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-01T18:17:46.386000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",ERP146353,NaN,NaN,NaN,NaN,NaN,NaN,Fecal,root:Host-associated:Human:Digestive system:La...
4,MGYS00006760,"[ERP148661, PRJEB63522]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-01T18:22:34.794000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",ERP148661,NaN,NaN,NaN,NaN,NaN,NaN,Fecal,root:Host-associated:Human:Digestive system:La...
5,MGYS00005130,"[ERP112853, PRJEB30401]",Gut Microbiome Alterations Drive Distinct Meta...,2026-05-06T10:02:48.163000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",ERP112853,Gut Microbiome and Parkinson's Disease,University of Cagliari,Gut Microbiome Alterations Drive Distinct Meta...,PRJEB30401,Parkinson's disease is a neurodegenerative dis...,ERP112853,Fecal,root:Host-associated:Human:Digestive system:La...
6,MGYS00005755,"[PRJNA510730, SRP173877]",Microbiota composition of Parkinson's disease ...,2026-05-06T11:35:50.490000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",SRP173877,NaN,NaN,NaN,NaN,NaN,NaN,Fecal,root:Host-associated:Human:Digestive system:La...

- Study and Analysis details have download fields. 
- In a given `Study` / `AnalysisDetail` you can take a closer look via their `.downloads` list
- in `MGnifyList`s such as `Studies` and `Analyses` all their detail downloads are combined into a `.details_downloads` list

In [7]:
# checking out 0th in download
mg_pd.details_downloads[0]

{'file_type': 'tsv',
 'download_type': 'Taxonomic analysis',
 'short_description': 'Phylum level taxonomies SSU',
 'long_description': 'Phylum level taxonomies SSU (TSV)',
 'alias': 'ERP142200_phylum_taxonomy_abundances_SSU_v5.0.tsv',
 'download_group': 'study_summary.v5.0.taxonomic_analysis_ssu_rrna',
 'file_size_bytes': None,
 'index_files': None,
 'url': None,
 'accession': 'MGYS00006121',
 'pipeline_version': 'v5'}

there's also a `.downloads_df()`

In [8]:
# accessing downloads_df and checking out pipeline versions
mg_pd.downloads_df['pipeline_version'].value_counts()

pipeline_version
v4_1    32
v5      21
v6      12
v3       3
Name: count, dtype: int64

These downloads lists are used in `MGazine`s to download, read in and curate mgnify datasets with metadata. 

The `MGazine` for this `Studies` list i.e., `mg_pd` can be accessed via `.datasets` attribute

## Retrieving the datasets

In [9]:
# getting mgazine
mz = mg_pd.datasets

# we can print more info about the mgazine dataset
print(mz)

MGazine containing:
- MGnify pipeline versions: ['v3', 'v4_1', 'v5', 'v6']
- Number of downloads: 68
- Short descriptions: ['Complete GO annotation',
 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -PR2 as ref DB',
 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -SILVA as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using ITSoneDB as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using PR2 as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using SILVA-LSU as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using SILVA-SSU as ref DB',
 'GO slim annotation',
 'InterPro matches',
 'Phylum level taxonomies',
 'Phylum level taxonomies LSU',
 'Phylum level taxonomies SSU',
 'Summary of DADA2-PR2 taxonomies',
 'Summary of DADA2-SILVA taxonomies',
 'Summary of ITSoneDB taxonomies',
 'Summary of PR2 taxonomies',
 'Summary of SILVA-LSU taxonomies',
 'Summary of SILVA-SSU taxonomies',
 'Taxonomic assignments',
 'Taxonomic assignments LSU',
 'Taxonomic assignments SSU',
 'Taxonomic diversity metrics']

Further filtered mgazine datasets or curations can be accessed via:
- calling attributes corresponding to specific pipeline versions i.e., `.v3`
- using the short description as a subscript i.e., `["Complete GO annotation"]`

for example let's say we are interested in 'Taxonomic assignments SSU' from pipeline 4.1

In [10]:
# checking out the v4.1 datasets
print(mz.v4_1)

MGazine containing:
- MGnify pipeline versions: ['v4_1']
- Number of downloads: 32
- Short descriptions: ['DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -PR2 as ref DB',
 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -SILVA as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using ITSoneDB as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using PR2 as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using SILVA-LSU as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using SILVA-SSU as ref DB',
 'Phylum level taxonomies LSU',
 'Phylum level taxonomies SSU',
 'Summary of DADA2-PR2 taxonomies',
 'Summary of DADA2-SILVA taxonomies',
 'Summary of ITSoneDB taxonomies',
 'Summary of PR2 taxonomies',
 'Summary of SILVA-LSU taxonomies',
 'Summary of SILVA-SSU taxonomies',
 'Taxonomic assignments LSU',
 'Taxonomic assignments SSU']

In [11]:
# accessing the taxonomic assignments SSU dataset in v4.1
tax_ssu_cur = mz.v4_1['Taxonomic assignments SSU']
# sanity check
print(tax_ssu_cur)

MGazine Curation TaxaCurator containing:
- MGnify pipeline versions: ['v4_1']
- Number of downloads: 2
- Short descriptions: ['Taxonomic assignments SSU']

we can get out the curated taxonomic datasets as

- `to_pandas`()
- `to_polars()` as polars dataframe
    - `lazy_merged` for polars lazyframe
- `X()` for array of values only, to either polars or pandas
- `metadata()` for mgnify enriched runs/study/sample etc metadata, to either polars or pandas
- `taxonomic_metadata()` for taxonomic ranks data, to either polars or pandas
- `to_anndata()` **(not for DwC-ready)**
    - its data `X` from `X()`
    - `var` annotations from `metadata()`
    - `obs` annotations form `taxonomic_metadata()`

![Note] check out the getting started with anndata page for an intro

In [12]:
# getting the annotated dataframe
ad = tax_ssu_cur.to_anndata()
print(ad)
# looking at the obs metadta
ad.obs.head()

AnnData object with n_obs × n_vars = 2286 × 413
    obs: 'Superkingdom', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'
    var: 'experiment_type', 'instrument_model', 'instrument_platform', 'sample_accession', 'study_accession', 'sample__accession', 'sample__ena_accessions', 'sample__sample_title', 'sample__biome', 'sample__updated_at', 'study__accession', 'study__ena_accessions', 'study__title', 'study__updated_at', 'study__biome.biome_name', 'study__biome.lineage'

/Users/phanthanourak/.pyenv/versions/3.11.14/lib/python3.11/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

,Superkingdom,Kingdom,Phylum,Class,Order,Family,Genus,Species
0,Archaea,NA,NA,NA,NA,NA,NA,NA
1,Archaea,NA,Euryarchaeota,NA,NA,NA,NA,NA
2,Archaea,NA,Euryarchaeota,NA,NA,NA,NA,methanogenic_archaeon_CH1270
3,Archaea,NA,Euryarchaeota,Methanobacteria,Methanobacteriales,NA,NA,NA
4,Archaea,NA,Euryarchaeota,Methanobacteria,Methanobacteriales,Methanobacteriaceae,NA,NA

- notice the warning:
    ```
    WARNING:root:No runs have been enriched yet. Returning empty metadata DataFrame. Please run `enrich_runs()` first to populate the metadata.
    ```

- and that there is no `var` in the anndataframe: 
    ```
    AnnData object with n_obs × n_vars = 2286 × 413
        obs: 'Superkingdom', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'
    ```

- we can enrich with metadata using `enrich_runs()` which will call a bunch of `RunDetails` 

- alternatively run level metadata can be passed on to `runs_results: list[dict] = ...`

In [13]:
tax_ssu_cur.enrich_runs(limit=None)

Enriching runs: 100%|██████████| 413/413 [00:00<?, ?it/s]

In [16]:
ad_more = tax_ssu_cur.to_anndata()
print(ad_more)
ad_more.var.head()

AnnData object with n_obs × n_vars = 2286 × 413
    obs: 'Superkingdom', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'
    var: 'experiment_type', 'instrument_model', 'instrument_platform', 'sample_accession', 'study_accession', 'sample__accession', 'sample__ena_accessions', 'sample__sample_title', 'sample__biome', 'sample__updated_at', 'study__accession', 'study__ena_accessions', 'study__title', 'study__updated_at', 'study__biome.biome_name', 'study__biome.lineage'

/Users/phanthanourak/.pyenv/versions/3.11.14/lib/python3.11/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

,experiment_type,instrument_model,instrument_platform,sample_accession,study_accession,sample__accession,sample__ena_accessions,sample__sample_title,sample__biome,sample__updated_at,study__accession,study__ena_accessions,study__title,study__updated_at,study__biome.biome_name,study__biome.lineage
accession,,,,,,,,,,,,,,,,
ERR2730148,Amplicon,None,None,SAMEA4821212,MGYS00005129,SAMEA4821212,"[ERS2641102, SAMEA4821212]",None,None,2026-05-05T20:34:37.322000+00:00,MGYS00005129,"[ERP109659, PRJEB27564]",Gut microbiota in Parkinson's disease: tempora...,2026-05-06T12:25:31.349000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
ERR2730149,Amplicon,None,None,SAMEA4821213,MGYS00005129,SAMEA4821213,"[ERS2641103, SAMEA4821213]",None,None,2026-05-05T20:34:37.614000+00:00,MGYS00005129,"[ERP109659, PRJEB27564]",Gut microbiota in Parkinson's disease: tempora...,2026-05-06T12:25:31.349000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
ERR2730150,Amplicon,None,None,SAMEA4821214,MGYS00005129,SAMEA4821214,"[SAMEA4821214, ERS2641104]",None,None,2026-05-05T20:35:28.231000+00:00,MGYS00005129,"[ERP109659, PRJEB27564]",Gut microbiota in Parkinson's disease: tempora...,2026-05-06T12:25:31.349000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
ERR2730151,Amplicon,None,None,SAMEA4821215,MGYS00005129,SAMEA4821215,"[SAMEA4821215, ERS2641105]",None,None,2026-05-05T20:35:01.984000+00:00,MGYS00005129,"[ERP109659, PRJEB27564]",Gut microbiota in Parkinson's disease: tempora...,2026-05-06T12:25:31.349000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
ERR2730152,Amplicon,None,None,SAMEA4821216,MGYS00005129,SAMEA4821216,"[SAMEA4821216, ERS2641106]",None,None,2026-05-05T20:34:37.876000+00:00,MGYS00005129,"[ERP109659, PRJEB27564]",Gut microbiota in Parkinson's disease: tempora...,2026-05-06T12:25:31.349000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...