# `MGazine` of MGnify data

```{margin}
After clicking the "Activate Notebook" button you can run the cells in this browser. Alternatively, you can also click on the 🚀 to launch in colab or binder. 
```
<button title="Make live" style="display:inline-flex;align-items:center;gap:0.4rem;padding:0.5rem 1rem;border:0;border-radius:20px;background:linear-gradient(135deg,#0f766e,#14b8a6);color:white;cursor:pointer;font-size:1rem;" class="thebe-button" onclick="initThebeSBT()">Activate Notebook</button>

## What is a `mgnipy.MGazine`?

Study and Analysis details include **'downloads'** fields which contain information such as types, short descriptions, urls etc about the datasets outputed from MGnify pipelines.

`mgnipy.MGazine` as well as more analysis-specific classes such as `TaxaMGazine` and `DWCTaxaMGazine` can be used to download the datasets onto disk or read them into our notebooks. 

For downloading, MGazine supports the downloading of all filetypes. For streaming (via `mixins.StreamMixin`), the supported filetypes are: 

- TSV/CSV — stream_pandas (pandas) or stream_polars (polars) (handles gzipped TSV/CSV).
- TXT — stream_txt (full text or line-chunks).
- HTML — stream_html (opens in browser).
- FASTA / GFF / BIOM — stream_fasta, stream_gff, stream_biom (scikit-bio generators).
- JSONL / NDJSON — stream_jsonl (pandas or polars).
- Tree / Newick — stream_tree (scikit-bio).
- Other — JSON files under other are streamed via stream_json; binary/unsupported types should be downloaded.

---

## Accessing a MGazine from a `MGnifier` search

Recalling,
1. Start up a `mgnipy.MGnipy` client with your desired configuration
2. Search in MGnify resources using a `mgnipy.MGnifier` glass
3. **Receive a `mgnipy.MGazine` of MGnify datasets**

For step 2 specifically the following mgnifiers can output a mgazine:
- `proxies.Study` 
- `proxies.Analysis`
- `proxies.Studies` 
- `proxies.Analyses`

In this demonstration we will get the `MGazine` of a single study, but this would be the same for a multi-study collection of `proxies.Studies`

In [1]:
from mgnipy import MGnipy

# 1. init with default config
MG = MGnipy()

# 2. search up a study/analysis detail or a list of studies/analyses and get their details
study = MG.study("MGYS00010442")
study.get()

DEBUG:numcodecs:Registering codec 'zlib'
DEBUG:numcodecs:Registering codec 'gzip'
DEBUG:numcodecs:Registering codec 'bz2'
DEBUG:numcodecs:Registering codec 'lzma'
DEBUG:numcodecs:Registering codec 'blosc'
DEBUG:numcodecs:Registering codec 'zstd'
DEBUG:numcodecs:Registering codec 'lz4'
DEBUG:numcodecs:Registering codec 'astype'
DEBUG:numcodecs:Registering codec 'delta'
DEBUG:numcodecs:Registering codec 'quantize'
DEBUG:numcodecs:Registering codec 'fixedscaleoffset'
DEBUG:numcodecs:Registering codec 'packbits'
DEBUG:numcodecs:Registering codec 'categorize'
DEBUG:numcodecs:Registering codec 'pickle'
DEBUG:numcodecs:Registering codec 'base64'
DEBUG:numcodecs:Registering codec 'shuffle'
DEBUG:numcodecs:Registering codec 'bitround'
DEBUG:numcodecs:Registering codec 'crc32'
DEBUG:numcodecs:Registering codec 'adler32'
DEBUG:numcodecs:Registering codec 'jenkins_lookup3'
DEBUG:numcodecs:Registering codec 'json2'
DEBUG:numcodecs:Registering codec 'vlen-utf8'
DEBUG:numcodecs:Registering codec 'vlen-bytes'
DEBUG:numcodecs:Registering codec 'vlen-array'
DEBUG:numcodecs:Registering codec 'fletcher32'
DEBUG:numcodecs:Registering codec 'crc32c'
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'study': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource study
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11f3b83d0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x11faeede0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11f38e910>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Sun, 31 May 2026 21:59:57 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for study
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for study
INFO:mgnipy.V2.query_set:Attempting to load cached results for study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 768fc2f41c6c0883b90ae9313e062236ee48d423071cc85bf7926f6e5f31dd98
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/768fc2f41c6c0883b90ae9313e062236ee48d423071cc85bf7926f6e5f31dd98
INFO:mgnipy.V2.mixins:Loading cached page from /Users/anglup/Library/Caches/mgnipy/768fc2f41c6c0883b90ae9313e062236ee48d423071cc85bf7926f6e5f31dd98/mgnipy_page_1.json
INFO:mgnipy.V2.query_set:Loaded pages [1] from cache for resource study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 768fc2f41c6c0883b90ae9313e062236ee48d423071cc85bf7926f6e5f31dd98
INFO:mgnipy.V2.mixins:Loading cache manifest from /Users/anglup/Library/Caches/mgnipy/768fc2f41c6c0883b90ae9313e062236ee48d423071cc85bf7926f6e5f31dd98/mgnipy_manifest.json
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=0 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 1 items (max page 1): [1]
INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for study page 1: True
INFO:mgnipy.V2.query_executor:Page 1 already retrieved.

{'accession': 'MGYS00010442',
 'ena_accessions': ['PRJEB37289', 'ERP120598'],
 'title': 'TKI',
 'biome': {'biome_name': 'Digestive system',
  'lineage': 'root:Host-associated:Human:Digestive system'},
 'updated_at': '2026-04-21T08:55:57.196000+00:00',
 'downloads': [{'file_type': 'tsv',
   'download_type': 'Taxonomic analysis',
   'short_description': 'Summary of DADA2-PR2 taxonomies',
   'long_description': 'Summary of DADA2-PR2 taxonomic assignments, across all runs in the study',
   'alias': 'ERP120598_DADA2-PR2_16S-V3-V4_study_summary.tsv',
   'download_group': 'study_summary.v6.amplicon',
   'file_size_bytes': None,
   'index_files': None,
   'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-PR2_16S-V3-V4_study_summary.tsv'},
  {'file_type': 'tsv',
   'download_type': 'Taxonomic analysis',
   'short_description': 'Summary of PR2 taxonomies',
   'long_description': 'Summary of PR2 taxonomic assignments, across all runs in the study',
   'alias': 'ERP120598_PR2_study_summary.tsv',
   'download_group': 'study_summary.v6.amplicon',
   'file_size_bytes': None,
   'index_files': None,
   'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_PR2_study_summary.tsv'},
  {'file_type': 'tsv',
   'download_type': 'Taxonomic analysis',
   'short_description': 'Summary of DADA2-SILVA taxonomies',
   'long_description': 'Summary of DADA2-SILVA taxonomic assignments, across all runs in the study',
   'alias': 'ERP120598_DADA2-SILVA_16S-V3-V4_study_summary.tsv',
   'download_group': 'study_summary.v6.amplicon',
   'file_size_bytes': None,
   'index_files': None,
   'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-SILVA_16S-V3-V4_study_summary.tsv'},
  {'file_type': 'tsv',
   'download_type': 'Taxonomic analysis',
   'short_description': 'Summary of SILVA-SSU taxonomies',
   'long_description': 'Summary of SILVA-SSU taxonomic assignments, across all runs in the study',
   'alias': 'ERP120598_SILVA-SSU_study_summary.tsv',
   'download_group': 'study_summary.v6.amplicon',
   'file_size_bytes': None,
   'index_files': None,
   'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_SILVA-SSU_study_summary.tsv'},
  {'file_type': 'csv',
   'download_type': 'Taxonomic analysis',
   'short_description': 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -PR2 as ref DB',
   'long_description': 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -PR2 as ref DB, across all runs in the study',
   'alias': 'ERP120598_DADA2-PR2_16S-V3-V4_dwcready.csv',
   'download_group': 'study_summary.v6.amplicon',
   'file_size_bytes': None,
   'index_files': None,
   'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-PR2_16S-V3-V4_dwcready.csv'},
  {'file_type': 'csv',
   'download_type': 'Taxonomic analysis',
   'short_description': 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -SILVA as ref DB',
   'long_description': 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -SILVA as ref DB, across all runs in the study',
   'alias': 'ERP120598_DADA2-SILVA_16S-V3-V4_dwcready.csv',
   'download_group': 'study_summary.v6.amplicon',
   'file_size_bytes': None,
   'index_files': None,
   'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-SILVA_16S-V3-V4_dwcready.csv'},
  {'file_type': 'csv',
   'download_type': 'Taxonomic analysis',
   'short_description': 'DwC-Ready summary of closed-ref taxonomies using SILVA-SSU as ref DB',
   'long_description': 'DwC-Ready summary of closed-reference taxonomies using SILVA-SSU as ref DB, across all runs in the study',
   'alias': 'ERP120598_closedref_SILVA-SSU_dwcready.csv',
   'download_group': 'study_summary.v6.amplicon',
   'file_size_bytes': None,
   'index_files': None,
   'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_closedref_SILVA-SSU_dwcready.csv'},
  {'file_type': 'csv',
   'download_type': 'Taxonomic analysis',
   'short_description': 'DwC-Ready summary of closed-ref taxonomies using PR2 as ref DB',
   'long_description': 'DwC-Ready summary of closed-reference taxonomies using PR2 as ref DB, across all runs in the study',
   'alias': 'ERP120598_closedref_PR2_dwcready.csv',
   'download_group': 'study_summary.v6.amplicon',
   'file_size_bytes': None,
   'index_files': None,
   'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_closedref_PR2_dwcready.csv'}],
 'metadata': {},
 'first_accession': 'ERP120598'}

MGazines for a given study or analysis detail can be accessed via their `.datasets` attributes

In [2]:
# access the study's mgazine
mz = study.datasets

# check it out 
print(mz)

DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.mixins:Converting results to pandas DataFrame; expand_nested_dicts=False
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning record iterator for study
DEBUG:mgnipy.V2.query_set:Flattening paginated results for study
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.proxies:Updating download info with identifier 'MGYS00010442' to id_param_key 'accession'
DEBUG:mgnipy.V2.mixins:Converting results to pandas DataFrame; expand_nested_dicts=False
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning record iterator for study
DEBUG:mgnipy.V2.query_set:Flattening paginated results for study
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.proxies:Could not parse pipeline version from 'v6' for download {'file_type': 'tsv', 'download_type': 'Taxonomic analysis', 'short_description': 'Summary of PR2 taxonomies', 'long_description': 'Summary of PR2 taxonomic assignments, across all runs in the study', 'alias': 'ERP120598_PR2_study_summary.tsv', 'download_group': 'study_summary.v6.amplicon', 'file_size_bytes': None, 'index_files': None, 'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_PR2_study_summary.tsv', 'accession': 'MGYS00010442'}: could not convert string to float: 'v6'
DEBUG:mgnipy.V2.proxies:Could not parse pipeline version from 'v6' for download {'file_type': 'tsv', 'download_type': 'Taxonomic analysis', 'short_description': 'Summary of DADA2-SILVA taxonomies', 'long_description': 'Summary of DADA2-SILVA taxonomic assignments, across all runs in the study', 'alias': 'ERP120598_DADA2-SILVA_16S-V3-V4_study_summary.tsv', 'download_group': 'study_summary.v6.amplicon', 'file_size_bytes': None, 'index_files': None, 'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-SILVA_16S-V3-V4_study_summary.tsv', 'accession': 'MGYS00010442'}: could not convert string to float: 'v6'
DEBUG:mgnipy.V2.proxies:Could not parse pipeline version from 'v6' for download {'file_type': 'tsv', 'download_type': 'Taxonomic analysis', 'short_description': 'Summary of SILVA-SSU taxonomies', 'long_description': 'Summary of SILVA-SSU taxonomic assignments, across all runs in the study', 'alias': 'ERP120598_SILVA-SSU_study_summary.tsv', 'download_group': 'study_summary.v6.amplicon', 'file_size_bytes': None, 'index_files': None, 'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_SILVA-SSU_study_summary.tsv', 'accession': 'MGYS00010442'}: could not convert string to float: 'v6'
DEBUG:mgnipy.V2.proxies:Could not parse pipeline version from 'v6' for download {'file_type': 'csv', 'download_type': 'Taxonomic analysis', 'short_description': 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -PR2 as ref DB', 'long_description': 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -PR2 as ref DB, across all runs in the study', 'alias': 'ERP120598_DADA2-PR2_16S-V3-V4_dwcready.csv', 'download_group': 'study_summary.v6.amplicon', 'file_size_bytes': None, 'index_files': None, 'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-PR2_16S-V3-V4_dwcready.csv', 'accession': 'MGYS00010442'}: could not convert string to float: 'v6'
DEBUG:mgnipy.V2.proxies:Could not parse pipeline version from 'v6' for download {'file_type': 'csv', 'download_type': 'Taxonomic analysis', 'short_description': 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -SILVA as ref DB', 'long_description': 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -SILVA as ref DB, across all runs in the study', 'alias': 'ERP120598_DADA2-SILVA_16S-V3-V4_dwcready.csv', 'download_group': 'study_summary.v6.amplicon', 'file_size_bytes': None, 'index_files': None, 'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-SILVA_16S-V3-V4_dwcready.csv', 'accession': 'MGYS00010442'}: could not convert string to float: 'v6'
DEBUG:mgnipy.V2.proxies:Could not parse pipeline version from 'v6' for download {'file_type': 'csv', 'download_type': 'Taxonomic analysis', 'short_description': 'DwC-Ready summary of closed-ref taxonomies using SILVA-SSU as ref DB', 'long_description': 'DwC-Ready summary of closed-reference taxonomies using SILVA-SSU as ref DB, across all runs in the study', 'alias': 'ERP120598_closedref_SILVA-SSU_dwcready.csv', 'download_group': 'study_summary.v6.amplicon', 'file_size_bytes': None, 'index_files': None, 'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_closedref_SILVA-SSU_dwcready.csv', 'accession': 'MGYS00010442'}: could not convert string to float: 'v6'
DEBUG:mgnipy.V2.proxies:Could not parse pipeline version from 'v6' for download {'file_type': 'csv', 'download_type': 'Taxonomic analysis', 'short_description': 'DwC-Ready summary of closed-ref taxonomies using PR2 as ref DB', 'long_description': 'DwC-Ready summary of closed-reference taxonomies using PR2 as ref DB, across all runs in the study', 'alias': 'ERP120598_closedref_PR2_dwcready.csv', 'download_group': 'study_summary.v6.amplicon', 'file_size_bytes': None, 'index_files': None, 'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_closedref_PR2_dwcready.csv', 'accession': 'MGYS00010442'}: could not convert string to float: 'v6'
DEBUG:mgnipy.V2.mixins:Converting results to pandas DataFrame; expand_nested_dicts=False
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning record iterator for study
DEBUG:mgnipy.V2.query_set:Flattening paginated results for study
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]

MGazine containing:
- MGnify pipeline versions: ['v6']
- Number of downloads: 8
- Short descriptions: ['DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -PR2 as ref DB',
 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -SILVA as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using PR2 as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using SILVA-SSU as ref DB',
 'Summary of DADA2-PR2 taxonomies',
 'Summary of DADA2-SILVA taxonomies',
 'Summary of PR2 taxonomies',
 'Summary of SILVA-SSU taxonomies']

As we see above, the __str__ representaiton of mgazine gives us a peak into the pipeline versions within, number of downloads and the short_description categories

## Navigating and filtering a `MGazine`

Built in to mgazine, you can filter the mgazine to a specific pipeline versions and short_descriptions which will return a mgazine again but filtered or a curated mgazine with additional functionalities if available ✨.

FOr accessing a specific pipeline version you can call the veresion as an attribute:

In [3]:
# above we saw that v6 is the only one so this will return the same basically
v6_data = mz.v6

# if we print again we will see the same info
print(v6_data)

INFO:mgnipy.V2.datasets:Setting up mgazine only for datasets of pipeline version v6 via attribute access.

MGazine containing:
- MGnify pipeline versions: ['v6']
- Number of downloads: 8
- Short descriptions: ['DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -PR2 as ref DB',
 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -SILVA as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using PR2 as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using SILVA-SSU as ref DB',
 'Summary of DADA2-PR2 taxonomies',
 'Summary of DADA2-SILVA taxonomies',
 'Summary of PR2 taxonomies',
 'Summary of SILVA-SSU taxonomies']

You can filter by short descriptioins by passing them as you would an index into square brackets i..e, __getitem__

In [4]:
# we want the taxonomic assignments
ssu = v6_data['Summary of SILVA-SSU taxonomies']

# checking out what it is 
print(type(ssu))
print(ssu)

# also downloads_df  
ssu.downloads_df

INFO:mgnipy.V2.datasets:Download type for Summary of SILVA-SSU taxonomies: taxonomic analysis
DEBUG:mgnipy.V2.datasets:getting taxonomic datasets of short description Summary of SILVA-SSU taxonomies via item access.
INFO:mgnipy.V2.datasets.taxonomic:TaxaMGazine initialized for short description: Summary of SILVA-SSU taxonomies
INFO:mgnipy.V2.datasets.taxonomic:TaxaMGazine long to short rank mapping set: {'Superkingdom': 'sk', 'Kingdom': 'k', 'Phylum': 'p', 'Class': 'c', 'Order': 'o', 'Family': 'f', 'Genus': 'g', 'Species': 's'}
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11f38f590>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x11faef650> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11f9fdd10>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Sun, 31 May 2026 21:59:57 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP120598_SILVA-SSU_study_summary.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_SILVA-SSU_study_summary.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for TaxaMGazine_Summary of SILVA-SSU taxonomies
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Summary of SILVA-SSU taxonomies: 3393c11280f05979b886961e2fbd12b4bde0fb346b7fc6210085737b2f716e4e
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Summary of SILVA-SSU taxonomies: 3393c11280f05979b886961e2fbd12b4bde0fb346b7fc6210085737b2f716e4e
INFO:mgnipy.V2.mixins:Loading cache for TaxaMGazine_Summary of SILVA-SSU taxonomies from /Users/anglup/Library/Caches/mgnipy/3393c11280f05979b886961e2fbd12b4bde0fb346b7fc6210085737b2f716e4e
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Summary of SILVA-SSU taxonomies: 3393c11280f05979b886961e2fbd12b4bde0fb346b7fc6210085737b2f716e4e
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/3393c11280f05979b886961e2fbd12b4bde0fb346b7fc6210085737b2f716e4e
INFO:mgnipy.V2.mixins:No cache directory found at /Users/anglup/Library/Caches/mgnipy/3393c11280f05979b886961e2fbd12b4bde0fb346b7fc6210085737b2f716e4e
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Summary of SILVA-SSU taxonomies: 3393c11280f05979b886961e2fbd12b4bde0fb346b7fc6210085737b2f716e4e
INFO:mgnipy.V2.mixins:Loaded 0 cached pages

<class 'mgnipy.V2.datasets.taxonomic.TaxaMGazine'>
MGazine Curation TaxaMGazine containing:
- MGnify pipeline versions: ['v6']
- Number of downloads: 1
- Short descriptions: ['Summary of SILVA-SSU taxonomies']

,file_type,download_type,short_description,long_description,alias,download_group,file_size_bytes,index_files,url,accession,pipeline_version
0,tsv,Taxonomic analysis,Summary of SILVA-SSU taxonomies,"Summary of SILVA-SSU taxonomic assignments, ac...",ERP120598_SILVA-SSU_study_summary.tsv,study_summary.v6.amplicon,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00010442,v6

## Downloading datasets

You can pass the `url` or `alias` if wanting to `.download()` or explore/read in via `.stream()` ONE download file/dataset. 

You can look at the file aliases as a list via `.aliases` attribute, also shown in "alias" column in `.downloads_df`

The urls are also in a column in `.downloads_df` but there are also helpers `.url_list` and `.url_dict` which provide {alias: url}

In [5]:
# lets try out one 
one_alias = ssu.aliases[0]
print(one_alias)

# downloading to a downloads folder
ssu.download(to_dir="downloads", alias=one_alias)

DEBUG:mgnipy.V2.datasets:Ensuring download directory exists: downloads
DEBUG:mgnipy.V2.datasets:Prepared file path for download: downloads/ERP120598_SILVA-SSU_study_summary.tsv
INFO:mgnipy.V2.datasets:File already exists and overwrite is False, skipping download: downloads/ERP120598_SILVA-SSU_study_summary.tsv

ERP120598_SILVA-SSU_study_summary.tsv

also the option to `download_all()`

In [6]:
ssu.download_all(to_dir="downloads")

DEBUG:mgnipy.V2.datasets:Initializing client once for all downloads
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11fb9dad0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x11fbd0320> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11f9e9e50>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Sun, 31 May 2026 21:59:58 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
DEBUG:mgnipy.V2.query_set:Built request URL for _downloads: https://www.ebi.ac.uk/
DEBUG:mgnipy.V2.datasets:MGnifier helper created: MGnifier instance for resource: _downloads
I.e., mgnipy.V2.core.MGnifier
----------------------------------------
Base URL: https://www.ebi.ac.uk/
Parameters: {'url': ''}
Example request URL: https://www.ebi.ac.uk/
Endpoint module: mgnipy.V2.custom_endpoint
Is list endpoint (returns paginated results): False
Cache directory: None

Overall Progress:   0%|          | 0/1 [00:00<?, ?it/s]DEBUG:mgnipy.V2.datasets:Ensuring download directory exists: downloads
DEBUG:mgnipy.V2.datasets:Prepared file path for download: downloads/ERP120598_SILVA-SSU_study_summary.tsv
INFO:mgnipy.V2.datasets:File already exists and overwrite is False, skipping download: downloads/ERP120598_SILVA-SSU_study_summary.tsv
Overall Progress: 100%|==========| 1/1 [00:00<00:00, 209.04it/s]

## Reading in a dataset `.stream()`

`.stream() `resolves a download alias or URL and returns the appropriate streaming handler for the file type. It supports returning either a full object (when `chunksize` is `None`) or an iterator of chunks when chunksize is provided.

In [7]:
df = ssu.stream(alias=one_alias, dataframe_engine="pandas")
df.head()

DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x10a43cd50>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x11fbd0f80> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11f36e510>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Sun, 31 May 2026 21:59:58 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP120598_SILVA-SSU_study_summary.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_SILVA-SSU_study_summary.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.

,taxonomy,ERR5382938,ERR5382939,ERR5382940,ERR5382941,ERR5382942,ERR5382943,ERR5382944,ERR5382945,ERR5382946,...,ERR5382991,ERR5382992,ERR5382993,ERR5382994,ERR5382995,ERR5382996,ERR5382997,ERR5382998,ERR5382999,ERR5383000
0,sk__Archaea;k__;p__Euryarchaeota;c__Methanobac...,2,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,2,0,0
1,sk__Archaea;k__;p__Euryarchaeota;c__Methanobac...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,sk__Bacteria,26,4,12,22,1,4,3,1,25,...,14,3,1,2,1,0,2,0,0,0
3,sk__Bacteria;k__;p__Acidobacteriota,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,sk__Bacteria;k__;p__Acidobacteriota;c__Holopha...,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## ✨ Bonus section: The `TaxaMGazine`

There are analysis type-specific mgazines, such as this TaxaMGazine

for example, we can also combine the taxonomic assignment results into one dataframe e.g. `.to_pandas()`, `.to_polars`, `.X()`

In [8]:
ssu.to_pandas()

,taxonomy,ERR5382938,ERR5382939,ERR5382940,ERR5382941,ERR5382942,ERR5382943,ERR5382944,ERR5382945,ERR5382946,...,ERR5382991,ERR5382992,ERR5382993,ERR5382994,ERR5382995,ERR5382996,ERR5382997,ERR5382998,ERR5382999,ERR5383000
0,sk__Archaea;k__;p__Euryarchaeota;c__Methanobac...,2,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,2,0,0
1,sk__Archaea;k__;p__Euryarchaeota;c__Methanobac...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,sk__Bacteria,26,4,12,22,1,4,3,1,25,...,14,3,1,2,1,0,2,0,0,0
3,sk__Bacteria;k__;p__Acidobacteriota,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,sk__Bacteria;k__;p__Acidobacteriota;c__Holopha...,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,sk__Bacteria;k__;p__Verrucomicrobiota;c__Verru...,0,0,0,0,8,0,0,0,0,...,5,0,0,0,0,0,0,0,0,0
671,sk__Bacteria;k__;p__Verrucomicrobiota;c__Verru...,2,0,0,0,31,0,0,0,0,...,10,2,0,0,0,0,0,0,0,0
672,sk__Bacteria;k__;p__Verrucomicrobiota;c__Verru...,32,1,1,1,8938,4,1,44,1,...,157,848,0,2,4,0,206,47,0,1
673,sk__Bacteria;k__;p__Verrucomicrobiota;c__Verru...,0,0,0,0,32,0,0,0,0,...,0,3,0,0,0,0,1,0,0,0
674,sk__Eukaryota;k__Viridiplantae;p__Streptophyta...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

There is also option to enrich with additional metadata! 

1)  From *already* retrieved `MGnifier` results you can set to `runs_results`, `samples_results`, `studies_results` etc, or

2) use `.enrich_runs()` etc or `.enrich_biosamples` which will make the get requests for the additional metadata

In [9]:
ssu.enrich_runs(limit=None)

DEBUG:mgnipy.V2.datasets.taxonomic:Starting enrichment of runs for short description Summary of SILVA-SSU taxonomies with limit None.
Enriching runs:   0%|          | 0/63 [00:00<?, ?it/s]INFO:mgnipy.V2.datasets.taxonomic:Enriching run ERR5382938 for short description Summary of SILVA-SSU taxonomies. Count: 0
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'run': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource run
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11fbfb190>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x11fc41910> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11f9fc550>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Sun, 31 May 2026 21:59:59 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for run
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for run
INFO:mgnipy.V2.query_set:Attempting to load cached results for run
DEBUG:mgnipy.V2.mixins:Computed cache key for run: 1691a608de2ee903ca7483ab659925c15a4f41f798c4597443cb4e461ab028fa
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/1691a608de2ee903ca7483ab659925c15a4f41f798c4597443cb4e461ab028fa
INFO:mgnipy.V2.mixins:Loading cached page from /Users/anglup/Library/Caches/mgnipy/1691a608de2ee903ca7483ab659925c15a4f41f798c4597443cb4e461ab028fa/mgnipy_page_1.json
INFO:mgnipy.V2.query_set:Loaded pages [1] from cache for resource run
DEBUG:mgnipy.V2.mixins:Computed cache key for run: 1691a608de2ee903ca7483ab659925c15a4f41f798c4597443cb4e461ab028fa
INFO:mgnipy.V2.mixins:Loading cache manifest from /Users/anglup/Library/Caches/mgnipy/1691a608de2ee903ca7483ab659925c15a4f41f798c4597443cb4e461ab028fa/mgnipy_manifest.json
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=0 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 1 items (max page 1): [1]
INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for run page 1: True
INFO:mgnipy.V2.query_executor:Page 1 already retrieved.
Enriching runs:   2%|▏         | 1/63 [00:00<00:16,  3.84it/s]INFO:mgnipy.V2.datasets.taxonomic:Enriching run ERR5382939 for short description Summary of SILVA-SSU taxonomies. Count: 1
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'run': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource run
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11fc2dad0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x11fc41be0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11f130050>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Sun, 31 May 2026 22:00:00 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for run
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for run
INFO:mgnipy.V2.query_set:Attempting to load cached results for run
DEBUG:mgnipy.V2.mixins:Computed cache key for run: dc2e76030b2039a208679b365647f84b8a54fef4de4201bc149a5d154c9c732a
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/dc2e76030b2039a208679b365647f84b8a54fef4de4201bc149a5d154c9c732a
INFO:mgnipy.V2.mixins:Loading cached page from /Users/anglup/Library/Caches/mgnipy/dc2e76030b2039a208679b365647f84b8a54fef4de4201bc149a5d154c9c732a/mgnipy_page_1.json
INFO:mgnipy.V2.query_set:Loaded pages [1] from cache for resource run
DEBUG:mgnipy.V2.mixins:Computed cache key for run: dc2e76030b2039a208679b365647f84b8a54fef4de4201bc149a5d154c9c732a
INFO:mgnipy.V2.mixins:Loading cache manifest from /Users/anglup/Library/Caches/mgnipy/dc2e76030b2039a208679b365647f84b8a54fef4de4201bc149a5d154c9c732a/mgnipy_manifest.json
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=0 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 1 items (max page 1): [1]
INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for run page 1: True
INFO:mgnipy.V2.query_executor:Page 1 already retrieved.
Enriching runs:   3%|▎         | 2/63 [00:00<00:14,  4.26it/s]INFO:mgnipy.V2.datasets.taxonomic:Enriching run ERR5382940 for short description Summary of SILVA-SSU taxonomies. Count: 2
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'run': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource run
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11fc5f590>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x11fc41eb0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x10a2ce2d0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Sun, 31 May 2026 22:00:00 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for run
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for run
INFO:mgnipy.V2.query_set:Attempting to load cached results for run
DEBUG:mgnipy.V2.mixins:Computed cache key for run: 297882fdbeab85d7a76f95e719c45f6facae75e9e5512190db305804a5e45515
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/297882fdbeab85d7a76f95e719c45f6facae75e9e5512190db305804a5e45515
INFO:mgnipy.V2.mixins:Loading cached page from /Users/anglup/Library/Caches/mgnipy/297882fdbeab85d7a76f95e719c45f6facae75e9e5512190db305804a5e45515/mgnipy_page_1.json
INFO:mgnipy.V2.query_set:Loaded pages [1] from cache for resource run
DEBUG:mgnipy.V2.mixins:Computed cache key for run: 297882fdbeab85d7a76f95e719c45f6facae75e9e5512190db305804a5e45515
INFO:mgnipy.V2.mixins:Loading cache manifest from /Users/anglup/Library/Caches/mgnipy/297882fdbeab85d7a76f95e719c45f6facae75e9e5512190db305804a5e45515/mgnipy_manifest.json
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=0 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 1 items (max page 1): [1]
INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for run page 1: True
INFO:mgnipy.V2.query_executor:Page 1 already retrieved.
Enriching runs:   5%|▍         | 3/63 [00:00<00:13,  4.39it/s]INFO:mgnipy.V2.datasets.taxonomic:Enriching run ERR5382941 for short description Summary of SILVA-SSU taxonomies. Count: 3
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'run': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource run
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11fc533d0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x11fc420f0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11fbdec50>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Sun, 31 May 2026 22:00:00 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for run
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for run
INFO:mgnipy.V2.query_set:Attempting to load cached results for run
DEBUG:mgnipy.V2.mixins:Computed cache key for run: 835cbbeadc4f59b7f4c23cd16e94a8e5b486e7361cd25ba9a833686781ecb9c0
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/835cbbeadc4f59b7f4c23cd16e94a8e5b486e7361cd25ba9a833686781ecb9c0
INFO:mgnipy.V2.mixins:Loading cached page from /Users/anglup/Library/Caches/mgnipy/835cbbeadc4f59b7f4c23cd16e94a8e5b486e7361cd25ba9a833686781ecb9c0/mgnipy_page_1.json
INFO:mgnipy.V2.query_set:Loaded pages [1] from cache for resource run
DEBUG:mgnipy.V2.mixins:Computed cache key for run: 835cbbeadc4f59b7f4c23cd16e94a8e5b486e7361cd25ba9a833686781ecb9c0
INFO:mgnipy.V2.mixins:Loading cache manifest from /Users/anglup/Library/Caches/mgnipy/835cbbeadc4f59b7f4c23cd16e94a8e5b486e7361cd25ba9a833686781ecb9c0/mgnipy_manifest.json
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=0 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 1 items (max page 1): [1]
INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for run page 1: True
INFO:mgnipy.V2.query_executor:Page 1 already retrieved.
Enriching runs:   6%|▋         | 4/63 [00:00<00:13,  4.42it/s]INFO:mgnipy.V2.datasets.taxonomic:Enriching run ERR5382942 for short description Summary of SILVA-SSU taxonomies. Count: 4
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'run': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource run
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11fc5fe90>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x11fc424e0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11fb9df10>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Vary', b'origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Sun, 31 May 2026 22:00:00 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'230')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for run
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for run
INFO:mgnipy.V2.query_set:Attempting to load cached results for run
DEBUG:mgnipy.V2.mixins:Computed cache key for run: d6a2ad97b48f95437cf2b915b3a24abca46ebd2af541f5e620fc70105c61dd31
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/anglup/Library/Caches/mgnipy/d6a2ad97b48f95437cf2b915b3a24abca46ebd2af541f5e620fc70105c61dd31
INFO:mgnipy.V2.mixins:Loading cached page from /Users/anglup/Library/Caches/mgnipy/d6a2ad97b48f95437cf2b915b3a24abca46ebd2af541f5e620fc70105c61dd31/mgnipy_page_1.json
INFO:mgnipy.V2.query_set:Loaded pages [1] from cache for resource run
DEBUG:mgnipy.V2.mixins:Computed cache key for run: d6a2ad97b48f95437cf2b915b3a24abca46ebd2af541f5e620fc70105c61dd31

In [10]:
ssu.to_anndata()

DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.mixins:Converting results to pandas DataFrame; expand_nested_dicts=True
/Users/anglup/.pyenv/versions/3.11.7/lib/python3.11/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

AnnData object with n_obs × n_vars = 675 × 63
    obs: 'Superkingdom', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'
    var: 'experiment_type', 'instrument_model', 'instrument_platform', 'sample_accession', 'study_accession', 'sample__accession', 'sample__ena_accessions', 'sample__sample_title', 'sample__biome', 'sample__updated_at', 'study__accession', 'study__ena_accessions', 'study__title', 'study__updated_at', 'study__biome.biome_name', 'study__biome.lineage'