# `MGazine` of MGnify data

```{margin}
After clicking the "Activate Notebook" button you can run the cells in this browser. Alternatively, you can also click on the 🚀 to launch in colab or binder.
```
<button title="Make live" style="display:inline-flex;align-items:center;gap:0.4rem;padding:0.5rem 1rem;border:0;border-radius:20px;background:linear-gradient(135deg,#0f766e,#14b8a6);color:white;cursor:pointer;font-size:1rem;" class="thebe-button" onclick="initThebeSBT()">Activate Notebook</button>

---

In [ ]:
# uncomment below if colab
#!pip install mgnipy


## What is a `mgnipy.MGazine`?

Study and Analysis details include **'downloads'** fields which contain information such as types, short descriptions, urls etc about the datasets outputed from MGnify pipelines.

`mgnipy.MGazine` as well as more analysis-specific classes such as `TaxaMGazine` and `DWCTaxaMGazine` can be used to download the datasets onto disk or read them into our notebooks.

For downloading, MGazine supports the downloading of all filetypes. For streaming (via `mixins.StreamMixin`), the supported filetypes are:

- TSV/CSV — stream_pandas (pandas) or stream_polars (polars) (handles gzipped TSV/CSV).
- TXT — stream_txt (full text or line-chunks).
- HTML — stream_html (opens in browser).
- FASTA / GFF / BIOM — stream_fasta, stream_gff, stream_biom (scikit-bio generators).
- JSONL / NDJSON — stream_jsonl (pandas or polars).
- Tree / Newick — stream_tree (scikit-bio).
- Other — JSON files under other are streamed via stream_json; binary/unsupported types should be downloaded.

---

## Accessing a MGazine from a `MGnifier` search

Recalling,
1. Start up a `mgnipy.MGnipy` client with your desired configuration
2. Search in MGnify resources using a `mgnipy.MGnifier` glass
3. **Receive a `mgnipy.MGazine` of MGnify datasets**

For step 2 specifically the following mgnifiers can output a mgazine:
- `proxies.Study`
- `proxies.Analysis`
- `proxies.Studies`
- `proxies.Analyses`

In this demonstration we will get the `MGazine` of a single study, but this would be the same for a multi-study collection of `proxies.Studies`

In [2]:
from mgnipy import MGnipy

# 1. init with default config
MG = MGnipy(cache_dir=None)

# 2. search up a study/analysis detail or a list of studies/analyses and get their details
study = MG.study("MGYS00010442")
with MG:
    study.get()

DEBUG:matplotlib:matplotlib data path: /Users/anglup/GitHub/mgnipy/.venv/lib/python3.11/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/Users/anglup/.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is darwin
DEBUG:matplotlib:CACHEDIR=/Users/anglup/.matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /Users/anglup/.matplotlib/fontlist-v390.json
DEBUG:pydot:pydot initializing
DEBUG:pydot:pydot 4.0.1
DEBUG:pydot.core:pydot core module initializing
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:numcodecs:Registering codec 'zlib'
DEBUG:numcodecs:Registering codec 'gzip'
DEBUG:numcodecs:Registering codec 'bz2'
DEBUG:numcodecs:Registering codec 'lzma'
DEBUG:numcodecs:Registering codec 'blosc'
DEBUG:numcodecs:Registering codec 'zstd'
DEBUG:numcodecs:Registering codec 'lz4'
DEBUG:numcodecs:Registering codec 'astype'
DEBUG:numcodecs:Registering codec 'delta'
DEBUG:numcodecs:Registering codec 'quantize'
DEBUG:numcodecs:Registering codec 'fixedscaleoffset'
DEBUG:numcodecs:Registering codec 'packbits'
DEBUG:numcodecs:Registering codec 'categorize'
DEBUG:numcodecs:Registering codec 'pickle'
DEBUG:numcodecs:Registering codec 'base64'
DEBUG:numcodecs:Registering codec 'shuffle'
DEBUG:numcodecs:Registering codec 'bitround'
DEBUG:numcodecs:Registering codec 'crc32'
DEBUG:numcodecs:Registering codec 'adler32'
DEBUG:numcodecs:Registering codec 'jenkins_lookup3'
DEBUG:numcodecs:Registering codec 'json2'
DEBUG:numcodecs:Registering codec 'vlen-utf8'
DEBUG:numcodecs:Registering codec 'vlen-bytes'
DEBUG:numcodecs:Registering codec 'vlen-array'
DEBUG:numcodecs:Registering codec 'fletcher32'
DEBUG:numcodecs:Registering codec 'crc32c'
DEBUG:mgnipy._models.config:Cached auth token will be stored in: /Users/anglup/GitHub/mgnipy/docs/notebooks/fundamentals
INFO:mgnipy._models.config:Username/password not provided. Proceeding without authentication.
DEBUG:mgnipy._models.config:No token, username, password. Exiting resolve_auth_token()
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'study': 'accession'
DEBUG:mgnipy.V2.mgnifier.query_set:Initiated QuerySet. Resource initially: study. Module: <module 'mgnipy.emgapi_v2_client.api.studies.get_mgnify_study' from '/Users/anglup/GitHub/mgnipy/mgnipy/emgapi_v2_client/api/studies/get_mgnify_study.py'>.
DEBUG:mgnipy.V2.mgnifier.describe:Attempting to retrieve identifier parameter key for resource 'studies'
INFO:mgnipy.V2.mgnifier:client from mgnipy:False
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'study': 'accession'
DEBUG:mgnipy.V2.mgnifier.query_set:Initiated QuerySet. Resource initially: study. Module: <module 'mgnipy.emgapi_v2_client.api.studies.get_mgnify_study' from '/Users/anglup/GitHub/mgnipy/mgnipy/emgapi_v2_client/api/studies/get_mgnify_study.py'>.
DEBUG:mgnipy.V2.mgnifier.describe:Attempting to retrieve identifier parameter key for resource 'studies'
INFO:mgnipy.V2.mgnifier:client from mgnipy:False
INFO:mgnipy.V2.mgnifier.query_set:Reassigning endpoint module: <module 'mgnipy.emgapi_v2_client.api.studies.get_mgnify_study' from '/Users/anglup/GitHub/mgnipy/mgnipy/emgapi_v2_client/api/studies/get_mgnify_study.py'>. Resetting count, num_requests, and results.
DEBUG:mgnipy.V2.mixins:Cache disabled: Skipping cache load for study.
DEBUG:mgnipy.V2.mgnifier.query_set:`.count` set to None
DEBUG:mgnipy.V2.mgnifier.query_set:`.num_requests` set to None
DEBUG:mgnipy.V2.mgnifier.query_set:`.count` set to 1
DEBUG:mgnipy.V2.mgnifier.query_set:`.num_requests` set to 1
DEBUG:mgnipy.V2.mgnifier.query_executor:Computed count and num_requests: 1, 1
DEBUG:mgnipy.V2.mgnifier.query_set:Building query plan for study
DEBUG:mgnipy.V2.mgnifier.query_set:Built single-query plan for study
DEBUG:mgnipy.V2.mgnifier:No pages loaded yet, initialized iterator with pages: [1]
DEBUG:mgnipy.V2.mgnifier:Advancing to request num 1
DEBUG:mgnipy.V2.mixins:Cache already loaded; skipping load attempt. Pages loaded: []Manifest: {}
DEBUG:mgnipy.V2.mgnifier.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.mgnifier:Fetching page 1
DEBUG:mgnipy.V2.mgnifier.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.mgnifier.query_set:Result presence check: False
INFO:mgnipy.V2.mgnifier.query_executor:Page 1 not in results
DEBUG:mgnipy.V2.mgnifier.query_set:Building query plan for study
DEBUG:mgnipy.V2.mgnifier.query_set:Built single-query plan for study
DEBUG:mgnipy.V2.mgnifier.query_set:Building query plan for study
DEBUG:mgnipy.V2.mgnifier.query_set:Built single-query plan for study
INFO:mgnipy.V2.mgnifier.query_executor:Fetching request num 1 with params: {'accession': 'MGYS00010442'}
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11e44d850>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x11ed0d5b0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11db61210>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Vary', b'Cookie, origin'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 21 Aug 2026 10:09:37 GMT'), (b'Cross-Origin-Opener-Policy', b'same-origin'), (b'X-Content-Type-Options', b'nosniff'), (b'Connection', b'keep-alive'), (b'X-Frame-Options', b'DENY'), (b'Referrer-Policy', b'same-origin'), (b'Content-Length', b'4612')])
INFO:httpx:HTTP Request: GET https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442 "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
INFO:mgnipy.V2.mgnifier.query_executor:Response status code: 200
DEBUG:root:Response validation for MGnify record MGYS00010442 returned status code 200. Valid: True
DEBUG:mgnipy.V2.mgnifier.query_executor:Endpoint is not a list endpoint, returning full response as items.
DEBUG:mgnipy.V2.mixins:Cache disabled: Skipping cache write for page 1
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:mgnipy.V2.mixins:Closing client: None

MGazines for a given study or analysis detail can be accessed via their `.datasets` attributes

In [3]:
# access the study's mgazine
mz = study.datasets

# check it out
print(mz)

DEBUG:mgnipy.V2.mixins:Cache already loaded; skipping load attempt. Pages loaded: []Manifest: {}
DEBUG:mgnipy.V2.mgnifier.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.mixins:Cache already loaded; skipping load attempt. Pages loaded: []Manifest: {}
DEBUG:mgnipy.V2.mgnifier.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.mgnifier.metadata:Converting results to pandas DataFrame; expand_nested_dicts=False
DEBUG:mgnipy.V2.mgnifier.metadata:Returning pandas DataFrame without nested expansion
DEBUG:mgnipy.V2.proxies:Metadata columns: ['accession', 'ena_accessions', 'title', 'biome', 'updated_at', 'metadata', 'downloads', 'first_accession']
DEBUG:mgnipy.V2.proxies:downloads columns: Index(['file_type', 'download_type', 'short_description', 'long_description',
       'alias', 'download_group', 'file_size_bytes', 'index_files', 'url'],
      dtype='object')
DEBUG:mgnipy.V2.proxies:No 'accession' field in downloads. Attempting to add identifier info with id_param_key 'accession' and identifier 'MGYS00010442'.
DEBUG:mgnipy.V2.mixins:Cache already loaded; skipping load attempt. Pages loaded: []Manifest: {}
DEBUG:mgnipy.V2.mgnifier.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.mgnifier.metadata:dict_keys(['accession', 'ena_accessions', 'title', 'biome', 'updated_at', 'metadata', 'downloads', 'first_accession'])
DEBUG:mgnipy.V2.proxies:No 'pipeline_version' field in downloads. Attempting to add pipeline version info.
DEBUG:mgnipy.V2.mixins:Cache already loaded; skipping load attempt. Pages loaded: []Manifest: {}
DEBUG:mgnipy.V2.mgnifier.query_executor:Using cached count and num_requests vals: 1, 1

MGazine containing:
- MGnify pipeline versions: ['v6']
- Number of downloads: 8
- Short descriptions: ['DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -PR2 as ref DB',
 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -SILVA as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using PR2 as ref DB',
 'DwC-Ready summary of closed-ref taxonomies using SILVA-SSU as ref DB',
 'Summary of DADA2-PR2 taxonomies',
 'Summary of DADA2-SILVA taxonomies',
 'Summary of PR2 taxonomies',
 'Summary of SILVA-SSU taxonomies']
- Nonempty metadata sets: .mgnify_studies

As we see above, the __str__ representaiton of mgazine gives us a peak into the pipeline versions within, number of downloads and the short_description categories

## Navigating and filtering a `MGazine`

Built in to mgazine, you can filter the mgazine to a specific pipeline versions and short_descriptions which will return a mgazine again but filtered or a curated mgazine with additional functionalities if available ✨.

You can filter by passing them as you would an index into square brackets i..e, __getitem__

In [4]:
# above we saw that v6 is the only one so this will return the same basically
ssu = mz["v6"]["Summary of SILVA-SSU taxonomies"]

print(ssu)
# also checking out downloads detials as df
ssu.downloads_df()

MGazine containing:
- MGnify pipeline versions: ['v6']
- Number of downloads: 1
- Short descriptions: ['Summary of SILVA-SSU taxonomies']
- Nonempty metadata sets: .mgnify_studies

,file_type,download_type,short_description,long_description,alias,download_group,file_size_bytes,index_files,url,accession,pipeline_version
0,tsv,Taxonomic analysis,Summary of SILVA-SSU taxonomies,"Summary of SILVA-SSU taxonomic assignments, ac...",ERP120598_SILVA-SSU_study_summary.tsv,study_summary.v6.amplicon,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00010442,v6

## Downloading datasets

You can pass the `url` or `alias` if wanting to `.download()` or explore/read in via `.stream()` ONE download file/dataset.

You can look at the file aliases as a list via `.aliases` attribute, also shown in "alias" column in `.downloads_df()`

The urls are also in a column in `.downloads_df()` but there are also helpers `.url_list` and `.url_dict` which provide {alias: url}

In [5]:
# lets try out one
one_alias = ssu.aliases[0]
print(one_alias)

# downloading to a downloads folder
ssu.download(to_dir="downloads", alias=one_alias)

DEBUG:mgnipy.V2.datasets:Ensuring download directory exists: downloads
DEBUG:mgnipy.V2.datasets:Prepared file path for download: downloads/ERP120598_SILVA-SSU_study_summary.tsv
INFO:mgnipy.V2.datasets:File already exists and overwrite is False, skipping download: downloads/ERP120598_SILVA-SSU_study_summary.tsv

ERP120598_SILVA-SSU_study_summary.tsv

also the option to `download_all()`

In [6]:
ssu.download_all(to_dir="downloads")

DEBUG:mgnipy.V2.datasets:Initializing client once for all downloads
Overall Progress:   0%|          | 0/1 [00:00<?, ?it/s]DEBUG:mgnipy.V2.datasets:Ensuring download directory exists: downloads
DEBUG:mgnipy.V2.datasets:Prepared file path for download: downloads/ERP120598_SILVA-SSU_study_summary.tsv
INFO:mgnipy.V2.datasets:File already exists and overwrite is False, skipping download: downloads/ERP120598_SILVA-SSU_study_summary.tsv
Overall Progress: 100%|==========| 1/1 [00:00<00:00, 172.51it/s]

## Reading in a dataset `.stream()`

`.stream() `resolves a download alias or URL and returns the appropriate streaming handler for the file type. It supports returning either a full object (when `chunksize` is `None`) or an iterator of chunks when chunksize is provided.

In [7]:
df = ssu.stream(alias=one_alias, df_engine="pandas")
df.head()

INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP120598_SILVA-SSU_study_summary.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_SILVA-SSU_study_summary.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.

,taxonomy,ERR5382938,ERR5382939,ERR5382940,ERR5382941,ERR5382942,ERR5382943,ERR5382944,ERR5382945,ERR5382946,...,ERR5382991,ERR5382992,ERR5382993,ERR5382994,ERR5382995,ERR5382996,ERR5382997,ERR5382998,ERR5382999,ERR5383000
0,sk__Archaea;k__;p__Euryarchaeota;c__Methanobac...,2,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,2,0,0
1,sk__Archaea;k__;p__Euryarchaeota;c__Methanobac...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,sk__Bacteria,26,4,12,22,1,4,3,1,25,...,14,3,1,2,1,0,2,0,0,0
3,sk__Bacteria;k__;p__Acidobacteriota,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,sk__Bacteria;k__;p__Acidobacteriota;c__Holopha...,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## ✨ Bonus section: The `TaxaMGazine`

There are analysis type-specific mgazines, such as this TaxaMGazine

for example, we can also combine the taxonomic assignment results into one dataframe e.g. `.to_pandas()`, `.to_polars`, `.to_anndata()`

In [8]:
taxo = ssu.taxonomic

taxo.load()

taxo.to_pandas().head()

INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP120598_SILVA-SSU_study_summary.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_SILVA-SSU_study_summary.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.

TaxaMGazine containing:
- MGnify pipeline versions: ['v6']
- Number of downloads: 1
- Short descriptions: ['Summary of SILVA-SSU taxonomies']
- Nonempty metadata sets: .mgnify_studies
-----------------------
Next steps: Use `.load()` to initialize.

,taxonomy,ERR5382938,ERR5382939,ERR5382940,ERR5382941,ERR5382942,ERR5382943,ERR5382944,ERR5382945,ERR5382946,...,ERR5382991,ERR5382992,ERR5382993,ERR5382994,ERR5382995,ERR5382996,ERR5382997,ERR5382998,ERR5382999,ERR5383000
0,sk__Archaea;k__;p__Euryarchaeota;c__Methanobac...,2,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,2,0,0
1,sk__Archaea;k__;p__Euryarchaeota;c__Methanobac...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,sk__Bacteria,26,4,12,22,1,4,3,1,25,...,14,3,1,2,1,0,2,0,0,0
3,sk__Bacteria;k__;p__Acidobacteriota,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,sk__Bacteria;k__;p__Acidobacteriota;c__Holopha...,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

also annotated dataframes

In [9]:
taxo.to_anndata()

WARNING:mgnipy.V2.datasets.annotate:No non-empty metadata sets available. Returning empty dataframe.
WARNING:mgnipy.V2.datasets.annotate:No non-empty metadata sets available. Returning empty dataframe.

AnnData object with n_obs × n_vars = 63 × 675
    var: 'Superkingdom', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'

tidy up

In [10]:
MG.clear_subcaches()

WARNING:mgnipy.mgnipy:Cache directory is not set: None. Cannot clear cache. Please set cache_dir in MGnipyConfig.