# Downloading MGnify Study data

The MGnify API provides access to study and analyses datasets for download. On this page we demonstrate how to:

-  **Discover** what datasets are available
-  **Download** the datasets
-  **Stream** or read in the datasets

```{margin}
After clicking the "Activate Notebook" button you can run the cells in this browser. Alternatively, you can also click on the 🚀 to launch in colab or binder. 
```
<button title="Make live" style="display:inline-flex;align-items:center;gap:0.4rem;padding:0.5rem 1rem;border:0;border-radius:20px;background:linear-gradient(135deg,#0f766e,#14b8a6);color:white;cursor:pointer;font-size:1rem;" class="thebe-button" onclick="initThebeSBT()">Activate Notebook</button>

---

In [1]:
# uncomment below if colab
#!pip install mgnipy
#!pip install asyncio

In [2]:
import logging
logging.basicConfig(level=logging.DEBUG)



## 🎯 The Goal: Retrieve taxonomic datasets of tomato rhizosphere studies

Let's request tomato rhizosphere datasets and metadata from MGnify API.

Recall the typical workflow (from [What is MGni.Py?](TODO)):

1. Start up a `mgnipy.MGnipy` client with your desired configuration

2. Search in MGnify resources using a MGnifier glass

3. Receive a MGazine of MGnify datasets

which we will follow in this notebook

## 1. and 2. `mgnipy.MGnipy().studies` 

In the below cell we take care of
- ✅ 1. set up of our MGnipy instance and
- ✅ 2.a) preparing search for a list of tomato studies using the studies-specific `MGnifier` aka `mgnipy.V2.proxies.studies.Studies`
- ✅ 2.b) populating list of studies
- ✅ 2.c) retrieving details (i.e., ALL `StudyDetail`s) for every study in the list


````{margin} What is happening behind the scenes of:
**2.b)** .bulk_fetch()
```python
for _ in range(
    tomato_studies.num_requests
):
    tomato_studies.get()
```

**2.c)** .enrich_details()
```python
for _ in range(
    len(tomato_studies)
):
    tomato_studies.get_detail()
```
````

In [3]:
from mgnipy import MGnipy

# 1. init with default config
MG = MGnipy()

# 2.a) setup studies mgnifier (build queries)
tomato_studies = MG.studies(
    biome_lineage="root:Host-associated:Plants:Rhizosphere", 
    search="tomato"
)

# 2.b) execute the list query (get the study list)
tomato_studies.bulk_fetch()

# 2.c) get the study list (execute all detail queries)
tomato_studies.enrich_details()

# take a look at the studies details results as a pandas df
tomato_studies.to_df(expand_nested_dicts=True)

DEBUG:pydot:pydot initializing
DEBUG:pydot:pydot 4.0.1
DEBUG:pydot.core:pydot core module initializing
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:numcodecs:Registering codec 'zlib'
DEBUG:numcodecs:Registering codec 'gzip'
DEBUG:numcodecs:Registering codec 'bz2'
DEBUG:numcodecs:Registering codec 'lzma'
DEBUG:numcodecs:Registering codec 'blosc'
DEBUG:numcodecs:Registering codec 'zstd'
DEBUG:numcodecs:Registering codec 'lz4'
DEBUG:numcodecs:Registering codec 'astype'
DEBUG:numcodecs:Registering codec 'delta'
DEBUG:numcodecs:Registering codec 'quantize'
DEBUG:numcodecs:Registering codec 'fixedscaleoffset'
DEBUG:numcodecs:Registering codec 'packbits'
DEBUG:numcodecs:Registering codec 'categorize'
DEBUG:numcodecs:Registering codec 'pickle'
DEBUG:numcodecs:Registering codec 'base64'
DEBUG:numcodecs:Registering codec 'shuffle'
DEBUG:numcodecs:Registering codec 'bitround'
DEBUG:numcodecs:Registering codec 'crc32'
DEBUG:numcodecs:Registering codec 'adler32'
DEBUG:numcodecs:Registering codec 'jenkins_lookup3'
DEBUG:numcodecs:Registering codec 'json2'
DEBUG:numcodecs:Registering codec 'vlen-utf8'
DEBUG:numcodecs:Registering codec 'vlen-bytes'
DEBUG:numcodecs:Registering codec 'vlen-array'
DEBUG:numcodecs:Registering codec 'fletcher32'
DEBUG:numcodecs:Registering codec 'crc32c'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource studies
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120430490>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120a6a060> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120430dd0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:12 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for studies
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for studies
INFO:mgnipy.V2.query_set:Attempting to load cached results for studies
DEBUG:mgnipy.V2.mixins:Computed cache key for studies: 548649ce566f131cec498682d701e6335235a8f634546f3cadae6892147a89b6
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/phanthanourak/Library/Caches/mgnipy/548649ce566f131cec498682d701e6335235a8f634546f3cadae6892147a89b6
INFO:mgnipy.V2.mixins:No cache directory found at /Users/phanthanourak/Library/Caches/mgnipy/548649ce566f131cec498682d701e6335235a8f634546f3cadae6892147a89b6
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource studies
DEBUG:mgnipy.V2.mixins:Computed cache key for studies: 548649ce566f131cec498682d701e6335235a8f634546f3cadae6892147a89b6
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource studies
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120ae8290>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120a6a600> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x12045da90>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:12 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for studies
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for studies
INFO:mgnipy.V2.query_set:Attempting to load cached results for studies
DEBUG:mgnipy.V2.mixins:Computed cache key for studies: cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/phanthanourak/Library/Caches/mgnipy/cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a
INFO:mgnipy.V2.mixins:Loading cached page from /Users/phanthanourak/Library/Caches/mgnipy/cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a/mgnipy_page_1.json
INFO:mgnipy.V2.query_set:Loaded pages [1] from cache for resource studies
DEBUG:mgnipy.V2.mixins:Computed cache key for studies: cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a
INFO:mgnipy.V2.mixins:Loading cache manifest from /Users/phanthanourak/Library/Caches/mgnipy/cb43e9497742a3c5617cc4fd4fb264f6d858d41d4dcc8af1dc5f6b95dca17d3a/mgnipy_manifest.json
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=1 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 17 items (max page 1): [1]
Retrieving pages:   0%|          | 0/1 [00:00<?, ?it/s]INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 17, 1
DEBUG:mgnipy.V2.query_set:Result presence check for studies page 1: True
INFO:mgnipy.V2.query_executor:Page 1 already retrieved.
Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 759.29it/s]
DEBUG:mgnipy.V2.proxies:Starting enrichment of details with limit 200.
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Flattening paginated results for studies
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Flattening paginated results for studies
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Flattening paginated results for studies
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
Enriching details:   0%|          | 0/17 [00:00<?, ?it/s]INFO:mgnipy.V2.proxies:Enriching detail MGYS00010296. Count: 0
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'study': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource study
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120aec7d0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120a6b5c0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120953e90>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:12 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for study
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for study
INFO:mgnipy.V2.query_set:Attempting to load cached results for study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 543ed63baf46ceb583dd3af1ab114e09d4fd4b4f0ba6d18455b6c5d6d7ddec29
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/phanthanourak/Library/Caches/mgnipy/543ed63baf46ceb583dd3af1ab114e09d4fd4b4f0ba6d18455b6c5d6d7ddec29
INFO:mgnipy.V2.mixins:No cache directory found at /Users/phanthanourak/Library/Caches/mgnipy/543ed63baf46ceb583dd3af1ab114e09d4fd4b4f0ba6d18455b6c5d6d7ddec29
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 543ed63baf46ceb583dd3af1ab114e09d4fd4b4f0ba6d18455b6c5d6d7ddec29
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_set:Built request URL for study: https://www.ebi.ac.uk/metagenomics/api/v2/studies/None
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 543ed63baf46ceb583dd3af1ab114e09d4fd4b4f0ba6d18455b6c5d6d7ddec29
DEBUG:mgnipy.V2.proxies:Got detail class MGnifier instance for resource: study
I.e., mgnipy.V2.proxies.studies.StudyDetail
----------------------------------------
Base URL: https://www.ebi.ac.uk/
Parameters: {'accession': None}
Example request URL: https://www.ebi.ac.uk/metagenomics/api/v2/studies/None
Endpoint module: mgnipy.emgapi_v2_client.api.studies.get_mgnify_study
Is list endpoint (returns paginated results): False
Cache directory: /Users/phanthanourak/Library/Caches/mgnipy/543ed63baf46ceb583dd3af1ab114e09d4fd4b4f0ba6d18455b6c5d6d7ddec29
 for child resource <SupportedEndpoints.STUDY: 'study'>
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Flattening paginated results for studies
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Flattening paginated results for studies
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.query_set:Flattening paginated results for studies
DEBUG:mgnipy.V2.query_set:Returning results for studies with pages: [1]
DEBUG:mgnipy.V2.proxies:Resolved id param for detail: {'accession': 'MGYS00010296'}
INFO:mgnipy.V2.query_set:Filtering QuerySet for study with keys: ['accession']
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'study': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource study
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x12095c7d0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120a6bd10> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x1204263d0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:13 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for study
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for study
INFO:mgnipy.V2.query_set:Attempting to load cached results for study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/phanthanourak/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
INFO:mgnipy.V2.mixins:Loading cached page from /Users/phanthanourak/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848/mgnipy_page_1.json
INFO:mgnipy.V2.query_set:Loaded pages [1] from cache for resource study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
INFO:mgnipy.V2.mixins:Loading cache manifest from /Users/phanthanourak/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848/mgnipy_manifest.json
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.query_set:Reassigning endpoint module for study
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for study
INFO:mgnipy.V2.query_set:Attempting to load cached results for study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/phanthanourak/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
INFO:mgnipy.V2.mixins:Loading cached page from /Users/phanthanourak/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848/mgnipy_page_1.json
INFO:mgnipy.V2.query_set:Loaded pages [1] from cache for resource study
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
INFO:mgnipy.V2.mixins:Loading cache manifest from /Users/phanthanourak/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848/mgnipy_manifest.json
DEBUG:mgnipy.V2.query_set:Built request URL for study: https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010296
DEBUG:mgnipy.V2.mixins:Computed cache key for study: 4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
DEBUG:mgnipy.V2.proxies:Initialized detail proxy MGnifier instance for resource: study
I.e., mgnipy.V2.proxies.studies.StudyDetail
----------------------------------------
Base URL: https://www.ebi.ac.uk/
Parameters: {'accession': 'MGYS00010296'}
Example request URL: https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010296
Endpoint module: mgnipy.emgapi_v2_client.api.studies.get_mgnify_study
Is list endpoint (returns paginated results): False
Cache directory: /Users/phanthanourak/Library/Caches/mgnipy/4c9cf6080290567edaf9134e27ee8ca914dde6dd313b2affa2af5b8ff1ec3848
 with params {'accession': 'MGYS00010296'}
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for study page 1: True
INFO:mgnipy.V2.query_executor:Page 1 already retrieved.
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.mixins:Converting results to pandas DataFrame; expand_nested_dicts=False
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning record iterator for study
DEBUG:mgnipy.V2.query_set:Flattening paginated results for study
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.proxies:Updating download info with identifier 'MGYS00010296' to id_param_key 'accession'
DEBUG:mgnipy.V2.mixins:Converting results to pandas DataFrame; expand_nested_dicts=False
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning record iterator for study
DEBUG:mgnipy.V2.query_set:Flattening paginated results for study
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.mixins:Converting results to pandas DataFrame; expand_nested_dicts=False
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
DEBUG:mgnipy.V2.query_set:Returning record iterator for study
DEBUG:mgnipy.V2.query_set:Flattening paginated results for study
DEBUG:mgnipy.V2.query_set:Returning results for study with pages: [1]
Enriching details:   6%|▌         | 1/17 [00:00<00:02,  5.66it/s]INFO:mgnipy.V2.proxies:Enriching detail MGYS00010297. Count: 1
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'study': 'accession'

,accession,ena_accessions,title,updated_at,biome__biome_name,biome__lineage
0,MGYS00010296,"[ERP166137, PRJEB82448]",Microbiome-mediated tolerance of wild tomato t...,2026-05-28T15:46:48.615000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
1,MGYS00010297,"[SRP333165, PRJNA755742]",Tomato rhizosphere microbiome in the pot exper...,2026-05-28T15:46:48.649000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
2,MGYS00006231,"[ERP139927, PRJEB55060]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:46:58.486000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
3,MGYS00006204,"[ERP140102, PRJEB55219]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:47:01.715000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
4,MGYS00006205,"[ERP140107, PRJEB55224]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:47:01.734000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
5,MGYS00006208,"[ERP140115, PRJEB55232]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:47:01.747000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
6,MGYS00006230,"[ERP139923, PRJEB55057]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:47:01.755000+00:00,Rhizosphere,root:Host-associated:Plants:Rhizosphere
7,MGYS00010257,"[SRP456588, PRJNA1004080]",Combined effect of microplastics and fungicide...,2026-05-28T15:46:48.538000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
8,MGYS00010264,[PRJEB91717],Metagenome assembly of PRJNA1127303 data set (...,2026-05-28T15:46:48.743000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
9,MGYS00010251,"[SRP338795, PRJNA766489]",Culture-independent analysis of rhizosphere mi...,2026-05-28T15:46:48.756000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
10,MGYS00010245,"[PRJEB82447, ERP166136]",Unveiling diversity and adaptations of the wil...,2026-05-28T15:46:48.558000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
11,MGYS00010324,[PRJEB95772],Metagenome assembly of PRJNA777724 data set (T...,2026-05-28T15:46:48.576000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
12,MGYS00010258,"[SRP517058, PRJNA1127303]",Metagenomic data of rhizosphere soil during to...,2026-05-28T15:46:48.578000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
13,MGYS00010298,"[PRJNA777724, SRP344777]",Tomato heritable microbiome,2026-05-28T15:46:48.670000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
14,MGYS00010262,[PRJEB91684],Metagenome assembly of PRJNA1004080 data set (...,2026-05-28T15:46:48.688000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
15,MGYS00010250,"[PRJNA755741, SRP333163]",Tomato rhizosphere microbiome in the belowgrou...,2026-05-28T15:46:48.730000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil
16,MGYS00010253,"[PRJNA789467, SRP351203]",Disentangling the genetic basis of rhizosphere...,2026-05-28T15:46:48.818000+00:00,Soil,root:Host-associated:Plants:Rhizosphere:Soil

## 3. Accessing the `MGazine` of datasets

- study details have a `mgnipy.MGazine` which allow us to download and interact with study-level datasets outputed from MGnify. 

- We can use `mgnipy.MGazine` to download the datasets onto disk or read them into our notebook. 

- To access the study's mgazine use `.datasets` 

- the __str__ representaiton of mgazine gives us a peak into the pipeline versions within, number of downloads and the short_description categories

In [4]:
# access study mgazine
MZ = tomato_studies.datasets

# print for more info 
print(MZ)

# also can view more as df 
MZ.downloads_df

MGazine containing:
- MGnify pipeline versions: ['v5']
- Number of downloads: 35
- Short descriptions: ['Complete GO annotation',
 'GO slim annotation',
 'InterPro matches',
 'Phylum level taxonomies LSU',
 'Phylum level taxonomies SSU',
 'Taxonomic assignments LSU',
 'Taxonomic assignments SSU']

,file_type,download_type,short_description,long_description,alias,download_group,file_size_bytes,index_files,url,accession,pipeline_version
0,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP139927_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
1,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP139927_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
2,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP139927_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
3,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP139927_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
4,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP139927_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
5,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP139927_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
6,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP139927_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
7,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP140102_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
8,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140102_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
9,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP140102_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
10,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP140102_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
11,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP140102_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
12,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP140102_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
13,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP140102_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
14,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP140107_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
15,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140107_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
16,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP140107_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
17,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP140107_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
18,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP140107_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
19,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP140107_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
20,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP140107_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
21,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP140115_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
22,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140115_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
23,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP140115_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
24,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP140115_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
25,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP140115_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
26,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP140115_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
27,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP140115_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
28,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP139923_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
29,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP139923_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
30,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP139923_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
31,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP139923_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
32,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP139923_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
33,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP139923_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
34,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP139923_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5

### Navigating and filtering a `MGazine`

Built in to mgazine, you can filter the mgazine to a specific pipeline versions and short_descriptions which will return a mgazine again but filtered or a curated mgazine with additional functionalities if available ✨.

FOr accessing a specific pipeline version you can call the veresion as an attribute:

In [5]:
# above we saw that v5 is the only one so this will return the same basically
v5_data = MZ.v5

# if we print again we will see the same info
print(v5_data)

INFO:mgnipy.V2.datasets:Setting up mgazine only for datasets of pipeline version v5 via attribute access.

MGazine containing:
- MGnify pipeline versions: ['v5']
- Number of downloads: 35
- Short descriptions: ['Complete GO annotation',
 'GO slim annotation',
 'InterPro matches',
 'Phylum level taxonomies LSU',
 'Phylum level taxonomies SSU',
 'Taxonomic assignments LSU',
 'Taxonomic assignments SSU']

You can filter by short descriptioins by passing them as you would an index into square brackets i..e, __getitem__

In [6]:
# we want the taxonomic assignments
ssu = v5_data['Taxonomic assignments SSU']

# checking out what it is 
print(type(ssu))
print(ssu)

# downloads_df again 
ssu.downloads_df

INFO:mgnipy.V2.datasets:Download type for Taxonomic assignments SSU: taxonomic analysis
DEBUG:mgnipy.V2.datasets:getting taxonomic datasets of short description Taxonomic assignments SSU via item access.
INFO:mgnipy.V2.datasets.taxonomic:TaxaMGazine initialized for short description: Taxonomic assignments SSU
INFO:mgnipy.V2.datasets.taxonomic:TaxaMGazine long to short rank mapping set: {'Superkingdom': 'sk', 'Kingdom': 'k', 'Phylum': 'p', 'Class': 'c', 'Order': 'o', 'Family': 'f', 'Genus': 'g', 'Species': 's'}
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120af8f90>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120b7e8d0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x11d7e41d0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:16 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP139927_taxonomy_abundances_SSU_v5.0.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP139/ERP139927/version_5.0/project-summary/taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b677d0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120bc4440> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b7a8d0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:16 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP140102_taxonomy_abundances_SSU_v5.0.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP140/ERP140102/version_5.0/project-summary/taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b96490>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120bc4950> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x10c5d9f90>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:16 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP140107_taxonomy_abundances_SSU_v5.0.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP140/ERP140107/version_5.0/project-summary/taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b670d0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120bc4d40> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b47c90>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:16 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP140115_taxonomy_abundances_SSU_v5.0.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP140/ERP140115/version_5.0/project-summary/taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b54550>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120bc4830> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x10c4c0d90>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:16 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP139923_taxonomy_abundances_SSU_v5.0.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP139/ERP139923/version_5.0/project-summary/taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for TaxaMGazine_Taxonomic assignments SSU
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.mixins:Loading cache for TaxaMGazine_Taxonomic assignments SSU from /Users/phanthanourak/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/phanthanourak/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.mixins:Loading cached page from /Users/phanthanourak/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9/mgnipy_page_1.json
DEBUG:mgnipy.V2.mixins:Computed cache key for TaxaMGazine_Taxonomic assignments SSU: 3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9
INFO:mgnipy.V2.mixins:Loading cache manifest from /Users/phanthanourak/Library/Caches/mgnipy/3a8dc16d4da6278d91e32df81347baf74b49eccde3afcfd89e039ee1a5c81ca9/mgnipy_manifest.json
INFO:mgnipy.V2.mixins:Loaded 1 cached pages

<class 'mgnipy.V2.datasets.taxonomic.TaxaMGazine'>
MGazine Curation TaxaMGazine containing:
- MGnify pipeline versions: ['v5']
- Number of downloads: 5
- Short descriptions: ['Taxonomic assignments SSU']

,file_type,download_type,short_description,long_description,alias,download_group,file_size_bytes,index_files,url,accession,pipeline_version
0,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP139927_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
1,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140102_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
2,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140107_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
3,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140115_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
4,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP139923_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5

for more options over the filtering of mgazines see the [MGazine informtion page](TODO). We will carry on with our filtered TaxaMGazine given [our goal](#-the-goal-retrieve-taxonomic-datasets-of-tomato-rhizosphere-studies) for now

### Downloading datasets

You can pass the `url` or `alias` if wanting to `.download()` or explore/read in via `.stream()` ONE download file/dataset. 

You can look at the file aliases as a list via `.aliases` attribute, also shown in "alias" column in `.downloads_df`

The urls are also in a column in `.downloads_df` but there are also helpers `.url_list` and `.url_dict` which provide {alias: url}

In [7]:
# lets try out one 
one_alias = ssu.aliases[0]
print(one_alias)

# downloading to a downloads folder
ssu.download(to_dir="downloads", alias=one_alias)

DEBUG:mgnipy.V2.datasets:Ensuring download directory exists: downloads
DEBUG:mgnipy.V2.datasets:Prepared file path for download: downloads/ERP139927_taxonomy_abundances_SSU_v5.0.tsv
INFO:mgnipy.V2.datasets:File already exists and overwrite is False, skipping download: downloads/ERP139927_taxonomy_abundances_SSU_v5.0.tsv

ERP139927_taxonomy_abundances_SSU_v5.0.tsv

also the option to `download_all()`

In [8]:
ssu.download_all(to_dir="downloads")

DEBUG:mgnipy.V2.datasets:Initializing client once for all downloads
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x10c47bdd0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120bc5010> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b303d0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:18 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
DEBUG:mgnipy.V2.query_set:Built request URL for _downloads: https://www.ebi.ac.uk/
DEBUG:mgnipy.V2.datasets:MGnifier helper created: MGnifier instance for resource: _downloads
I.e., mgnipy.V2.core.MGnifier
----------------------------------------
Base URL: https://www.ebi.ac.uk/
Parameters: {'url': ''}
Example request URL: https://www.ebi.ac.uk/
Endpoint module: mgnipy.V2.custom_endpoint
Is list endpoint (returns paginated results): False
Cache directory: None

Overall Progress:   0%|          | 0/5 [00:00<?, ?it/s]DEBUG:mgnipy.V2.datasets:Ensuring download directory exists: downloads
DEBUG:mgnipy.V2.datasets:Prepared file path for download: downloads/ERP139927_taxonomy_abundances_SSU_v5.0.tsv
INFO:mgnipy.V2.datasets:File already exists and overwrite is False, skipping download: downloads/ERP139927_taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Ensuring download directory exists: downloads
DEBUG:mgnipy.V2.datasets:Prepared file path for download: downloads/ERP140102_taxonomy_abundances_SSU_v5.0.tsv
INFO:mgnipy.V2.datasets:File already exists and overwrite is False, skipping download: downloads/ERP140102_taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Ensuring download directory exists: downloads
DEBUG:mgnipy.V2.datasets:Prepared file path for download: downloads/ERP140107_taxonomy_abundances_SSU_v5.0.tsv
INFO:mgnipy.V2.datasets:File already exists and overwrite is False, skipping download: downloads/ERP140107_taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Ensuring download directory exists: downloads
DEBUG:mgnipy.V2.datasets:Prepared file path for download: downloads/ERP140115_taxonomy_abundances_SSU_v5.0.tsv
INFO:mgnipy.V2.datasets:File already exists and overwrite is False, skipping download: downloads/ERP140115_taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Ensuring download directory exists: downloads
DEBUG:mgnipy.V2.datasets:Prepared file path for download: downloads/ERP139923_taxonomy_abundances_SSU_v5.0.tsv
INFO:mgnipy.V2.datasets:File already exists and overwrite is False, skipping download: downloads/ERP139923_taxonomy_abundances_SSU_v5.0.tsv
Overall Progress: 100%|==========| 5/5 [00:00<00:00, 548.72it/s]

### Reading in a dataset `.stream()`

`.stream() `resolves a download alias or URL and returns the appropriate streaming handler for the file type. It supports returning either a full object (when `chunksize` is `None`) or an iterator of chunks when chunksize is provided. 

Supported formats include:
- TSV/CSV — stream_pandas (pandas) or stream_polars (polars) (handles gzipped TSV/CSV).
- FASTA / GFF / BIOM — stream_fasta, stream_gff, stream_biom (scikit-bio generators).
- JSONL / NDJSON — stream_jsonl (pandas or polars).

See [Intro to MGazine page](TODO) for more information

In [9]:
df = ssu.stream(alias=one_alias, dataframe_engine="pandas")
df.head()

DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource _downloads
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b87150>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120bc4950> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120be17d0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:18 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for _downloads
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for _downloads
INFO:mgnipy.V2.query_set:Attempting to load cached results for _downloads
DEBUG:mgnipy.V2.mixins:Skipping cache load for _downloads because cache is disabled
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource _downloads
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
INFO:mgnipy.V2.datasets:MGnifier initialized with resource=_downloads and url=
INFO:mgnipy.V2.mixins:Setting up stream for alias=ERP139927_taxonomy_abundances_SSU_v5.0.tsv url=https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP139/ERP139927/version_5.0/project-summary/taxonomy_abundances_SSU_v5.0.tsv
DEBUG:mgnipy.V2.datasets:Both `alias` and `url` provided, ignoring `url`.

,#SampleID,ERZ12343720,ERZ12343730,ERZ12343740,ERZ12343750,ERZ12343760,ERZ12343770,ERZ12343780,ERZ12343721,ERZ12343731,...,ERZ12590947,ERZ12593067,ERZ12590878,ERZ12590908,ERZ12590968,ERZ12590988,ERZ12590849,ERZ12590879,ERZ12590889,ERZ12590909
0,sk__Archaea,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,sk__Archaea;k__;p__Crenarchaeota,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,sk__Archaea;k__;p__Crenarchaeota;c__Thermoprot...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,sk__Archaea;k__;p__Thaumarchaeota;c__Nitrososp...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,sk__Archaea;k__;p__Thaumarchaeota;c__Nitrososp...,0,1,0,0,0,0,0,1,1,...,0,1,1,0,1,1,0,0,0,1

## ✨ Bonus section: The `TaxaMGazine`

There are analysis type-specific mgazines, such as this TaxaMGazine

for example, we can also combine the taxonomic assignment results into one dataframe e.g. `.to_pandas()`, `.to_polars`, `.X()`

In [10]:
ssu.to_pandas()

,#SampleID,ERZ12343720,ERZ12343730,ERZ12343740,ERZ12343750,ERZ12343760,ERZ12343770,ERZ12343780,ERZ12343721,ERZ12343731,...,ERZ12633581,ERZ12633572,ERZ12633582,ERZ12633573,ERZ12633574,ERZ12633594,ERZ12633576,ERZ12633579,ERZ12590661,ERZ12590669
0,sk__Archaea,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0
1,sk__Archaea;k__;p__Crenarchaeota,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,sk__Archaea;k__;p__Crenarchaeota;c__Thermoprot...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,sk__Archaea;k__;p__Thaumarchaeota;c__Nitrososp...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,sk__Archaea;k__;p__Thaumarchaeota;c__Nitrososp...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,sk__Bacteria;k__;p__Proteobacteria;c__Deltapro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0
554,sk__Bacteria;k__;p__Proteobacteria;c__Deltapro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
555,sk__Bacteria;k__;p__Bacteroidetes;c__Chitinoph...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
556,sk__Bacteria;k__;p__Proteobacteria;c__Deltapro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
557,sk__Eukaryota;k__Viridiplantae;p__Streptophyta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0

There is also option to enrich with additional metadata! 

1)  From *already* retrieved `MGnifier` results you can set to `runs_results`, `samples_results`, `studies_results` etc, or

2) use `.enrich_runs()` etc or `.enrich_biosamples` which will make the get requests for the additional metadata

In [11]:
ssu.enrich_runs(limit=None)

DEBUG:mgnipy.V2.datasets.taxonomic:Starting enrichment of runs for short description Taxonomic assignments SSU with limit None.
Enriching runs:  93%|█████████▎| 138/149 [00:00<?, ?it/s]INFO:mgnipy.V2.datasets.taxonomic:Enriching run ERZ12633580 for short description Taxonomic assignments SSU. Count: 0
DEBUG:mgnipy.V2.datasets.taxonomic:Run ERZ12633580 appears to be an assembly. Using AssemblyDetail proxy for enrichment.
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'assembly': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource assembly
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b5f710>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120c39d90> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b5c3d0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:19 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for assembly
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for assembly
INFO:mgnipy.V2.query_set:Attempting to load cached results for assembly
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: 1bc3d30cd3859b6b0b015f76f963f85fea28825c1046506a81364cf853bea5f3
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/phanthanourak/Library/Caches/mgnipy/1bc3d30cd3859b6b0b015f76f963f85fea28825c1046506a81364cf853bea5f3
INFO:mgnipy.V2.mixins:No cache directory found at /Users/phanthanourak/Library/Caches/mgnipy/1bc3d30cd3859b6b0b015f76f963f85fea28825c1046506a81364cf853bea5f3
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource assembly
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: 1bc3d30cd3859b6b0b015f76f963f85fea28825c1046506a81364cf853bea5f3
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Total items is unknown (no dry run) running set_counts() to retrieve count.
DEBUG:mgnipy.V2.query_executor:Computed count and num_requests: 1, 1
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=0 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 1 items (max page 1): [1]
INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for assembly page 1: False
INFO:mgnipy.V2.query_set:Building query plan for assembly
DEBUG:mgnipy.V2.query_set:Built single-query plan for assembly
INFO:mgnipy.V2.query_executor:Fetching request num 1 with params: {'accession': 'ERZ12633580'}
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b54590>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120c39e20> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b44c50>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:19 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: GET https://www.ebi.ac.uk/metagenomics/api/v2/assemblies/ERZ12633580 "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
INFO:mgnipy.V2.query_executor:Response status code: 500
WARNING:mgnipy.V2.query_executor:No response received from API.
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: 1bc3d30cd3859b6b0b015f76f963f85fea28825c1046506a81364cf853bea5f3
INFO:mgnipy.V2.mixins:Writing cached results for page 1
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: 1bc3d30cd3859b6b0b015f76f963f85fea28825c1046506a81364cf853bea5f3
INFO:mgnipy.V2.mixins:Writing page 1 to /Users/phanthanourak/Library/Caches/mgnipy/1bc3d30cd3859b6b0b015f76f963f85fea28825c1046506a81364cf853bea5f3/mgnipy_page_1.json and manifest to /Users/phanthanourak/Library/Caches/mgnipy/1bc3d30cd3859b6b0b015f76f963f85fea28825c1046506a81364cf853bea5f3/mgnipy_manifest.json
WARNING:mgnipy.V2.datasets.taxonomic:Run ERZ12633580 could not be retrieved. Skipping.
Enriching runs:  93%|█████████▎| 139/149 [00:00<00:01,  5.11it/s]INFO:mgnipy.V2.datasets.taxonomic:Enriching run ERZ12633581 for short description Taxonomic assignments SSU. Count: 1
DEBUG:mgnipy.V2.datasets.taxonomic:Run ERZ12633581 appears to be an assembly. Using AssemblyDetail proxy for enrichment.
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'assembly': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource assembly
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120c47f10>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120c3a3c0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b84210>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:19 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for assembly
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for assembly
INFO:mgnipy.V2.query_set:Attempting to load cached results for assembly
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: e79a3761f93f72f8eab8828211608188329bcfadf763271a708041f87267f3d8
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/phanthanourak/Library/Caches/mgnipy/e79a3761f93f72f8eab8828211608188329bcfadf763271a708041f87267f3d8
INFO:mgnipy.V2.mixins:No cache directory found at /Users/phanthanourak/Library/Caches/mgnipy/e79a3761f93f72f8eab8828211608188329bcfadf763271a708041f87267f3d8
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource assembly
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: e79a3761f93f72f8eab8828211608188329bcfadf763271a708041f87267f3d8
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Total items is unknown (no dry run) running set_counts() to retrieve count.
DEBUG:mgnipy.V2.query_executor:Computed count and num_requests: 1, 1
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=0 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 1 items (max page 1): [1]
INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for assembly page 1: False
INFO:mgnipy.V2.query_set:Building query plan for assembly
DEBUG:mgnipy.V2.query_set:Built single-query plan for assembly
INFO:mgnipy.V2.query_executor:Fetching request num 1 with params: {'accession': 'ERZ12633581'}
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120b5c910>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120c3a570> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120baf050>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:19 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: GET https://www.ebi.ac.uk/metagenomics/api/v2/assemblies/ERZ12633581 "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
INFO:mgnipy.V2.query_executor:Response status code: 500
WARNING:mgnipy.V2.query_executor:No response received from API.
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: e79a3761f93f72f8eab8828211608188329bcfadf763271a708041f87267f3d8
INFO:mgnipy.V2.mixins:Writing cached results for page 1
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: e79a3761f93f72f8eab8828211608188329bcfadf763271a708041f87267f3d8
INFO:mgnipy.V2.mixins:Writing page 1 to /Users/phanthanourak/Library/Caches/mgnipy/e79a3761f93f72f8eab8828211608188329bcfadf763271a708041f87267f3d8/mgnipy_page_1.json and manifest to /Users/phanthanourak/Library/Caches/mgnipy/e79a3761f93f72f8eab8828211608188329bcfadf763271a708041f87267f3d8/mgnipy_manifest.json
WARNING:mgnipy.V2.datasets.taxonomic:Run ERZ12633581 could not be retrieved. Skipping.
Enriching runs:  94%|█████████▍| 140/149 [00:00<00:02,  3.70it/s]INFO:mgnipy.V2.datasets.taxonomic:Enriching run ERZ12633572 for short description Taxonomic assignments SSU. Count: 2
DEBUG:mgnipy.V2.datasets.taxonomic:Run ERZ12633572 appears to be an assembly. Using AssemblyDetail proxy for enrichment.
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'assembly': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource assembly
DEBUG:mgnipy._models.config:No valid auth token available, obtaining new one...
DEBUG:mgnipy._models.config:getting username and password...
DEBUG:mgnipy._models.config:retrieved username and password...
DEBUG:mgnipy._models.config:prepping body for token request...
DEBUG:mgnipy._models.config:requesting token from API...
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120be1090>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120c3aa80> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120c46650>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:19 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: POST https://www.ebi.ac.uk/metagenomics/api/v2/auth/sliding "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:mgnipy._models.config:No login credentials provided, unable to obtain auth_token.
DEBUG:mgnipy.V2.query_set:Creating cache handler for assembly
DEBUG:mgnipy.V2.mixins:Initializing DiskCheckpointer for assembly
INFO:mgnipy.V2.query_set:Attempting to load cached results for assembly
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: b574f5ad7c0484919f96d104476e5cdba2ef512b9adfb79c125914b420069089
INFO:mgnipy.V2.mixins:Loading cached pages from /Users/phanthanourak/Library/Caches/mgnipy/b574f5ad7c0484919f96d104476e5cdba2ef512b9adfb79c125914b420069089
INFO:mgnipy.V2.mixins:No cache directory found at /Users/phanthanourak/Library/Caches/mgnipy/b574f5ad7c0484919f96d104476e5cdba2ef512b9adfb79c125914b420069089
INFO:mgnipy.V2.query_set:Loaded pages [] from cache for resource assembly
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: b574f5ad7c0484919f96d104476e5cdba2ef512b9adfb79c125914b420069089
DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.query_executor:Total items is unknown (no dry run) running set_counts() to retrieve count.
DEBUG:mgnipy.V2.query_executor:Computed count and num_requests: 1, 1
DEBUG:mgnipy.V2.query_executor:Resolved number of requests for this collection round: 1. (upper caps: 2500 items or 100 pages)
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying from_page=0 filter: [1]
DEBUG:mgnipy.V2.query_executor:Pages to collect after applying limit of 1 items (max page 1): [1]
INFO:mgnipy.V2.query_executor:Advancing to request num 1
DEBUG:mgnipy.V2.query_executor:Using cached count and num_requests vals: 1, 1
DEBUG:mgnipy.V2.query_set:Result presence check for assembly page 1: False
INFO:mgnipy.V2.query_set:Building query plan for assembly
DEBUG:mgnipy.V2.query_set:Built single-query plan for assembly
INFO:mgnipy.V2.query_executor:Fetching request num 1 with params: {'accession': 'ERZ12633572'}
DEBUG:httpcore.connection:connect_tcp.started host='www.ebi.ac.uk' port=443 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120c47110>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x120c3a8d0> server_hostname='www.ebi.ac.uk' timeout=None
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x120c44390>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Content-Type', b'text/html'), (b'Strict-Transport-Security', b'max-age=0'), (b'Date', b'Fri, 29 May 2026 14:12:19 GMT'), (b'Connection', b'close'), (b'Content-Length', b'141')])
INFO:httpx:HTTP Request: GET https://www.ebi.ac.uk/metagenomics/api/v2/assemblies/ERZ12633572 "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
INFO:mgnipy.V2.query_executor:Response status code: 500
WARNING:mgnipy.V2.query_executor:No response received from API.
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: b574f5ad7c0484919f96d104476e5cdba2ef512b9adfb79c125914b420069089
INFO:mgnipy.V2.mixins:Writing cached results for page 1
DEBUG:mgnipy.V2.mixins:Computed cache key for assembly: b574f5ad7c0484919f96d104476e5cdba2ef512b9adfb79c125914b420069089
INFO:mgnipy.V2.mixins:Writing page 1 to /Users/phanthanourak/Library/Caches/mgnipy/b574f5ad7c0484919f96d104476e5cdba2ef512b9adfb79c125914b420069089/mgnipy_page_1.json and manifest to /Users/phanthanourak/Library/Caches/mgnipy/b574f5ad7c0484919f96d104476e5cdba2ef512b9adfb79c125914b420069089/mgnipy_manifest.json
WARNING:mgnipy.V2.datasets.taxonomic:Run ERZ12633572 could not be retrieved. Skipping.
Enriching runs:  95%|█████████▍| 141/149 [00:00<00:01,  4.26it/s]INFO:mgnipy.V2.datasets.taxonomic:Enriching run ERZ12633582 for short description Taxonomic assignments SSU. Count: 3
DEBUG:mgnipy.V2.datasets.taxonomic:Run ERZ12633582 appears to be an assembly. Using AssemblyDetail proxy for enrichment.
DEBUG:mgnipy.V2.proxies:Resolved id param key for 'assembly': 'accession'
DEBUG:mgnipy.V2.query_set:Initializing QuerySet for resource assembly

In [12]:
ssu.to_anndata()

DEBUG:mgnipy.V2.mixins:Initializing ResultsHandler
DEBUG:mgnipy.V2.mixins:Converting results to pandas DataFrame; expand_nested_dicts=True
/Users/phanthanourak/.pyenv/versions/3.11.14/lib/python3.11/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)
ERROR:mgnipy.V2.datasets.taxonomic:Returning without var Error occurred while converting to AnnData: Observations annot. `var` must have as many rows as `X` has columns (149), but has 138 rows.
/Users/phanthanourak/.pyenv/versions/3.11.14/lib/python3.11/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

AnnData object with n_obs × n_vars = 558 × 149
    obs: 'Superkingdom', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'

---

## Wrap Up: 

This page was a quick start demonstration of:

1. ✅ Start up a `mgnipy.MGnipy` client with your desired configuration

2. ✅ Search in MGnify resources using a MGnifier glass

3. ✅ Receive a MGazine of MGnify datasets