# Demo: Retrieving Mgnify tomato samples

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ebi-metagenomics/mgnipy/blob/main/docs/tutorial/demo-mgnify-tomatoes.ipynb)

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# uncomment below if colab
#!pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple mgnipy
#!pip install asyncio

In this tutorial we demonstrate how mgnipy can be used to retrieve tomato rhizosphere metagenomics analyses (only sample metadata for now) available on MGnify.

In [3]:
from mgnipy import MGnipy

#import logging 
#logging.basicConfig(level=logging.INFO)

Choose your entry resource proxy

In [4]:
# init 
MG = MGnipy(
    # configuration
)

# helper 
MG.list_resources()

['analyses',
 'assemblies',
 'genomes',
 'publications',
 'samples',
 'studies',
 'biomes']

you can either pass query parameters as dict to `params` or as kwargs.

In [5]:
#  resource proxy
biomes = MG.biomes

# helper
biomes.list_parameters()

['biome_lineage', 'max_depth', 'page', 'page_size']

In [6]:
filtered_b = biomes.filter(
    biome_lineage="root:Host-associated:Plants:Rhizosphere"
)

filtered_b.get()

Planning the API call with params:
{'biome_lineage': 'root:Host-associated:Plants:Rhizosphere', 'page_size': 25}
Total pages to retrieve: 1
Total records to retrieve: 4

Retrieving pages: 0it [00:00, ?it/s]

In [7]:
filtered_b[0]

In [8]:
# studies resource proxy
studies = MG.studies

# helper
studies.list_parameters()

['order',
 'biome_lineage',
 'has_analyses_from_pipeline',
 'search',
 'page',
 'page_size']

In [9]:
# set up query
filtered_studies = studies.filter(
    biome_lineage='root:Host-associated:Plants:Rhizosphere',
    search='tomato'
)

# preview before getting all pages 
filtered_studies.dry_run()

Planning the API call with params:
{'biome_lineage': 'root:Host-associated:Plants:Rhizosphere', 'search': 'tomato', 'page_size': 25}
Total pages to retrieve: 1
Total records to retrieve: 17

In [10]:
# make the get request
filtered_studies.get()

# also option async get
# import asyncio
# await studies.aget()

# look at results 
filtered_studies.to_pandas()

Retrieving pages:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  4.36it/s]

,accession,ena_accessions,title,biome,updated_at
0,MGYS00010296,"[ERP166137, PRJEB82448]",Microbiome-mediated tolerance of wild tomato t...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T14:00:52.352000+00:00
1,MGYS00010297,"[SRP333165, PRJNA755742]",Tomato rhizosphere microbiome in the pot exper...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:42:02.227000+00:00
2,MGYS00006204,"[ERP140102, PRJEB55219]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-01-27T16:27:14.469000+00:00
3,MGYS00006205,"[ERP140107, PRJEB55224]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-01-27T16:27:14.478000+00:00
4,MGYS00006208,"[ERP140115, PRJEB55232]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-01-27T16:27:14.505000+00:00
5,MGYS00006230,"[ERP139923, PRJEB55057]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-01-27T16:27:14.714000+00:00
6,MGYS00006231,"[ERP139927, PRJEB55060]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-01-27T16:27:14.722000+00:00
7,MGYS00010257,"[SRP456588, PRJNA1004080]",Combined effect of microplastics and fungicide...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-03T18:47:35.095000+00:00
8,MGYS00010258,"[SRP517058, PRJNA1127303]",Metagenomic data of rhizosphere soil during to...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-04T11:04:15.175000+00:00
9,MGYS00010324,[PRJEB95772],Metagenome assembly of PRJNA777724 data set (T...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-07T12:30:16.888000+00:00
10,MGYS00010245,"[PRJEB82447, ERP166136]",Unveiling diversity and adaptations of the wil...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-23T16:38:33.334000+00:00
11,MGYS00010298,"[PRJNA777724, SRP344777]",Tomato heritable microbiome,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-07T15:25:59.939000+00:00
12,MGYS00010262,[PRJEB91684],Metagenome assembly of PRJNA1004080 data set (...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-03T18:41:58.194000+00:00
13,MGYS00010250,"[PRJNA755741, SRP333163]",Tomato rhizosphere microbiome in the belowgrou...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-23T08:45:47.142000+00:00
14,MGYS00010264,[PRJEB91717],Metagenome assembly of PRJNA1127303 data set (...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-04T10:10:15.643000+00:00
15,MGYS00010251,"[SRP338795, PRJNA766489]",Culture-independent analysis of rhizosphere mi...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-21T17:01:18.132000+00:00
16,MGYS00010253,"[PRJNA789467, SRP351203]",Disentangling the genetic basis of rhizosphere...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-01T17:26:35.948000+00:00

In [11]:
# all samples for a given study above?
# first study 
second_study_samples = filtered_studies[1]
# or getitem by accession
# first_study_samples = studies["MGYS00010297"]

second_study_samples.get()
second_study_samples.to_pandas()

Planning the API call with params:
{'accession': 'MGYS00010297', 'page_size': 25}
Total pages to retrieve: 1
Total records to retrieve: 12

Retrieving pages: 0it [00:00, ?it/s]

,accession,ena_accessions,sample_title,biome,updated_at,lat,lon
0,SRS9830941,"[SRS9830941, SAMN20841010]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.650000+00:00,45.41,126.37
1,SRS9830940,"[SRS9830940, SAMN20841019]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.685000+00:00,45.41,126.37
2,SRS9830946,"[SRS9830946, SAMN20841015]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.711000+00:00,45.41,126.37
3,SRS9830942,"[SRS9830942, SAMN20841011]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.736000+00:00,45.41,126.37
4,SAMN20841008,"[SAMN20841008, SRS9830937]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.761000+00:00,45.41,126.37
5,SRS9830948,"[SRS9830948, SAMN20841017]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.788000+00:00,45.41,126.37
6,SAMN20841016,"[SAMN20841016, SRS9830947]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.812000+00:00,45.41,126.37
7,SRS9830945,"[SRS9830945, SAMN20841014]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.837000+00:00,45.41,126.37
8,SAMN20841013,"[SAMN20841013, SRS9830944]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.861000+00:00,45.41,126.37
9,SRS9830943,"[SRS9830943, SAMN20841012]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.886000+00:00,45.41,126.37
10,SAMN20841018,"[SAMN20841018, SRS9830939]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.911000+00:00,45.41,126.37
11,SAMN20841009,"[SAMN20841009, SRS9830938]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.939000+00:00,45.41,126.37

you can also pass a slice which will return the samples proxies in a list

In [12]:
filtered_studies[:5]

[<mgnipy.V2.metadata.SamplesProxy at 0x11279ffd0>,
 <mgnipy.V2.metadata.SamplesProxy at 0x1127a7590>,
 <mgnipy.V2.metadata.SamplesProxy at 0x1127516d0>,
 <mgnipy.V2.metadata.SamplesProxy at 0x1127a4050>,
 <mgnipy.V2.metadata.SamplesProxy at 0x11278d5d0>]

## getting analyses for given studies

In [13]:
analyses = MG.analyses
# same as 
# from mgnipy.V2.metadata import AnalysesProxy
# analyses = AnalysesProxy()
import asyncio

In [14]:
analyses_proxies = {}
for study in filtered_studies.results_accessions:
    print(study)
    analyses_proxies[study] = analyses.filter(accession=study)
    await analyses_proxies[study].aget()

MGYS00010296
Planning the API call with params:
{'accession': 'MGYS00010296', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00010297
Planning the API call with params:
{'accession': 'MGYS00010297', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00006204
Planning the API call with params:
{'accession': 'MGYS00006204', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00006205
Planning the API call with params:
{'accession': 'MGYS00006205', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00006208

Planning the API call with params:
{'accession': 'MGYS00006208', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00006230
Planning the API call with params:
{'accession': 'MGYS00006230', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00006231
Planning the API call with params:
{'accession': 'MGYS00006231', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00010257
Planning the API call with params:
{'accession': 'MGYS00010257', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00010258
Planning the API call with params:
{'accession': 'MGYS00010258', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00010324
Planning the API call with params:
{'accession': 'MGYS00010324', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00010245
Planning the API call with params:
{'accession': 'MGYS00010245', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00010298
Planning the API call with params:
{'accession': 'MGYS00010298', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00010262
Planning the API call with params:
{'accession': 'MGYS00010262', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00010250
Planning the API call with params:
{'accession': 'MGYS00010250', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00010264
Planning the API call with params:
{'accession': 'MGYS00010264', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00010251
Planning the API call with params:
{'accession': 'MGYS00010251', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

MGYS00010253
Planning the API call with params:
{'accession': 'MGYS00010253', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0

0it [00:00, ?it/s]

Need to stop there with tomatos because analyses not yet loaded.

Instead getting an accession MGYS00006793

In [30]:
# from mgnipy import MGnipy
MG = MGnipy()
a_proxy = MG.analyses

# from mgnipy.V2.metadata import AnalysesProxy
# a_proxy = AnalysesProxy()
# a_proxy.endpoint_module

In [33]:
a = a_proxy.filter(accession="MGYS00006793")
a.endpoint_module
#a.dry_run()

In [34]:
a.get()

Planning the API call with params:
{'accession': 'MGYS00006793', 'page_size': 25}
Total pages to retrieve: 1
Total records to retrieve: 7

Retrieving pages: 0it [00:00, ?it/s]

In [35]:
a.to_pandas()

,study_accession,accession,experiment_type,run,sample,assembly,pipeline_version
0,MGYS00006793,MGYA01000016,Amplicon,"{'accession': 'SRR8451752', 'instrument_model'...","{'accession': 'SAMN10624955', 'ena_accessions'...",None,V6
1,MGYS00006793,MGYA01000010,Amplicon,"{'accession': 'SRR8451748', 'instrument_model'...","{'accession': 'SAMN10624959', 'ena_accessions'...",None,V6
2,MGYS00006793,MGYA01000011,Amplicon,"{'accession': 'SRR8451746', 'instrument_model'...","{'accession': 'SAMN10624954', 'ena_accessions'...",None,V6
3,MGYS00006793,MGYA01000015,Amplicon,"{'accession': 'SRR8451751', 'instrument_model'...","{'accession': 'SAMN10624956', 'ena_accessions'...",None,V6
4,MGYS00006793,MGYA01000012,Amplicon,"{'accession': 'SRR8451747', 'instrument_model'...","{'accession': 'SAMN10624960', 'ena_accessions'...",None,V6
5,MGYS00006793,MGYA01000013,Amplicon,"{'accession': 'SRR8451749', 'instrument_model'...","{'accession': 'SAMN10624958', 'ena_accessions'...",None,V6
6,MGYS00006793,MGYA01000014,Amplicon,"{'accession': 'SRR8451750', 'instrument_model'...","{'accession': 'SAMN10624957', 'ena_accessions'...",None,V6

In [36]:
a.linked_proxy_module

mgnipy.V2.datasets.DatasetBuilder

## assemblies

In [78]:
from mgnipy import MGnipy

MG = MGnipy()

assemblies = MG.assemblies

assemblies.dry_run()

Planning the API call with params:
{'page_size': 25}
Total pages to retrieve: 758
Total records to retrieve: 18947

In [79]:
# only wanting 10 result really, but because of page_size then first page of page_size num results
assemblies.get(limit=10)

assemblies[:]

Retrieving pages:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  4.41it/s]

[<mgnipy.V2.metadata.AnalysesProxy at 0x10e8dd8d0>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1134aa2d0>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x11362bc90>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1134a9a10>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136f2610>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136f0c90>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136f13d0>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136f3150>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136f2710>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136f0990>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136f16d0>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136f1490>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136f0690>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x11345a090>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136f0f10>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136d6590>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x10a43fa50>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136d4a90>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136d6a90>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136d4110>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136d58d0>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136d6890>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136d7750>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136d7550>,
 <mgnipy.V2.metadata.AnalysesProxy at 0x1136d5890>]

In [ ]:
aa_proxies = assemblies[:]
for aa in aa_proxies:
    print(aa.accession)
    aa.dry_run()

# TODO need to deal with None accessions

ERZ24911306
Planning the API call with params:
{'accession': 'ERZ24911306', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0
ERZ24985237
Planning the API call with params:
{'accession': 'ERZ24985237', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0
ERZ24985238
Planning the API call with params:
{'accession': 'ERZ24985238', 'page_size': 25}
Total pages to retrieve: 0
Total records to retrieve: 0
None
Planning the API call with params:

TypeError: sync_detailed() got an unexpected keyword argument 'accession'

In [42]:
from mgnipy._shared_helpers.ena_helpers import get_analyses_accession_by_study_accession, ENAAnalysisFields

get_analyses_accession_by_study_accession(limit=10)

[{'analysis_accession': 'ERZ10043910',
  'age': '',
  'altitude': '',
  'analysis_alias': 'webin-genome-IMS-10150-CVDP-B352AEEB-9839-4FAC-A26',
  'analysis_code_repository': '',
  'analysis_date': '',
  'analysis_description': '',
  'analysis_protocol': '',
  'analysis_title': 'Genome assembly: IMS-10150-CVDP-B352AEEB-9839-4FAC-A26',
  'analysis_type': 'SEQUENCE_ASSEMBLY',
  'assembly_quality': '',
  'assembly_software': '',
  'assembly_type': 'COVID-19 outbreak',
  'binning_software': '',
  'bio_material': '',
  'broad_scale_environmental_context': '',
  'broker_name': 'RKI-OSEDA',
  'cell_line': '',
  'cell_type': '',
  'center_name': 'ROBERT KOCH INSTITUTE;RKI-OSEDA',
  'checklist': 'ERC000033',
  'collected_by': '',
  'collection_date': '2022-02-07',
  'collection_date_end': '2022-02-07',
  'collection_date_start': '2022-02-07',
  'completeness_score': '',
  'contamination_score': '',
  'country': 'Germany',
  'cultivar': '',
  'culture_collection': '',
  'datahub': '',
  'depth': '',
  'description': '',
  'dev_stage': '',
  'disease': '',
  'ecotype': '',
  'elevation': '',
  'environment_biome': '',
  'environment_feature': '',
  'environment_material': '',
  'environmental_medium': '',
  'environmental_sample': '',
  'experiment_accession': '',
  'experimental_factor': '',
  'first_created': '2022-05-14',
  'first_public': '2022-05-14',
  'generated_aspera': '',
  'generated_bytes': '',
  'generated_format': '',
  'generated_ftp': '',
  'generated_galaxy': '',
  'generated_md5': '',
  'germline': '',
  'host': 'Homo sapiens',
  'host_body_site': '',
  'host_genotype': '',
  'host_gravidity': '',
  'host_growth_conditions': '',
  'host_phenotype': '',
  'host_scientific_name': 'Homo sapiens',
  'host_sex': '',
  'host_status': '',
  'host_tax_id': '9606',
  'identified_by': '',
  'investigation_type': '',
  'isolate': '',
  'isolation_source': '',
  'last_updated': '2022-05-14',
  'lat': '',
  'local_environmental_context': '',
  'location': '',
  'location_end': '',
  'location_start': '',
  'lon': '',
  'marine_region': '',
  'mating_type': '',
  'ncbi_reporting_standard': '',
  'ph': '',
  'pipeline_name': '',
  'pipeline_version': '',
  'project_name': '',
  'protocol_label': '',
  'pubmed_id': '',
  'reference_data_set_name': '',
  'reference_data_set_version': '',
  'reference_genome': '',
  'related_analysis_accession': '',
  'run_accession': '',
  'salinity': '',
  'sample_accession': 'SAMEA13729043',
  'sample_alias': 'IMS-10150-CVDP-B352AEEB-9839-4FAC-A265-5774284FA609',
  'sample_capture_status': 'active surveillance in response to outbreak',
  'sample_collection': '',
  'sample_description': 'Molecular surveillance of SARS-CoV-2 in Germany',
  'sample_material': '',
  'sample_title': 'Molecular surveillance of SARS-CoV-2 in Germany',
  'sampling_campaign': '',
  'sampling_platform': '',
  'sampling_site': '',
  'scientific_name': 'Severe acute respiratory syndrome coronavirus 2',
  'secondary_project': '',
  'secondary_sample_accession': 'ERS11330658',
  'secondary_study_accession': 'ERP129098',
  'sequencing_method': '',
  'serotype': '',
  'serovar': '',
  'sex': '',
  'specimen_voucher': '',
  'status': 'public',
  'strain': '',
  'study_accession': 'PRJEB44987',
  'study_alias': 'ena-STUDY-Robert Koch Institute-16-05-2021-16:06:46:171-179',
  'study_title': 'The Robert Koch Institute provides molecular and epidemiological data for the molecular surveillance of SARS-CoV-2 in Germany. Quality control passed',
  'sub_species': '',
  'sub_strain': '',
  'submission_accession': 'ERA14121874',
  'submission_tool': '',
  'submitted_aspera': 'fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10043910/file.fasta.gz;fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10043910/file.list.gz',
  'submitted_bytes': '8855;34',
  'submitted_format': 'FASTA;CHROMOSOME_LIST',
  'submitted_ftp': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043910/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043910/file.list.gz',
  'submitted_galaxy': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043910/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043910/file.list.gz',
  'submitted_host_sex': '',
  'submitted_md5': 'bf29349e7b3628a62e64c765503fa6f1;5aaa584c7ab0743f52b7c029ada4bdd5',
  'tag': 'covid19;pathogen;pathogen:virus;pathogen:priority',
  'target_gene': '',
  'tax_id': '2697049',
  'tax_lineage': '1;10239;2559587;2732396;2732408;2732506;76804;2499399;11118;2501931;694002;2509511;3418604;2697049',
  'taxonomic_classification': '',
  'taxonomic_identity_marker': '',
  'temperature': '',
  'tissue_lib': '',
  'tissue_type': '',
  'variety': ''},
 {'analysis_accession': 'ERZ10043917',
  'age': '',
  'altitude': '',
  'analysis_alias': 'webin-genome-hCoV-19.Scotland.QEUH-3DF09F3.2022',
  'analysis_code_repository': '',
  'analysis_date': '',
  'analysis_description': '',
  'analysis_protocol': '',
  'analysis_title': 'Genome assembly: hCoV-19.Scotland.QEUH-3DF09F3.2022',
  'analysis_type': 'SEQUENCE_ASSEMBLY',
  'assembly_quality': '',
  'assembly_software': '',
  'assembly_type': 'COVID-19 outbreak',
  'binning_software': '',
  'bio_material': '',
  'broad_scale_environmental_context': '',
  'broker_name': '',
  'cell_line': '',
  'cell_type': '',
  'center_name': 'Wellcome Sanger Institute;SC',
  'checklist': 'ERC000033',
  'collected_by': '',
  'collection_date': '2022-04-26',
  'collection_date_end': '2022-04-26',
  'collection_date_start': '2022-04-25',
  'completeness_score': '',
  'contamination_score': '',
  'country': 'United Kingdom',
  'cultivar': '',
  'culture_collection': '',
  'datahub': 'dcc_grusin',
  'depth': '',
  'description': 'COG_ACCESSION:COG-UK/QEUH-3DF09F3/SANG:220505_A01545_0273_AH3GCFDRX2 COG_BASIC_QC:PASS COG_HIGH_QC:PASS COG_NOTE:Sample metadata and QC flags may have been updated since deposition in public databases. COG-UK recommends users refer to data.covid19.climb.ac.uk for latest metadata and QC tables before conducting analysis.',
  'dev_stage': '',
  'disease': '',
  'ecotype': '',
  'elevation': '',
  'environment_biome': '',
  'environment_feature': '',
  'environment_material': '',
  'environmental_medium': '',
  'environmental_sample': '',
  'experiment_accession': '',
  'experimental_factor': '',
  'first_created': '2022-05-14',
  'first_public': '2022-05-14',
  'generated_aspera': '',
  'generated_bytes': '',
  'generated_format': '',
  'generated_ftp': '',
  'generated_galaxy': '',
  'generated_md5': '',
  'germline': '',
  'host': 'Homo sapiens',
  'host_body_site': '',
  'host_genotype': '',
  'host_gravidity': '',
  'host_growth_conditions': '',
  'host_phenotype': '',
  'host_scientific_name': 'Homo sapiens',
  'host_sex': '',
  'host_status': '',
  'host_tax_id': '9606',
  'identified_by': '',
  'investigation_type': '',
  'isolate': '',
  'isolation_source': '',
  'last_updated': '2022-05-14',
  'lat': '',
  'local_environmental_context': '',
  'location': '',
  'location_end': '',
  'location_start': '',
  'lon': '',
  'marine_region': '',
  'mating_type': '',
  'ncbi_reporting_standard': '',
  'ph': '',
  'pipeline_name': '',
  'pipeline_version': '',
  'project_name': 'COVID-19 Genomics UK (COG-UK) consortium',
  'protocol_label': '',
  'pubmed_id': '',
  'reference_data_set_name': '',
  'reference_data_set_version': '',
  'reference_genome': '',
  'related_analysis_accession': '',
  'run_accession': 'ERR9720937',
  'salinity': '',
  'sample_accession': 'SAMEA14378297',
  'sample_alias': 'COG-UK/QEUH-3DF09F3',
  'sample_capture_status': 'active surveillance in response to outbreak',
  'sample_collection': '',
  'sample_description': 'Samples prepared at Lighthouse Lab in Glasgow by Harper VanSteenhouse, Yumi Kasai, David Gray, Carol Clugston, Anna Dominiczak and Alex Alderton, Roberto Amato, Jeffrey Barrett, Sonia Goncalves, Ewan Harrison, David K. Jackson, Ian Johnston, Dominic Kwiatkowski, Cordelia Langford, John Sillitoe on behalf of the Wellcome Sanger Institute COVID-19 Surveillance Team (https://www.sanger.ac.uk/covid-team)',
  'sample_material': '',
  'sample_title': 'COG-UK/QEUH-3DF09F3',
  'sampling_campaign': '',
  'sampling_platform': '',
  'sampling_site': '',
  'scientific_name': 'Severe acute respiratory syndrome coronavirus 2',
  'secondary_project': '',
  'secondary_sample_accession': 'ERS11972671',
  'secondary_study_accession': 'ERP121228',
  'sequencing_method': '',
  'serotype': '',
  'serovar': '',
  'sex': '',
  'specimen_voucher': '',
  'status': 'public',
  'strain': '',
  'study_accession': 'PRJEB37886',
  'study_alias': 'ena-STUDY-COVID-19 Genomics UK Consortium-18-04-2020-13:10:01:615-410',
  'study_title': 'COVID-19 Genomics UK (COG-UK) consortium',
  'sub_species': '',
  'sub_strain': '',
  'submission_accession': 'ERA14121881',
  'submission_tool': '',
  'submitted_aspera': 'fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10043917/file.fasta.gz;fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10043917/file.list.gz',
  'submitted_bytes': '8863;34',
  'submitted_format': 'FASTA;CHROMOSOME_LIST',
  'submitted_ftp': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043917/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043917/file.list.gz',
  'submitted_galaxy': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043917/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043917/file.list.gz',
  'submitted_host_sex': '',
  'submitted_md5': '16bbb52974c64e1d840752de4aed1f51;5aaa584c7ab0743f52b7c029ada4bdd5',
  'tag': 'datahub;covid19;pathogen;pathogen:virus;pathogen:priority',
  'target_gene': '',
  'tax_id': '2697049',
  'tax_lineage': '1;10239;2559587;2732396;2732408;2732506;76804;2499399;11118;2501931;694002;2509511;3418604;2697049',
  'taxonomic_classification': '',
  'taxonomic_identity_marker': '',
  'temperature': '',
  'tissue_lib': '',
  'tissue_type': '',
  'variety': ''},
 {'analysis_accession': 'ERZ10043961',
  'age': '',
  'altitude': '',
  'analysis_alias': 'webin-genome-hCoV-19.Scotland.QEUH-3DF0AD2.2022',
  'analysis_code_repository': '',
  'analysis_date': '',
  'analysis_description': '',
  'analysis_protocol': '',
  'analysis_title': 'Genome assembly: hCoV-19.Scotland.QEUH-3DF0AD2.2022',
  'analysis_type': 'SEQUENCE_ASSEMBLY',
  'assembly_quality': '',
  'assembly_software': '',
  'assembly_type': 'COVID-19 outbreak',
  'binning_software': '',
  'bio_material': '',
  'broad_scale_environmental_context': '',
  'broker_name': '',
  'cell_line': '',
  'cell_type': '',
  'center_name': 'Wellcome Sanger Institute;SC',
  'checklist': 'ERC000033',
  'collected_by': '',
  'collection_date': '2022-04-27',
  'collection_date_end': '2022-04-27',
  'collection_date_start': '2022-04-26',
  'completeness_score': '',
  'contamination_score': '',
  'country': 'United Kingdom',
  'cultivar': '',
  'culture_collection': '',
  'datahub': 'dcc_grusin',
  'depth': '',
  'description': 'COG_ACCESSION:COG-UK/QEUH-3DF0AD2/SANG:220505_A01545_0273_AH3GCFDRX2 COG_BASIC_QC:PASS COG_HIGH_QC:PASS COG_NOTE:Sample metadata and QC flags may have been updated since deposition in public databases. COG-UK recommends users refer to data.covid19.climb.ac.uk for latest metadata and QC tables before conducting analysis.',
  'dev_stage': '',
  'disease': '',
  'ecotype': '',
  'elevation': '',
  'environment_biome': '',
  'environment_feature': '',
  'environment_material': '',
  'environmental_medium': '',
  'environmental_sample': '',
  'experiment_accession': '',
  'experimental_factor': '',
  'first_created': '2022-05-14',
  'first_public': '2022-05-14',
  'generated_aspera': '',
  'generated_bytes': '',
  'generated_format': '',
  'generated_ftp': '',
  'generated_galaxy': '',
  'generated_md5': '',
  'germline': '',
  'host': 'Homo sapiens',
  'host_body_site': '',
  'host_genotype': '',
  'host_gravidity': '',
  'host_growth_conditions': '',
  'host_phenotype': '',
  'host_scientific_name': 'Homo sapiens',
  'host_sex': '',
  'host_status': '',
  'host_tax_id': '9606',
  'identified_by': '',
  'investigation_type': '',
  'isolate': '',
  'isolation_source': '',
  'last_updated': '2022-05-14',
  'lat': '',
  'local_environmental_context': '',
  'location': '',
  'location_end': '',
  'location_start': '',
  'lon': '',
  'marine_region': '',
  'mating_type': '',
  'ncbi_reporting_standard': '',
  'ph': '',
  'pipeline_name': '',
  'pipeline_version': '',
  'project_name': 'COVID-19 Genomics UK (COG-UK) consortium',
  'protocol_label': '',
  'pubmed_id': '',
  'reference_data_set_name': '',
  'reference_data_set_version': '',
  'reference_genome': '',
  'related_analysis_accession': '',
  'run_accession': 'ERR9720830',
  'salinity': '',
  'sample_accession': 'SAMEA14378191',
  'sample_alias': 'COG-UK/QEUH-3DF0AD2',
  'sample_capture_status': 'active surveillance in response to outbreak',
  'sample_collection': '',
  'sample_description': 'Samples prepared at Lighthouse Lab in Glasgow by Harper VanSteenhouse, Yumi Kasai, David Gray, Carol Clugston, Anna Dominiczak and Alex Alderton, Roberto Amato, Jeffrey Barrett, Sonia Goncalves, Ewan Harrison, David K. Jackson, Ian Johnston, Dominic Kwiatkowski, Cordelia Langford, John Sillitoe on behalf of the Wellcome Sanger Institute COVID-19 Surveillance Team (https://www.sanger.ac.uk/covid-team)',
  'sample_material': '',
  'sample_title': 'COG-UK/QEUH-3DF0AD2',
  'sampling_campaign': '',
  'sampling_platform': '',
  'sampling_site': '',
  'scientific_name': 'Severe acute respiratory syndrome coronavirus 2',
  'secondary_project': '',
  'secondary_sample_accession': 'ERS11972565',
  'secondary_study_accession': 'ERP121228',
  'sequencing_method': '',
  'serotype': '',
  'serovar': '',
  'sex': '',
  'specimen_voucher': '',
  'status': 'public',
  'strain': '',
  'study_accession': 'PRJEB37886',
  'study_alias': 'ena-STUDY-COVID-19 Genomics UK Consortium-18-04-2020-13:10:01:615-410',
  'study_title': 'COVID-19 Genomics UK (COG-UK) consortium',
  'sub_species': '',
  'sub_strain': '',
  'submission_accession': 'ERA14121925',
  'submission_tool': '',
  'submitted_aspera': 'fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10043961/file.fasta.gz;fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10043961/file.list.gz',
  'submitted_bytes': '8865;34',
  'submitted_format': 'FASTA;CHROMOSOME_LIST',
  'submitted_ftp': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043961/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043961/file.list.gz',
  'submitted_galaxy': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043961/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043961/file.list.gz',
  'submitted_host_sex': '',
  'submitted_md5': 'dca54fc127dfbe95ed94e38c743c2fe3;5aaa584c7ab0743f52b7c029ada4bdd5',
  'tag': 'datahub;covid19;pathogen;pathogen:virus;pathogen:priority',
  'target_gene': '',
  'tax_id': '2697049',
  'tax_lineage': '1;10239;2559587;2732396;2732408;2732506;76804;2499399;11118;2501931;694002;2509511;3418604;2697049',
  'taxonomic_classification': '',
  'taxonomic_identity_marker': '',
  'temperature': '',
  'tissue_lib': '',
  'tissue_type': '',
  'variety': ''},
 {'analysis_accession': 'ERZ10044095',
  'age': '',
  'altitude': '',
  'analysis_alias': 'webin-genome-hCoV-19.Scotland.QEUH-3DF0C72.2022',
  'analysis_code_repository': '',
  'analysis_date': '',
  'analysis_description': '',
  'analysis_protocol': '',
  'analysis_title': 'Genome assembly: hCoV-19.Scotland.QEUH-3DF0C72.2022',
  'analysis_type': 'SEQUENCE_ASSEMBLY',
  'assembly_quality': '',
  'assembly_software': '',
  'assembly_type': 'COVID-19 outbreak',
  'binning_software': '',
  'bio_material': '',
  'broad_scale_environmental_context': '',
  'broker_name': '',
  'cell_line': '',
  'cell_type': '',
  'center_name': 'Wellcome Sanger Institute;SC',
  'checklist': 'ERC000033',
  'collected_by': '',
  'collection_date': '2022-04-26',
  'collection_date_end': '2022-04-26',
  'collection_date_start': '2022-04-25',
  'completeness_score': '',
  'contamination_score': '',
  'country': 'United Kingdom',
  'cultivar': '',
  'culture_collection': '',
  'datahub': 'dcc_grusin',
  'depth': '',
  'description': 'COG_ACCESSION:COG-UK/QEUH-3DF0C72/SANG:220505_A01545_0273_AH3GCFDRX2 COG_BASIC_QC:PASS COG_HIGH_QC:PASS COG_NOTE:Sample metadata and QC flags may have been updated since deposition in public databases. COG-UK recommends users refer to data.covid19.climb.ac.uk for latest metadata and QC tables before conducting analysis.',
  'dev_stage': '',
  'disease': '',
  'ecotype': '',
  'elevation': '',
  'environment_biome': '',
  'environment_feature': '',
  'environment_material': '',
  'environmental_medium': '',
  'environmental_sample': '',
  'experiment_accession': '',
  'experimental_factor': '',
  'first_created': '2022-05-14',
  'first_public': '2022-05-14',
  'generated_aspera': '',
  'generated_bytes': '',
  'generated_format': '',
  'generated_ftp': '',
  'generated_galaxy': '',
  'generated_md5': '',
  'germline': '',
  'host': 'Homo sapiens',
  'host_body_site': '',
  'host_genotype': '',
  'host_gravidity': '',
  'host_growth_conditions': '',
  'host_phenotype': '',
  'host_scientific_name': 'Homo sapiens',
  'host_sex': '',
  'host_status': '',
  'host_tax_id': '9606',
  'identified_by': '',
  'investigation_type': '',
  'isolate': '',
  'isolation_source': '',
  'last_updated': '2022-05-14',
  'lat': '',
  'local_environmental_context': '',
  'location': '',
  'location_end': '',
  'location_start': '',
  'lon': '',
  'marine_region': '',
  'mating_type': '',
  'ncbi_reporting_standard': '',
  'ph': '',
  'pipeline_name': '',
  'pipeline_version': '',
  'project_name': 'COVID-19 Genomics UK (COG-UK) consortium',
  'protocol_label': '',
  'pubmed_id': '',
  'reference_data_set_name': '',
  'reference_data_set_version': '',
  'reference_genome': '',
  'related_analysis_accession': '',
  'run_accession': 'ERR9720923',
  'salinity': '',
  'sample_accession': 'SAMEA14378283',
  'sample_alias': 'COG-UK/QEUH-3DF0C72',
  'sample_capture_status': 'active surveillance in response to outbreak',
  'sample_collection': '',
  'sample_description': 'Samples prepared at Lighthouse Lab in Glasgow by Harper VanSteenhouse, Yumi Kasai, David Gray, Carol Clugston, Anna Dominiczak and Alex Alderton, Roberto Amato, Jeffrey Barrett, Sonia Goncalves, Ewan Harrison, David K. Jackson, Ian Johnston, Dominic Kwiatkowski, Cordelia Langford, John Sillitoe on behalf of the Wellcome Sanger Institute COVID-19 Surveillance Team (https://www.sanger.ac.uk/covid-team)',
  'sample_material': '',
  'sample_title': 'COG-UK/QEUH-3DF0C72',
  'sampling_campaign': '',
  'sampling_platform': '',
  'sampling_site': '',
  'scientific_name': 'Severe acute respiratory syndrome coronavirus 2',
  'secondary_project': '',
  'secondary_sample_accession': 'ERS11972657',
  'secondary_study_accession': 'ERP121228',
  'sequencing_method': '',
  'serotype': '',
  'serovar': '',
  'sex': '',
  'specimen_voucher': '',
  'status': 'public',
  'strain': '',
  'study_accession': 'PRJEB37886',
  'study_alias': 'ena-STUDY-COVID-19 Genomics UK Consortium-18-04-2020-13:10:01:615-410',
  'study_title': 'COVID-19 Genomics UK (COG-UK) consortium',
  'sub_species': '',
  'sub_strain': '',
  'submission_accession': 'ERA14122059',
  'submission_tool': '',
  'submitted_aspera': 'fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10044095/file.fasta.gz;fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10044095/file.list.gz',
  'submitted_bytes': '8862;34',
  'submitted_format': 'FASTA;CHROMOSOME_LIST',
  'submitted_ftp': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10044095/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10044095/file.list.gz',
  'submitted_galaxy': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10044095/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10044095/file.list.gz',
  'submitted_host_sex': '',
  'submitted_md5': '7c3f6813d889ede294b524960d315d52;5aaa584c7ab0743f52b7c029ada4bdd5',
  'tag': 'datahub;covid19;pathogen;pathogen:virus;pathogen:priority',
  'target_gene': '',
  'tax_id': '2697049',

In [35]:
ENAAnalysisFields.all_values_as_str()

'age,altitude,analysis_accession,analysis_alias,analysis_code_repository,analysis_date,analysis_description,analysis_protocol,analysis_title,analysis_type,assembly_quality,assembly_software,assembly_type,binning_software,bio_material,broad_scale_environmental_context,broker_name,cell_line,cell_type,center_name,checklist,collected_by,collection_date,collection_date_end,collection_date_start,completeness_score,contamination_score,country,cultivar,culture_collection,datahub,depth,description,dev_stage,disease,ecotype,elevation,environment_biome,environment_feature,environment_material,environmental_medium,environmental_sample,experiment_accession,experimental_factor,first_created,first_public,generated_aspera,generated_bytes,generated_format,generated_ftp,generated_galaxy,generated_md5,germline,host,host_body_site,host_genotype,host_gravidity,host_growth_conditions,host_phenotype,host_scientific_name,host_sex,host_status,host_tax_id,identified_by,investigation_type,isolate,isolation_source,last_updated,lat,local_environmental_context,location,location_end,location_start,lon,marine_region,mating_type,ncbi_reporting_standard,ph,pipeline_name,pipeline_version,project_name,protocol_label,pubmed_id,reference_data_set_name,reference_data_set_version,reference_genome,related_analysis_accession,run_accession,salinity,sample_accession,sample_alias,sample_capture_status,sample_collection,sample_description,sample_material,sample_title,sampling_campaign,sampling_platform,sampling_site,scientific_name,secondary_project,secondary_sample_accession,secondary_study_accession,sequencing_method,serotype,serovar,sex,specimen_voucher,status,strain,study_accession,study_alias,study_title,sub_species,sub_strain,submission_accession,submission_tool,submitted_aspera,submitted_bytes,submitted_format,submitted_ftp,submitted_galaxy,submitted_host_sex,submitted_md5,tag,target_gene,tax_id,tax_lineage,taxonomic_classification,taxonomic_identity_marker,temperature,tissue_lib,tissue_type,variety'