In [1]:
%load_ext autoreload
%autoreload 2
# for dev
# import logging
# logging.basicConfig(level=logging.INFO)

# Demo: Get all MGnify analyses for a given Study

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ebi-metagenomics/mgnipy/blob/main/docs/tutorial/demo-mgnify-tomatoes.ipynb)

In [2]:
# uncomment below if colab
#!pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple mgnipy
#!pip install asyncio

In this tutorial we demonstrate how mgnipy can be used to get all the analyses metadata for a given study [MGYS00010442](https://www.ebi.ac.uk/metagenomics/v6-early-data-release/studies/MGYS00010442/overview)

In [ ]:
from mgnipy import MGnipy
import asyncio # optional, for async requests
import pandas as pd # optional

Choose your entry resource proxy

In [20]:
# init
MG = MGnipy(
    # configuration
)

# helper
MG.list_resources()

['analyses',
 'assemblies',
 'genomes',
 'publications',
 'samples',
 'studies',
 'runs',
 'miscellaneous',
 'biomes']

## Getting the study metadata

Since we know our MGnify study ID we can provide as accession

In [5]:
study = MG.studies(accession="MGYS00010442")
print(study)

MGnifier instance for resource: studies
I.e., mgnipy.V2.proxies.Studies
----------------------------------------
Base URL: https://www.ebi.ac.uk/
Parameters: {'accession': 'MGYS00010442'}
Endpoint module: mgnipy.emgapi_v2_client.api.studies.get_mgnify_study
Example request URL: https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442
Returns paginated results: False

if you're happy with that then let's actually retrieve the study info

In [21]:
await study.aget()
# or 
#study.get()

we can take a look at what was returned in numerous view options
- `.results` response parsed as dict 
- `.to_list()` put the records as dicts in one list
- `.to_df()` as pandas dataframe
- `.to_polars()` as polars dataframe
- `.to_json()` as json

In [26]:
study.to_df()

,accession,ena_accessions,title,biome,updated_at,downloads,metadata,first_accession
0,MGYS00010442,"[PRJEB37289, ERP120598]",TKI,"{'biome_name': 'Digestive system', 'lineage': ...",2026-03-31T18:15:42.471000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",{},ERP120598

## Option 1: Find analyses by study id
without getting sample and run info

In [ ]:
study_analyses = study.analyses
# instead get ~10 at a time instead of default ~25
study_analyses = study_analyses.page_size(10)
# preview
study_analyses.explain()

Planning the API call with params:
{'accession': 'MGYS00010442', 'page_size': 10}
Total pages to retrieve: 7
Total records to retrieve: 63
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/analyses/?page_size=10&page=1
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/analyses/?page_size=10&page=2
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/analyses/?page_size=10&page=3
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/analyses/?page_size=10&page=4
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/analyses/?page_size=10&page=5
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/analyses/?page_size=10&page=6
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/analyses/?page_size=10&page=7

alright we want this study's analyses

In [107]:
await study_analyses.aget()

Retrieving pages: 100%|██████████| 7/7 [00:00<00:00,  8.18it/s]

In [110]:
study_analyses_details = await study_analyses.acollect_details(
    fetch=True, #not lazily
    by_accession=True # else as a list 
)

Processing:   2%|▏         | 1/63 [00:00<00:07,  8.26it/s]

Planning the API call with params:
{'accession': 'MGYA01021253'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021239'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021271'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021289'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021240'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021254'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021272'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021290'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021255'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021241'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021234'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:  19%|█▉        | 12/63 [00:00<00:01, 34.52it/s]

Planning the API call with params:
{'accession': 'MGYA01021268'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021287'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021236'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021288'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021251'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021269'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021270'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021238'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021252'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021260'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:  37%|███▋      | 23/63 [00:00<00:00, 44.58it/s]

Planning the API call with params:
{'accession': 'MGYA01021261'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021278'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021262'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021279'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021263'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021280'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021281'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021244'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021265'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021267'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021246'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:  54%|█████▍    | 34/63 [00:00<00:00, 48.42it/s]

Planning the API call with params:
{'accession': 'MGYA01021249'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021266'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021237'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021245'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021250'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021235'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021233'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021247'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021258'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021259'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021294'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021276'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:  75%|███████▍  | 47/63 [00:01<00:00, 52.87it/s]

Planning the API call with params:
{'accession': 'MGYA01021285'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021283'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021295'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021284'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021286'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021277'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021273'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021291'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021274'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021242'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021275'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021256'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:  94%|█████████▎| 59/63 [00:01<00:00, 53.75it/s]

Planning the API call with params:
{'accession': 'MGYA01021292'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021243'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021257'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021293'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021282'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021264'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'MGYA01021248'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 63/63 [00:01<00:00, 47.73it/s]

In [121]:
df_study_analyses_details = pd.concat([study_analyses_details[x].to_df() for x in study_analyses_details])

df_study_analyses_details.head()

,experiment_type,study_accession,accession,run,sample,assembly,pipeline_version,read_run,quality_control_summary,downloads,results_dir,metadata
0,Amplicon,MGYS00010442,MGYA01021253,"{'experiment_type': 'Amplicon', 'accession': '...","{'accession': 'SAMEA8156337', 'ena_accessions'...",None,V6,"[{'experiment_type': 'Amplicon', 'accession': ...",{'sequencing': 'paired end (251 cycles + 251 c...,"[{'file_type': 'html', 'download_type': 'Quali...",https://ftp.ebi.ac.uk/pub/databases/metagenomi...,"{'marker_gene_summary': {'asv': {}, 'closed_re..."
0,Amplicon,MGYS00010442,MGYA01021239,"{'experiment_type': 'Amplicon', 'accession': '...","{'accession': 'SAMEA8156364', 'ena_accessions'...",None,V6,"[{'experiment_type': 'Amplicon', 'accession': ...",{'sequencing': 'paired end (251 cycles + 251 c...,"[{'file_type': 'html', 'download_type': 'Quali...",https://ftp.ebi.ac.uk/pub/databases/metagenomi...,{'marker_gene_summary': {'asv': {'amplified_re...
0,Amplicon,MGYS00010442,MGYA01021271,"{'experiment_type': 'Amplicon', 'accession': '...","{'accession': 'SAMEA8156385', 'ena_accessions'...",None,V6,"[{'experiment_type': 'Amplicon', 'accession': ...",{'sequencing': 'paired end (251 cycles + 251 c...,"[{'file_type': 'html', 'download_type': 'Quali...",https://ftp.ebi.ac.uk/pub/databases/metagenomi...,{'marker_gene_summary': {'asv': {'amplified_re...
0,Amplicon,MGYS00010442,MGYA01021289,"{'experiment_type': 'Amplicon', 'accession': '...","{'accession': 'SAMEA8156378', 'ena_accessions'...",None,V6,"[{'experiment_type': 'Amplicon', 'accession': ...",{'sequencing': 'paired end (251 cycles + 251 c...,"[{'file_type': 'html', 'download_type': 'Quali...",https://ftp.ebi.ac.uk/pub/databases/metagenomi...,{'marker_gene_summary': {'asv': {'amplified_re...
0,Amplicon,MGYS00010442,MGYA01021240,"{'experiment_type': 'Amplicon', 'accession': '...","{'accession': 'SAMEA8156366', 'ena_accessions'...",None,V6,"[{'experiment_type': 'Amplicon', 'accession': ...",{'sequencing': 'paired end (251 cycles + 251 c...,"[{'file_type': 'html', 'download_type': 'Quali...",https://ftp.ebi.ac.uk/pub/databases/metagenomi...,{'marker_gene_summary': {'asv': {'amplified_re...

## Optional: get sample and runs metadata too

### Getting the sample metadata

From our given study we can access their samples metadata by traversing their relationship?

We can preview the number of associated sample records to retrieve and the request urls to do that by using `.explain()`

In [46]:
study_samples = study.samples
# instead get ~10 at a time instead of default ~25
study_samples = study_samples.page_size(10)
# preview
study_samples.explain()

Planning the API call with params:
{'accession': 'MGYS00010442', 'page_size': 10}
Total pages to retrieve: 7
Total records to retrieve: 63
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/samples/?page_size=10&page=1
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/samples/?page_size=10&page=2
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/samples/?page_size=10&page=3
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/samples/?page_size=10&page=4
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/samples/?page_size=10&page=5
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/samples/?page_size=10&page=6
https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00010442/samples/?page_size=10&page=7

further we could take a look at the first page using `.preview()`

In [47]:
study_samples.preview()

,accession,ena_accessions,sample_title,biome,updated_at,metadata
0,SAMEA8156338,"[ERS5843109, SAMEA8156338]",2019_0011_00_SB504SB706,None,2026-03-31T15:57:05.490000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
1,SAMEA8156341,"[ERS5843112, SAMEA8156341]",2019_0011_00_SB507SB709,None,2026-03-31T15:57:05.657000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
2,SAMEA8156345,"[ERS5843116, SAMEA8156345]",2019_0011_00_SB504SB707,None,2026-03-31T15:57:05.822000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
3,SAMEA8156347,"[ERS5843118, SAMEA8156347]",2019_0011_00_SB506SB709,None,2026-03-31T15:57:05.984000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
4,SAMEA8156348,"[ERS5843119, SAMEA8156348]",2019_0011_00_SB507SB710,None,2026-03-31T15:57:06.144000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
5,SAMEA8156349,"[ERS5843120, SAMEA8156349]",2019_0011_00_SB508SB711,None,2026-03-31T15:57:06.307000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
6,SAMEA8156353,"[ERS5843124, SAMEA8156353]",2019_0011_00_SB504SB708,None,2026-03-31T15:57:06.477000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
7,SAMEA8156355,"[SAMEA8156355, ERS5843126]",2019_0011_00_SB506SB710,None,2026-03-31T15:57:06.643000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
8,SAMEA8156356,"[ERS5843127, SAMEA8156356]",2019_0011_00_SB507SB711,None,2026-03-31T15:57:06.790000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
9,SAMEA8156357,"[SAMEA8156357, ERS5843128]",2019_0011_00_SB501SB706,None,2026-03-31T15:57:06.958000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."

again if we are happy to proceed, then use aget() or get() to retrieve all samples metadata. 

for more control you can retrive page by page using .apage() or .page()

In [ ]:
# for example getting page 5 of sample records for our given study
await study_samples.apage(5)
print("Num pages in results: ", len(study_samples.results)) 

# now lets go ahead and get all 
await study_samples.aget()
print("Num pages in results: ", len(study_samples.results))

2

Retrieving pages: 100%|██████████| 7/7 [00:00<00:00, 61.71it/s]

7

**Note:** At first there were 2 pages despite us ony getting one page e.g. 5, because the previewed page 1 previously was cached as to not unnecessarily rerun the same request. 

Now let's take a look at the brief sample metadata.

In [50]:
study_samples.to_df().sample(5)

,accession,ena_accessions,sample_title,biome,updated_at,metadata
19,SAMEA8156361,"[ERS5843132, SAMEA8156361]",2019_0011_00_SB505SB710,None,2026-03-31T15:57:13.179000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
5,SAMEA8156349,"[ERS5843120, SAMEA8156349]",2019_0011_00_SB508SB711,None,2026-03-31T15:57:06.307000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
42,SAMEA8156365,"[ERS5843136, SAMEA8156365]",2019_0011_00_SB501SB707,None,2026-03-31T15:57:10.093000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
29,SAMEA8156381,"[ERS5843152, SAMEA8156381]",2019_0011_00_SB501SB709,None,2026-03-31T15:57:14.247000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."
46,SAMEA8156377,"[SAMEA8156377, ERS5843148]",2019_0011_00_SB505SB712,None,2026-03-31T15:57:10.697000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's..."

We can get more details about each sample, which includes the option to traverse their relationships to associated runs

In [ ]:
study_samples_details = await study_samples.acollect_details(
    fetch=True, #not lazily
    by_accession=True # else as a list 
)

Processing:   2%|▏         | 1/63 [00:00<00:07,  7.89it/s]

Planning the API call with params:
{'accession': 'SAMEA8156338'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156341'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156345'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156347'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156348'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156349'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156353'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156355'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156356'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156357'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:  17%|█▋        | 11/63 [00:00<00:01, 35.16it/s]

Planning the API call with params:
{'accession': 'SAMEA8156393'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156394'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156397'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156343'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156339'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156342'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156350'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156352'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156354'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156361'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:  33%|███▎      | 21/63 [00:00<00:01, 41.38it/s]

Planning the API call with params:
{'accession': 'SAMEA8156395'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156396'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156399'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156363'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156367'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156368'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156370'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156372'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156378'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156381'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:  49%|████▉     | 31/63 [00:00<00:00, 43.72it/s]

Planning the API call with params:
{'accession': 'SAMEA8156387'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156389'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156391'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156384'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156386'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156388'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156398'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156340'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156344'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156346'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:  65%|██████▌   | 41/63 [00:01<00:00, 44.64it/s]

Planning the API call with params:
{'accession': 'SAMEA8156351'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156337'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156365'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156369'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156371'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156376'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156377'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156379'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156380'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156382'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:  83%|████████▎ | 52/63 [00:01<00:00, 46.36it/s]

Planning the API call with params:
{'accession': 'SAMEA8156385'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156390'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156392'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156358'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156359'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156360'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156362'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156364'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156366'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156373'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:  90%|█████████ | 57/63 [00:01<00:00, 36.77it/s]

Planning the API call with params:
{'accession': 'SAMEA8156374'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156375'}
Total pages to retrieve: 1
Total records to retrieve: 1
Planning the API call with params:
{'accession': 'SAMEA8156383'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 63/63 [00:01<00:00, 37.34it/s]

In [59]:
study_samples_details['SAMEA8156338'].to_df()

,accession,ena_accessions,sample_title,biome,updated_at,metadata,studies
0,SAMEA8156338,"[ERS5843109, SAMEA8156338]",2019_0011_00_SB504SB706,None,2026-03-31T15:57:05.490000+00:00,"{'ph': '', 'age': '', 'lat': '', 'lon': '', 's...","[{'accession': 'MGYS00010442', 'ena_accessions..."

### And now traversing their runs metadata

In [73]:
# init the runs proxy for each sample
sample_run_lists = {k: study_samples_details[k].runs for k in study_samples_details}
# now we can get the details for each run proxy

**Note:** We cannot complete aget() or get() at init. e.g.
```
>>> sample_run_lists = {k: await study_samples_details[k].runs.aget() for k in study_samples_details}
"AssertionError: Please run .dry_run() or .preview() or .explain()before deciding to collect metadata."
```
This is because there is a safety intermediary step where the built requests must be previewed in some way before retriving all.

In [77]:
# now we can get the details for each run proxy
for sample in sample_run_lists:
    print(f"Sample: {sample}")
    sample_run_lists[sample].explain()
    await sample_run_lists[sample].aget()
    print(f"Runs for sample {sample}: {len(sample_run_lists[sample].results)}")

Sample: SAMEA8156338
Planning the API call with params:
{'accession': 'SAMEA8156338'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156338/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]

Runs for sample SAMEA8156338: 1
Sample: SAMEA8156341
Planning the API call with params:
{'accession': 'SAMEA8156341'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156341/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]

Runs for sample SAMEA8156341: 1
Sample: SAMEA8156345
Planning the API call with params:
{'accession': 'SAMEA8156345'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156345/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]

Runs for sample SAMEA8156345: 1
Sample: SAMEA8156347
Planning the API call with params:
{'accession': 'SAMEA8156347'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156347/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]

Runs for sample SAMEA8156347: 1
Sample: SAMEA8156348
Planning the API call with params:
{'accession': 'SAMEA8156348'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156348/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]

Runs for sample SAMEA8156348: 1
Sample: SAMEA8156349
Planning the API call with params:
{'accession': 'SAMEA8156349'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156349/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]

Runs for sample SAMEA8156349: 1
Sample: SAMEA8156353
Planning the API call with params:
{'accession': 'SAMEA8156353'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156353/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]

Runs for sample SAMEA8156353: 1
Sample: SAMEA8156355
Planning the API call with params:
{'accession': 'SAMEA8156355'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156355/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]

Runs for sample SAMEA8156355: 1
Sample: SAMEA8156356
Planning the API call with params:
{'accession': 'SAMEA8156356'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156356/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]

Runs for sample SAMEA8156356: 1
Sample: SAMEA8156357
Planning the API call with params:
{'accession': 'SAMEA8156357'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156357/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]

Runs for sample SAMEA8156357: 1
Sample: SAMEA8156393
Planning the API call with params:
{'accession': 'SAMEA8156393'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156393/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]

Runs for sample SAMEA8156393: 1
Sample: SAMEA8156394
Planning the API call with params:
{'accession': 'SAMEA8156394'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156394/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]

Runs for sample SAMEA8156394: 1
Sample: SAMEA8156397
Planning the API call with params:
{'accession': 'SAMEA8156397'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156397/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]

Runs for sample SAMEA8156397: 1
Sample: SAMEA8156343
Planning the API call with params:
{'accession': 'SAMEA8156343'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156343/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]

Runs for sample SAMEA8156343: 1
Sample: SAMEA8156339
Planning the API call with params:
{'accession': 'SAMEA8156339'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156339/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]

Runs for sample SAMEA8156339: 1
Sample: SAMEA8156342
Planning the API call with params:
{'accession': 'SAMEA8156342'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156342/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  2.82it/s]

Runs for sample SAMEA8156342: 1
Sample: SAMEA8156350
Planning the API call with params:
{'accession': 'SAMEA8156350'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156350/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]

Runs for sample SAMEA8156350: 1
Sample: SAMEA8156352
Planning the API call with params:
{'accession': 'SAMEA8156352'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156352/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]

Runs for sample SAMEA8156352: 1
Sample: SAMEA8156354
Planning the API call with params:
{'accession': 'SAMEA8156354'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156354/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]

Runs for sample SAMEA8156354: 1
Sample: SAMEA8156361
Planning the API call with params:
{'accession': 'SAMEA8156361'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156361/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]

Runs for sample SAMEA8156361: 1
Sample: SAMEA8156395
Planning the API call with params:
{'accession': 'SAMEA8156395'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156395/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]

Runs for sample SAMEA8156395: 1
Sample: SAMEA8156396
Planning the API call with params:
{'accession': 'SAMEA8156396'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156396/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]

Runs for sample SAMEA8156396: 1
Sample: SAMEA8156399
Planning the API call with params:
{'accession': 'SAMEA8156399'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156399/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]

Runs for sample SAMEA8156399: 1
Sample: SAMEA8156363
Planning the API call with params:
{'accession': 'SAMEA8156363'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156363/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]

Runs for sample SAMEA8156363: 1
Sample: SAMEA8156367
Planning the API call with params:
{'accession': 'SAMEA8156367'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156367/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]

Runs for sample SAMEA8156367: 1
Sample: SAMEA8156368
Planning the API call with params:
{'accession': 'SAMEA8156368'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156368/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]

Runs for sample SAMEA8156368: 1
Sample: SAMEA8156370
Planning the API call with params:
{'accession': 'SAMEA8156370'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156370/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]

Runs for sample SAMEA8156370: 1
Sample: SAMEA8156372
Planning the API call with params:
{'accession': 'SAMEA8156372'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156372/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]

Runs for sample SAMEA8156372: 1
Sample: SAMEA8156378
Planning the API call with params:
{'accession': 'SAMEA8156378'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156378/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]

Runs for sample SAMEA8156378: 1
Sample: SAMEA8156381
Planning the API call with params:
{'accession': 'SAMEA8156381'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156381/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]

Runs for sample SAMEA8156381: 1
Sample: SAMEA8156387
Planning the API call with params:
{'accession': 'SAMEA8156387'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156387/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]

Runs for sample SAMEA8156387: 1
Sample: SAMEA8156389
Planning the API call with params:
{'accession': 'SAMEA8156389'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156389/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]

Runs for sample SAMEA8156389: 1
Sample: SAMEA8156391
Planning the API call with params:
{'accession': 'SAMEA8156391'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156391/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]

Runs for sample SAMEA8156391: 1
Sample: SAMEA8156384
Planning the API call with params:
{'accession': 'SAMEA8156384'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156384/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]

Runs for sample SAMEA8156384: 1
Sample: SAMEA8156386
Planning the API call with params:
{'accession': 'SAMEA8156386'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156386/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]

Runs for sample SAMEA8156386: 1
Sample: SAMEA8156388
Planning the API call with params:
{'accession': 'SAMEA8156388'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156388/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]

Runs for sample SAMEA8156388: 1
Sample: SAMEA8156398
Planning the API call with params:
{'accession': 'SAMEA8156398'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156398/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]

Runs for sample SAMEA8156398: 1
Sample: SAMEA8156340
Planning the API call with params:
{'accession': 'SAMEA8156340'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156340/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]

Runs for sample SAMEA8156340: 1
Sample: SAMEA8156344
Planning the API call with params:
{'accession': 'SAMEA8156344'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156344/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]

Runs for sample SAMEA8156344: 1
Sample: SAMEA8156346
Planning the API call with params:
{'accession': 'SAMEA8156346'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156346/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]

Runs for sample SAMEA8156346: 1
Sample: SAMEA8156351
Planning the API call with params:
{'accession': 'SAMEA8156351'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156351/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]

Runs for sample SAMEA8156351: 1
Sample: SAMEA8156337
Planning the API call with params:
{'accession': 'SAMEA8156337'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156337/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]

Runs for sample SAMEA8156337: 1
Sample: SAMEA8156365
Planning the API call with params:
{'accession': 'SAMEA8156365'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156365/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]

Runs for sample SAMEA8156365: 1
Sample: SAMEA8156369
Planning the API call with params:
{'accession': 'SAMEA8156369'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156369/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]

Runs for sample SAMEA8156369: 1
Sample: SAMEA8156371
Planning the API call with params:
{'accession': 'SAMEA8156371'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156371/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]

Runs for sample SAMEA8156371: 1
Sample: SAMEA8156376
Planning the API call with params:
{'accession': 'SAMEA8156376'}

Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156376/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  3.46it/s]

Runs for sample SAMEA8156376: 1
Sample: SAMEA8156377
Planning the API call with params:
{'accession': 'SAMEA8156377'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156377/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]

Runs for sample SAMEA8156377: 1
Sample: SAMEA8156379
Planning the API call with params:
{'accession': 'SAMEA8156379'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156379/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]

Runs for sample SAMEA8156379: 1
Sample: SAMEA8156380
Planning the API call with params:
{'accession': 'SAMEA8156380'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156380/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]

Runs for sample SAMEA8156380: 1
Sample: SAMEA8156382
Planning the API call with params:
{'accession': 'SAMEA8156382'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156382/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]

Runs for sample SAMEA8156382: 1
Sample: SAMEA8156385
Planning the API call with params:
{'accession': 'SAMEA8156385'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156385/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]

Runs for sample SAMEA8156385: 1
Sample: SAMEA8156390
Planning the API call with params:
{'accession': 'SAMEA8156390'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156390/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]

Runs for sample SAMEA8156390: 1
Sample: SAMEA8156392
Planning the API call with params:
{'accession': 'SAMEA8156392'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156392/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]

Runs for sample SAMEA8156392: 1
Sample: SAMEA8156358
Planning the API call with params:
{'accession': 'SAMEA8156358'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156358/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]

Runs for sample SAMEA8156358: 1
Sample: SAMEA8156359
Planning the API call with params:
{'accession': 'SAMEA8156359'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156359/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]

Runs for sample SAMEA8156359: 1
Sample: SAMEA8156360
Planning the API call with params:
{'accession': 'SAMEA8156360'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156360/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]

Runs for sample SAMEA8156360: 1
Sample: SAMEA8156362
Planning the API call with params:
{'accession': 'SAMEA8156362'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156362/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]

Runs for sample SAMEA8156362: 1
Sample: SAMEA8156364
Planning the API call with params:
{'accession': 'SAMEA8156364'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156364/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.94it/s]

Runs for sample SAMEA8156364: 1
Sample: SAMEA8156366
Planning the API call with params:
{'accession': 'SAMEA8156366'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156366/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]

Runs for sample SAMEA8156366: 1
Sample: SAMEA8156373
Planning the API call with params:
{'accession': 'SAMEA8156373'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156373/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]

Runs for sample SAMEA8156373: 1
Sample: SAMEA8156374
Planning the API call with params:
{'accession': 'SAMEA8156374'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156374/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]

Runs for sample SAMEA8156374: 1
Sample: SAMEA8156375
Planning the API call with params:
{'accession': 'SAMEA8156375'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156375/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00,  9.91it/s]

Runs for sample SAMEA8156375: 1
Sample: SAMEA8156383
Planning the API call with params:
{'accession': 'SAMEA8156383'}
Total pages to retrieve: 1
Total records to retrieve: 1
https://www.ebi.ac.uk/metagenomics/api/v2/samples/SAMEA8156383/runs/?page=1

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]

Runs for sample SAMEA8156383: 1

In [86]:
runs_details = {
    sample: await sample_run_lists[sample].acollect_details(
        fetch=True, #not lazily
        #by_accession=True # else as a list 
    ) for sample in sample_run_lists
}

Processing: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]

Planning the API call with params:
{'accession': 'ERR5382939'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382942'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382945'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382947'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382948'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382949'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382953'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382955'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382956'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382958'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382994'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382995'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382998'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382938'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382940'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382943'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382950'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.84it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382952'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382954'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382962'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382996'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382997'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5383000'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382964'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382968'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.87it/s]
Processing: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]

Planning the API call with params:
{'accession': 'ERR5382969'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]

Planning the API call with params:
{'accession': 'ERR5382971'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382973'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382979'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.88it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382982'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382988'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382990'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382992'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382985'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382987'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382989'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382999'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382941'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382944'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.87it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382946'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382951'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382957'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382966'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382970'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382972'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382977'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382978'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382980'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382981'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382983'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382986'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382991'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382993'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382959'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382960'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382961'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382963'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382965'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382967'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382974'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382975'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382976'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382984'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]

we can take a look at the runs details

In [96]:
import pandas as pd
df_runs_details = pd.concat([runs_details[run][0].to_df() for run in runs_details])

df_runs_details.head()

,experiment_type,accession,instrument_model,instrument_platform,sample,study,sample_accession,study_accession
0,Amplicon,ERR5382939,None,None,"{'accession': 'SAMEA8156338', 'ena_accessions'...","{'accession': 'MGYS00010442', 'ena_accessions'...",SAMEA8156338,MGYS00010442
0,Amplicon,ERR5382942,None,None,"{'accession': 'SAMEA8156341', 'ena_accessions'...","{'accession': 'MGYS00010442', 'ena_accessions'...",SAMEA8156341,MGYS00010442
0,Amplicon,ERR5382945,None,None,"{'accession': 'SAMEA8156345', 'ena_accessions'...","{'accession': 'MGYS00010442', 'ena_accessions'...",SAMEA8156345,MGYS00010442
0,Amplicon,ERR5382947,None,None,"{'accession': 'SAMEA8156347', 'ena_accessions'...","{'accession': 'MGYS00010442', 'ena_accessions'...",SAMEA8156347,MGYS00010442
0,Amplicon,ERR5382948,None,None,"{'accession': 'SAMEA8156348', 'ena_accessions'...","{'accession': 'MGYS00010442', 'ena_accessions'...",SAMEA8156348,MGYS00010442

### And now traversing to analyses metadata

In [ ]:
# init 
run_analyses_list = {k: runs_details[k][0].analyses for k in runs_details}
# get analyses metadta for each run 
analyses_details = {
    run: await sample_run_lists[run].acollect_details(
        fetch=True, #not lazily
        #by_accession=True # else as a list 
    ) for run in run_analyses_list
}

Processing: 100%|██████████| 1/1 [00:00<00:00,  5.99it/s]

Planning the API call with params:
{'accession': 'ERR5382939'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382942'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382945'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382947'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382948'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382949'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382953'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382955'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382956'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
Processing: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]

Planning the API call with params:
{'accession': 'ERR5382958'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382994'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382995'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382998'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382938'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382940'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382943'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382950'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382952'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382954'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382962'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382996'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382997'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5383000'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382964'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382968'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382969'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382971'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382973'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382979'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382982'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  3.85it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382988'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  4.43it/s]
Processing: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]

Planning the API call with params:
{'accession': 'ERR5382990'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382992'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382985'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  6.02it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382987'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382989'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382999'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382941'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382944'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382946'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382951'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382957'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382966'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382970'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382972'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382977'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382978'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382980'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382981'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382983'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382986'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382991'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382993'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382959'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382960'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382961'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382963'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382965'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382967'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382974'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382975'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382976'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Planning the API call with params:
{'accession': 'ERR5382984'}
Total pages to retrieve: 1
Total records to retrieve: 1

Processing: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]

In [ ]:
df_analyses_details = pd.concat([analyses_details[a][0].to_df() for a in analyses_details])

df_analyses_details.head()

,experiment_type,accession,instrument_model,instrument_platform,sample,study,sample_accession,study_accession
0,Amplicon,ERR5382939,None,None,"{'accession': 'SAMEA8156338', 'ena_accessions'...","{'accession': 'MGYS00010442', 'ena_accessions'...",SAMEA8156338,MGYS00010442
0,Amplicon,ERR5382942,None,None,"{'accession': 'SAMEA8156341', 'ena_accessions'...","{'accession': 'MGYS00010442', 'ena_accessions'...",SAMEA8156341,MGYS00010442
0,Amplicon,ERR5382945,None,None,"{'accession': 'SAMEA8156345', 'ena_accessions'...","{'accession': 'MGYS00010442', 'ena_accessions'...",SAMEA8156345,MGYS00010442
0,Amplicon,ERR5382947,None,None,"{'accession': 'SAMEA8156347', 'ena_accessions'...","{'accession': 'MGYS00010442', 'ena_accessions'...",SAMEA8156347,MGYS00010442
0,Amplicon,ERR5382948,None,None,"{'accession': 'SAMEA8156348', 'ena_accessions'...","{'accession': 'MGYS00010442', 'ena_accessions'...",SAMEA8156348,MGYS00010442

# stop

In [ ]:
from mgnipy._shared_helpers.ena_helpers import get_analyses_accession_by_study_accession, ENAAnalysisFields

get_analyses_accession_by_study_accession(limit=10)

[{'analysis_accession': 'ERZ10043910',
  'age': '',
  'altitude': '',
  'analysis_alias': 'webin-genome-IMS-10150-CVDP-B352AEEB-9839-4FAC-A26',
  'analysis_code_repository': '',
  'analysis_date': '',
  'analysis_description': '',
  'analysis_protocol': '',
  'analysis_title': 'Genome assembly: IMS-10150-CVDP-B352AEEB-9839-4FAC-A26',
  'analysis_type': 'SEQUENCE_ASSEMBLY',
  'assembly_quality': '',
  'assembly_software': '',
  'assembly_type': 'COVID-19 outbreak',
  'binning_software': '',
  'bio_material': '',
  'broad_scale_environmental_context': '',
  'broker_name': 'RKI-OSEDA',
  'cell_line': '',
  'cell_type': '',
  'center_name': 'ROBERT KOCH INSTITUTE;RKI-OSEDA',
  'checklist': 'ERC000033',
  'collected_by': '',
  'collection_date': '2022-02-07',
  'collection_date_end': '2022-02-07',
  'collection_date_start': '2022-02-07',
  'completeness_score': '',
  'contamination_score': '',
  'country': 'Germany',
  'cultivar': '',
  'culture_collection': '',
  'datahub': '',
  'depth': '',
  'description': '',
  'dev_stage': '',
  'disease': '',
  'ecotype': '',
  'elevation': '',
  'environment_biome': '',
  'environment_feature': '',
  'environment_material': '',
  'environmental_medium': '',
  'environmental_sample': '',
  'experiment_accession': '',
  'experimental_factor': '',
  'first_created': '2022-05-14',
  'first_public': '2022-05-14',
  'generated_aspera': '',
  'generated_bytes': '',
  'generated_format': '',
  'generated_ftp': '',
  'generated_galaxy': '',
  'generated_md5': '',
  'germline': '',
  'host': 'Homo sapiens',
  'host_body_site': '',
  'host_genotype': '',
  'host_gravidity': '',
  'host_growth_conditions': '',
  'host_phenotype': '',
  'host_scientific_name': 'Homo sapiens',
  'host_sex': '',
  'host_status': '',
  'host_tax_id': '9606',
  'identified_by': '',
  'investigation_type': '',
  'isolate': '',
  'isolation_source': '',
  'last_updated': '2022-05-14',
  'lat': '',
  'local_environmental_context': '',
  'location': '',
  'location_end': '',
  'location_start': '',
  'lon': '',
  'marine_region': '',
  'mating_type': '',
  'ncbi_reporting_standard': '',
  'ph': '',
  'pipeline_name': '',
  'pipeline_version': '',
  'project_name': '',
  'protocol_label': '',
  'pubmed_id': '',
  'reference_data_set_name': '',
  'reference_data_set_version': '',
  'reference_genome': '',
  'related_analysis_accession': '',
  'run_accession': '',
  'salinity': '',
  'sample_accession': 'SAMEA13729043',
  'sample_alias': 'IMS-10150-CVDP-B352AEEB-9839-4FAC-A265-5774284FA609',
  'sample_capture_status': 'active surveillance in response to outbreak',
  'sample_collection': '',
  'sample_description': 'Molecular surveillance of SARS-CoV-2 in Germany',
  'sample_material': '',
  'sample_title': 'Molecular surveillance of SARS-CoV-2 in Germany',
  'sampling_campaign': '',
  'sampling_platform': '',
  'sampling_site': '',
  'scientific_name': 'Severe acute respiratory syndrome coronavirus 2',
  'secondary_project': '',
  'secondary_sample_accession': 'ERS11330658',
  'secondary_study_accession': 'ERP129098',
  'sequencing_method': '',
  'serotype': '',
  'serovar': '',
  'sex': '',
  'specimen_voucher': '',
  'status': 'public',
  'strain': '',
  'study_accession': 'PRJEB44987',
  'study_alias': 'ena-STUDY-Robert Koch Institute-16-05-2021-16:06:46:171-179',
  'study_title': 'The Robert Koch Institute provides molecular and epidemiological data for the molecular surveillance of SARS-CoV-2 in Germany. Quality control passed',
  'sub_species': '',
  'sub_strain': '',
  'submission_accession': 'ERA14121874',
  'submission_tool': '',
  'submitted_aspera': 'fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10043910/file.fasta.gz;fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10043910/file.list.gz',
  'submitted_bytes': '8855;34',
  'submitted_format': 'FASTA;CHROMOSOME_LIST',
  'submitted_ftp': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043910/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043910/file.list.gz',
  'submitted_galaxy': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043910/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043910/file.list.gz',
  'submitted_host_sex': '',
  'submitted_md5': 'bf29349e7b3628a62e64c765503fa6f1;5aaa584c7ab0743f52b7c029ada4bdd5',
  'tag': 'covid19;pathogen;pathogen:virus;pathogen:priority',
  'target_gene': '',
  'tax_id': '2697049',
  'tax_lineage': '1;10239;2559587;2732396;2732408;2732506;76804;2499399;11118;2501931;694002;2509511;3418604;2697049',
  'taxonomic_classification': '',
  'taxonomic_identity_marker': '',
  'temperature': '',
  'tissue_lib': '',
  'tissue_type': '',
  'variety': ''},
 {'analysis_accession': 'ERZ10043917',
  'age': '',
  'altitude': '',
  'analysis_alias': 'webin-genome-hCoV-19.Scotland.QEUH-3DF09F3.2022',
  'analysis_code_repository': '',
  'analysis_date': '',
  'analysis_description': '',
  'analysis_protocol': '',
  'analysis_title': 'Genome assembly: hCoV-19.Scotland.QEUH-3DF09F3.2022',
  'analysis_type': 'SEQUENCE_ASSEMBLY',
  'assembly_quality': '',
  'assembly_software': '',
  'assembly_type': 'COVID-19 outbreak',
  'binning_software': '',
  'bio_material': '',
  'broad_scale_environmental_context': '',
  'broker_name': '',
  'cell_line': '',
  'cell_type': '',
  'center_name': 'Wellcome Sanger Institute;SC',
  'checklist': 'ERC000033',
  'collected_by': '',
  'collection_date': '2022-04-26',
  'collection_date_end': '2022-04-26',
  'collection_date_start': '2022-04-25',
  'completeness_score': '',
  'contamination_score': '',
  'country': 'United Kingdom',
  'cultivar': '',
  'culture_collection': '',
  'datahub': 'dcc_grusin',
  'depth': '',
  'description': 'COG_ACCESSION:COG-UK/QEUH-3DF09F3/SANG:220505_A01545_0273_AH3GCFDRX2 COG_BASIC_QC:PASS COG_HIGH_QC:PASS COG_NOTE:Sample metadata and QC flags may have been updated since deposition in public databases. COG-UK recommends users refer to data.covid19.climb.ac.uk for latest metadata and QC tables before conducting analysis.',
  'dev_stage': '',
  'disease': '',
  'ecotype': '',
  'elevation': '',
  'environment_biome': '',
  'environment_feature': '',
  'environment_material': '',
  'environmental_medium': '',
  'environmental_sample': '',
  'experiment_accession': '',
  'experimental_factor': '',
  'first_created': '2022-05-14',
  'first_public': '2022-05-14',
  'generated_aspera': '',
  'generated_bytes': '',
  'generated_format': '',
  'generated_ftp': '',
  'generated_galaxy': '',
  'generated_md5': '',
  'germline': '',
  'host': 'Homo sapiens',
  'host_body_site': '',
  'host_genotype': '',
  'host_gravidity': '',
  'host_growth_conditions': '',
  'host_phenotype': '',
  'host_scientific_name': 'Homo sapiens',
  'host_sex': '',
  'host_status': '',
  'host_tax_id': '9606',
  'identified_by': '',
  'investigation_type': '',
  'isolate': '',
  'isolation_source': '',
  'last_updated': '2022-05-14',
  'lat': '',
  'local_environmental_context': '',
  'location': '',
  'location_end': '',
  'location_start': '',
  'lon': '',
  'marine_region': '',
  'mating_type': '',
  'ncbi_reporting_standard': '',
  'ph': '',
  'pipeline_name': '',
  'pipeline_version': '',
  'project_name': 'COVID-19 Genomics UK (COG-UK) consortium',
  'protocol_label': '',
  'pubmed_id': '',
  'reference_data_set_name': '',
  'reference_data_set_version': '',
  'reference_genome': '',
  'related_analysis_accession': '',
  'run_accession': 'ERR9720937',
  'salinity': '',
  'sample_accession': 'SAMEA14378297',
  'sample_alias': 'COG-UK/QEUH-3DF09F3',
  'sample_capture_status': 'active surveillance in response to outbreak',
  'sample_collection': '',
  'sample_description': 'Samples prepared at Lighthouse Lab in Glasgow by Harper VanSteenhouse, Yumi Kasai, David Gray, Carol Clugston, Anna Dominiczak and Alex Alderton, Roberto Amato, Jeffrey Barrett, Sonia Goncalves, Ewan Harrison, David K. Jackson, Ian Johnston, Dominic Kwiatkowski, Cordelia Langford, John Sillitoe on behalf of the Wellcome Sanger Institute COVID-19 Surveillance Team (https://www.sanger.ac.uk/covid-team)',
  'sample_material': '',
  'sample_title': 'COG-UK/QEUH-3DF09F3',
  'sampling_campaign': '',
  'sampling_platform': '',
  'sampling_site': '',
  'scientific_name': 'Severe acute respiratory syndrome coronavirus 2',
  'secondary_project': '',
  'secondary_sample_accession': 'ERS11972671',
  'secondary_study_accession': 'ERP121228',
  'sequencing_method': '',
  'serotype': '',
  'serovar': '',
  'sex': '',
  'specimen_voucher': '',
  'status': 'public',
  'strain': '',
  'study_accession': 'PRJEB37886',
  'study_alias': 'ena-STUDY-COVID-19 Genomics UK Consortium-18-04-2020-13:10:01:615-410',
  'study_title': 'COVID-19 Genomics UK (COG-UK) consortium',
  'sub_species': '',
  'sub_strain': '',
  'submission_accession': 'ERA14121881',
  'submission_tool': '',
  'submitted_aspera': 'fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10043917/file.fasta.gz;fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10043917/file.list.gz',
  'submitted_bytes': '8863;34',
  'submitted_format': 'FASTA;CHROMOSOME_LIST',
  'submitted_ftp': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043917/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043917/file.list.gz',
  'submitted_galaxy': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043917/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043917/file.list.gz',
  'submitted_host_sex': '',
  'submitted_md5': '16bbb52974c64e1d840752de4aed1f51;5aaa584c7ab0743f52b7c029ada4bdd5',
  'tag': 'datahub;covid19;pathogen;pathogen:virus;pathogen:priority',
  'target_gene': '',
  'tax_id': '2697049',
  'tax_lineage': '1;10239;2559587;2732396;2732408;2732506;76804;2499399;11118;2501931;694002;2509511;3418604;2697049',
  'taxonomic_classification': '',
  'taxonomic_identity_marker': '',
  'temperature': '',
  'tissue_lib': '',
  'tissue_type': '',
  'variety': ''},
 {'analysis_accession': 'ERZ10043961',
  'age': '',
  'altitude': '',
  'analysis_alias': 'webin-genome-hCoV-19.Scotland.QEUH-3DF0AD2.2022',
  'analysis_code_repository': '',
  'analysis_date': '',
  'analysis_description': '',
  'analysis_protocol': '',
  'analysis_title': 'Genome assembly: hCoV-19.Scotland.QEUH-3DF0AD2.2022',
  'analysis_type': 'SEQUENCE_ASSEMBLY',
  'assembly_quality': '',
  'assembly_software': '',
  'assembly_type': 'COVID-19 outbreak',
  'binning_software': '',
  'bio_material': '',
  'broad_scale_environmental_context': '',
  'broker_name': '',
  'cell_line': '',
  'cell_type': '',
  'center_name': 'Wellcome Sanger Institute;SC',
  'checklist': 'ERC000033',
  'collected_by': '',
  'collection_date': '2022-04-27',
  'collection_date_end': '2022-04-27',
  'collection_date_start': '2022-04-26',
  'completeness_score': '',
  'contamination_score': '',
  'country': 'United Kingdom',
  'cultivar': '',
  'culture_collection': '',
  'datahub': 'dcc_grusin',
  'depth': '',
  'description': 'COG_ACCESSION:COG-UK/QEUH-3DF0AD2/SANG:220505_A01545_0273_AH3GCFDRX2 COG_BASIC_QC:PASS COG_HIGH_QC:PASS COG_NOTE:Sample metadata and QC flags may have been updated since deposition in public databases. COG-UK recommends users refer to data.covid19.climb.ac.uk for latest metadata and QC tables before conducting analysis.',
  'dev_stage': '',
  'disease': '',
  'ecotype': '',
  'elevation': '',
  'environment_biome': '',
  'environment_feature': '',
  'environment_material': '',
  'environmental_medium': '',
  'environmental_sample': '',
  'experiment_accession': '',
  'experimental_factor': '',
  'first_created': '2022-05-14',
  'first_public': '2022-05-14',
  'generated_aspera': '',
  'generated_bytes': '',
  'generated_format': '',
  'generated_ftp': '',
  'generated_galaxy': '',
  'generated_md5': '',
  'germline': '',
  'host': 'Homo sapiens',
  'host_body_site': '',
  'host_genotype': '',
  'host_gravidity': '',
  'host_growth_conditions': '',
  'host_phenotype': '',
  'host_scientific_name': 'Homo sapiens',
  'host_sex': '',
  'host_status': '',
  'host_tax_id': '9606',
  'identified_by': '',
  'investigation_type': '',
  'isolate': '',
  'isolation_source': '',
  'last_updated': '2022-05-14',
  'lat': '',
  'local_environmental_context': '',
  'location': '',
  'location_end': '',
  'location_start': '',
  'lon': '',
  'marine_region': '',
  'mating_type': '',
  'ncbi_reporting_standard': '',
  'ph': '',
  'pipeline_name': '',
  'pipeline_version': '',
  'project_name': 'COVID-19 Genomics UK (COG-UK) consortium',
  'protocol_label': '',
  'pubmed_id': '',
  'reference_data_set_name': '',
  'reference_data_set_version': '',
  'reference_genome': '',
  'related_analysis_accession': '',
  'run_accession': 'ERR9720830',
  'salinity': '',
  'sample_accession': 'SAMEA14378191',
  'sample_alias': 'COG-UK/QEUH-3DF0AD2',
  'sample_capture_status': 'active surveillance in response to outbreak',
  'sample_collection': '',
  'sample_description': 'Samples prepared at Lighthouse Lab in Glasgow by Harper VanSteenhouse, Yumi Kasai, David Gray, Carol Clugston, Anna Dominiczak and Alex Alderton, Roberto Amato, Jeffrey Barrett, Sonia Goncalves, Ewan Harrison, David K. Jackson, Ian Johnston, Dominic Kwiatkowski, Cordelia Langford, John Sillitoe on behalf of the Wellcome Sanger Institute COVID-19 Surveillance Team (https://www.sanger.ac.uk/covid-team)',
  'sample_material': '',
  'sample_title': 'COG-UK/QEUH-3DF0AD2',
  'sampling_campaign': '',
  'sampling_platform': '',
  'sampling_site': '',
  'scientific_name': 'Severe acute respiratory syndrome coronavirus 2',
  'secondary_project': '',
  'secondary_sample_accession': 'ERS11972565',
  'secondary_study_accession': 'ERP121228',
  'sequencing_method': '',
  'serotype': '',
  'serovar': '',
  'sex': '',
  'specimen_voucher': '',
  'status': 'public',
  'strain': '',
  'study_accession': 'PRJEB37886',
  'study_alias': 'ena-STUDY-COVID-19 Genomics UK Consortium-18-04-2020-13:10:01:615-410',
  'study_title': 'COVID-19 Genomics UK (COG-UK) consortium',
  'sub_species': '',
  'sub_strain': '',
  'submission_accession': 'ERA14121925',
  'submission_tool': '',
  'submitted_aspera': 'fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10043961/file.fasta.gz;fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10043961/file.list.gz',
  'submitted_bytes': '8865;34',
  'submitted_format': 'FASTA;CHROMOSOME_LIST',
  'submitted_ftp': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043961/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043961/file.list.gz',
  'submitted_galaxy': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043961/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10043961/file.list.gz',
  'submitted_host_sex': '',
  'submitted_md5': 'dca54fc127dfbe95ed94e38c743c2fe3;5aaa584c7ab0743f52b7c029ada4bdd5',
  'tag': 'datahub;covid19;pathogen;pathogen:virus;pathogen:priority',
  'target_gene': '',
  'tax_id': '2697049',
  'tax_lineage': '1;10239;2559587;2732396;2732408;2732506;76804;2499399;11118;2501931;694002;2509511;3418604;2697049',
  'taxonomic_classification': '',
  'taxonomic_identity_marker': '',
  'temperature': '',
  'tissue_lib': '',
  'tissue_type': '',
  'variety': ''},
 {'analysis_accession': 'ERZ10044095',
  'age': '',
  'altitude': '',
  'analysis_alias': 'webin-genome-hCoV-19.Scotland.QEUH-3DF0C72.2022',
  'analysis_code_repository': '',
  'analysis_date': '',
  'analysis_description': '',
  'analysis_protocol': '',
  'analysis_title': 'Genome assembly: hCoV-19.Scotland.QEUH-3DF0C72.2022',
  'analysis_type': 'SEQUENCE_ASSEMBLY',
  'assembly_quality': '',
  'assembly_software': '',
  'assembly_type': 'COVID-19 outbreak',
  'binning_software': '',
  'bio_material': '',
  'broad_scale_environmental_context': '',
  'broker_name': '',
  'cell_line': '',
  'cell_type': '',
  'center_name': 'Wellcome Sanger Institute;SC',
  'checklist': 'ERC000033',
  'collected_by': '',
  'collection_date': '2022-04-26',
  'collection_date_end': '2022-04-26',
  'collection_date_start': '2022-04-25',
  'completeness_score': '',
  'contamination_score': '',
  'country': 'United Kingdom',
  'cultivar': '',
  'culture_collection': '',
  'datahub': 'dcc_grusin',
  'depth': '',
  'description': 'COG_ACCESSION:COG-UK/QEUH-3DF0C72/SANG:220505_A01545_0273_AH3GCFDRX2 COG_BASIC_QC:PASS COG_HIGH_QC:PASS COG_NOTE:Sample metadata and QC flags may have been updated since deposition in public databases. COG-UK recommends users refer to data.covid19.climb.ac.uk for latest metadata and QC tables before conducting analysis.',
  'dev_stage': '',
  'disease': '',
  'ecotype': '',
  'elevation': '',
  'environment_biome': '',
  'environment_feature': '',
  'environment_material': '',
  'environmental_medium': '',
  'environmental_sample': '',
  'experiment_accession': '',
  'experimental_factor': '',
  'first_created': '2022-05-14',
  'first_public': '2022-05-14',
  'generated_aspera': '',
  'generated_bytes': '',
  'generated_format': '',
  'generated_ftp': '',
  'generated_galaxy': '',
  'generated_md5': '',
  'germline': '',
  'host': 'Homo sapiens',
  'host_body_site': '',
  'host_genotype': '',
  'host_gravidity': '',
  'host_growth_conditions': '',
  'host_phenotype': '',
  'host_scientific_name': 'Homo sapiens',
  'host_sex': '',
  'host_status': '',
  'host_tax_id': '9606',
  'identified_by': '',
  'investigation_type': '',
  'isolate': '',
  'isolation_source': '',
  'last_updated': '2022-05-14',
  'lat': '',
  'local_environmental_context': '',
  'location': '',
  'location_end': '',
  'location_start': '',
  'lon': '',
  'marine_region': '',
  'mating_type': '',
  'ncbi_reporting_standard': '',
  'ph': '',
  'pipeline_name': '',
  'pipeline_version': '',
  'project_name': 'COVID-19 Genomics UK (COG-UK) consortium',
  'protocol_label': '',
  'pubmed_id': '',
  'reference_data_set_name': '',
  'reference_data_set_version': '',
  'reference_genome': '',
  'related_analysis_accession': '',
  'run_accession': 'ERR9720923',
  'salinity': '',
  'sample_accession': 'SAMEA14378283',
  'sample_alias': 'COG-UK/QEUH-3DF0C72',
  'sample_capture_status': 'active surveillance in response to outbreak',
  'sample_collection': '',
  'sample_description': 'Samples prepared at Lighthouse Lab in Glasgow by Harper VanSteenhouse, Yumi Kasai, David Gray, Carol Clugston, Anna Dominiczak and Alex Alderton, Roberto Amato, Jeffrey Barrett, Sonia Goncalves, Ewan Harrison, David K. Jackson, Ian Johnston, Dominic Kwiatkowski, Cordelia Langford, John Sillitoe on behalf of the Wellcome Sanger Institute COVID-19 Surveillance Team (https://www.sanger.ac.uk/covid-team)',
  'sample_material': '',
  'sample_title': 'COG-UK/QEUH-3DF0C72',
  'sampling_campaign': '',
  'sampling_platform': '',
  'sampling_site': '',
  'scientific_name': 'Severe acute respiratory syndrome coronavirus 2',
  'secondary_project': '',
  'secondary_sample_accession': 'ERS11972657',
  'secondary_study_accession': 'ERP121228',
  'sequencing_method': '',
  'serotype': '',
  'serovar': '',
  'sex': '',
  'specimen_voucher': '',
  'status': 'public',
  'strain': '',
  'study_accession': 'PRJEB37886',
  'study_alias': 'ena-STUDY-COVID-19 Genomics UK Consortium-18-04-2020-13:10:01:615-410',
  'study_title': 'COVID-19 Genomics UK (COG-UK) consortium',
  'sub_species': '',
  'sub_strain': '',
  'submission_accession': 'ERA14122059',
  'submission_tool': '',
  'submitted_aspera': 'fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10044095/file.fasta.gz;fasp.sra.ebi.ac.uk:/vol1/analysis/ERZ100/ERZ10044095/file.list.gz',
  'submitted_bytes': '8862;34',
  'submitted_format': 'FASTA;CHROMOSOME_LIST',
  'submitted_ftp': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10044095/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10044095/file.list.gz',
  'submitted_galaxy': 'ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10044095/file.fasta.gz;ftp.sra.ebi.ac.uk/vol1/analysis/ERZ100/ERZ10044095/file.list.gz',
  'submitted_host_sex': '',
  'submitted_md5': '7c3f6813d889ede294b524960d315d52;5aaa584c7ab0743f52b7c029ada4bdd5',
  'tag': 'datahub;covid19;pathogen;pathogen:virus;pathogen:priority',
  'target_gene': '',
  'tax_id': '2697049',

In [ ]:
ENAAnalysisFields.all_values_as_str()

'age,altitude,analysis_accession,analysis_alias,analysis_code_repository,analysis_date,analysis_description,analysis_protocol,analysis_title,analysis_type,assembly_quality,assembly_software,assembly_type,binning_software,bio_material,broad_scale_environmental_context,broker_name,cell_line,cell_type,center_name,checklist,collected_by,collection_date,collection_date_end,collection_date_start,completeness_score,contamination_score,country,cultivar,culture_collection,datahub,depth,description,dev_stage,disease,ecotype,elevation,environment_biome,environment_feature,environment_material,environmental_medium,environmental_sample,experiment_accession,experimental_factor,first_created,first_public,generated_aspera,generated_bytes,generated_format,generated_ftp,generated_galaxy,generated_md5,germline,host,host_body_site,host_genotype,host_gravidity,host_growth_conditions,host_phenotype,host_scientific_name,host_sex,host_status,host_tax_id,identified_by,investigation_type,isolate,isolation_source,last_updated,lat,local_environmental_context,location,location_end,location_start,lon,marine_region,mating_type,ncbi_reporting_standard,ph,pipeline_name,pipeline_version,project_name,protocol_label,pubmed_id,reference_data_set_name,reference_data_set_version,reference_genome,related_analysis_accession,run_accession,salinity,sample_accession,sample_alias,sample_capture_status,sample_collection,sample_description,sample_material,sample_title,sampling_campaign,sampling_platform,sampling_site,scientific_name,secondary_project,secondary_sample_accession,secondary_study_accession,sequencing_method,serotype,serovar,sex,specimen_voucher,status,strain,study_accession,study_alias,study_title,sub_species,sub_strain,submission_accession,submission_tool,submitted_aspera,submitted_bytes,submitted_format,submitted_ftp,submitted_galaxy,submitted_host_sex,submitted_md5,tag,target_gene,tax_id,tax_lineage,taxonomic_classification,taxonomic_identity_marker,temperature,tissue_lib,tissue_type,variety'