# 🕵️‍♀️ Searching for MGnify Studies

<button title="Make live" style="display:inline-flex;align-items:center;gap:0.4rem;padding:0.5rem 1rem;border:0;border-radius:100px;background:linear-gradient(135deg,#0f766e,#14b8a6);color:white;box-shadow:0 6px 18px rgba(15,118,110,.25);cursor:pointer;font-size:1rem;" class="thebe-button" onclick="initThebeSBT()">Activate Notebook</button>

On this page, which also serves as a runnable notebook (link above ^), we again demonstrate the basic usability of MGni.py to search the [Studies resource](https://www.ebi.ac.uk/metagenomics/api/v2/#/Studies/list_mgnify_studies) for some studies of interest (e.g., tomaotos)

---

## 🎯 The Goal: Get a list of MGnify studies of tomato rhizospheres

Let's request tomato rhizosphere study metadata from the  MGnify Studies API.

In [2]:
# uncomment below if colab
#!pip install mgnipy
#!pip install asyncio

In [3]:
from mgnipy import MGnipy

MG = MGnipy()

tomato_studies = MG.studies(
    biome_lineage="root:Host-associated:Plants:Rhizosphere", search="tomato"
)

# tomato_studies.explain()

https://www.ebi.ac.uk/metagenomics/api/v2/studies?biome_lineage=root%3AHost-associated%3APlants%3ARhizosphere&search=tomato&page=1

Choose your entry resource proxy

In [4]:
# init
MG = MGnipy(
    # configuration
)

# helper
MG.list_resources()

Advancing to request num 1

,accession,ena_accessions,title,biome,updated_at
0,MGYS00010296,"[ERP166137, PRJEB82448]",Microbiome-mediated tolerance of wild tomato t...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T14:00:52.352000+00:00
1,MGYS00010297,"[SRP333165, PRJNA755742]",Tomato rhizosphere microbiome in the pot exper...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:42:02.227000+00:00
2,MGYS00006231,"[ERP139927, PRJEB55060]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:27:28.963000+00:00
3,MGYS00006204,"[ERP140102, PRJEB55219]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:01:19.102000+00:00
4,MGYS00006205,"[ERP140107, PRJEB55224]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:01:31.666000+00:00
5,MGYS00006230,"[ERP139923, PRJEB55057]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:25:40.059000+00:00
6,MGYS00006208,"[ERP140115, PRJEB55232]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:01:49.848000+00:00
7,MGYS00010257,"[SRP456588, PRJNA1004080]",Combined effect of microplastics and fungicide...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-03T18:47:35.095000+00:00
8,MGYS00010258,"[SRP517058, PRJNA1127303]",Metagenomic data of rhizosphere soil during to...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-04T11:04:15.175000+00:00
9,MGYS00010324,[PRJEB95772],Metagenome assembly of PRJNA777724 data set (T...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-07T12:30:16.888000+00:00
10,MGYS00010245,"[PRJEB82447, ERP166136]",Unveiling diversity and adaptations of the wil...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-23T16:38:33.334000+00:00
11,MGYS00010298,"[PRJNA777724, SRP344777]",Tomato heritable microbiome,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-07T15:25:59.939000+00:00
12,MGYS00010262,[PRJEB91684],Metagenome assembly of PRJNA1004080 data set (...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-03T18:41:58.194000+00:00
13,MGYS00010250,"[PRJNA755741, SRP333163]",Tomato rhizosphere microbiome in the belowgrou...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-23T08:45:47.142000+00:00
14,MGYS00010264,[PRJEB91717],Metagenome assembly of PRJNA1127303 data set (...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-04T10:10:15.643000+00:00
15,MGYS00010251,"[SRP338795, PRJNA766489]",Culture-independent analysis of rhizosphere mi...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-21T17:01:18.132000+00:00
16,MGYS00010253,"[PRJNA789467, SRP351203]",Disentangling the genetic basis of rhizosphere...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-01T17:26:35.948000+00:00

you can either pass query parameters as dict to `params` or as kwargs.

In [ ]:
# studies resource proxy
studies = MG.studies

# helper
studies.list_supported_params()

In [ ]:
# set up query
filtered_studies = studies.filter(
    biome_lineage="root:Host-associated:Plants:Rhizosphere", search="tomato"
)

# preview before getting all pages
filtered_studies.dry_run()

In [ ]:
# make the get request
await filtered_studies.abulk_fetch()

# look at our list of studies
filtered_studies.to_df()

### Getting their study details

From our filtered list of studies we can use `.get_detail()` to iteratively get their details from the [**get_mgnify_study** MGnify API endpoint](https://www.ebi.ac.uk/metagenomics/api/v2/#/Studies/get_mgnify_study)

In [6]:
# get details for all studies (this will make multiple requests until all details are fetched)
while True:
    # get details for the next study
    det = filtered_studies.get_detail()
    # if no more studies to fetch details for, break the loop
    if det is None:
        print("Finished fetching details for all studies.")
        break

Finished fetching details for all studies.

We can take a look at all study metadata details which are stored to

- `.details`: the `mgnipy.StudyDetail` instances
- `.details_rsults`: a dictionary where each item is a accession: detail
- `.details_df`: a pd.DataFrame where each study metadata detail is a row

In [12]:
filtered_studies.details_df

,accession,ena_accessions,title,biome,updated_at,downloads,metadata,first_accession
MGYS00010296,MGYS00010296,"[ERP166137, PRJEB82448]",Microbiome-mediated tolerance of wild tomato t...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T14:00:52.352000+00:00,[],{},ERP166137
MGYS00010297,MGYS00010297,"[SRP333165, PRJNA755742]",Tomato rhizosphere microbiome in the pot exper...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:42:02.227000+00:00,[],{},SRP333165
MGYS00006231,MGYS00006231,"[ERP139927, PRJEB55060]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:27:28.963000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",{},ERP139927
MGYS00006204,MGYS00006204,"[ERP140102, PRJEB55219]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:01:19.102000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",{},ERP140102
MGYS00006205,MGYS00006205,"[ERP140107, PRJEB55224]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:01:31.666000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",{},ERP140107

## 🎯 Next Steps: Getting their MGnify analyses

Using the StudyDetail instances we can also get a list of all their
- MGnify analyses i.e., `mgnipy.V2.proxies.Analyses` instance
- publications `mgnipy.V2.proxies.Publications`
- samples `mgnipy.V2.proxies.Samples`


For example lets take a look at the study "MGYS00006204".

### Step-by-step example: `MGYS00006204`

In [16]:
# getting the StudyDetail for the specific study
example_study_details = filtered_studies["MGYS00006231"]

# this is a helper method to list all relationships for the study
example_study_details.list_relationships()

['samples', 'analyses', 'publications']

we can access them as attributes form the StudyDetail. When called the requests will automatically be made to the MGnify API

In [17]:
example_study_pub_list = example_study_details.publications
print(example_study_pub_list)

example_study_sample_list = example_study_details.samples
print(example_study_sample_list)

example_study_analysis_list = example_study_details.analyses
print(example_study_analysis_list)

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 2525.17it/s]

Advancing to request num 1
MGnifier instance for resource: publications
I.e., mgnipy.V2.proxies.publications.Publications
----------------------------------------
Base URL: https://www.ebi.ac.uk/
Parameters: {'accession': 'MGYS00006231'}
Example request URL: https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00006231/publications?page=1
Endpoint module: mgnipy.emgapi_v2_client.api.studies.list_mgnify_study_publications
Is list endpoint (returns paginated results): True
Cache directory: /Users/phanthanourak/Library/Caches/mgnipy/9be351d43240b5e84bc0968397a25d600e05060b7e43fe51945d866f35d01c28

Retrieving pages: 100%|██████████| 5/5 [00:00<00:00, 8153.78it/s]

Advancing to request num 1
Advancing to request num 2
Advancing to request num 3
Advancing to request num 4
Advancing to request num 5
MGnifier instance for resource: samples
I.e., mgnipy.V2.proxies.samples.Samples
----------------------------------------
Base URL: https://www.ebi.ac.uk/
Parameters: {'accession': 'MGYS00006231'}
Example request URL: https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00006231/samples?page=1
Endpoint module: mgnipy.emgapi_v2_client.api.studies.list_mgnify_study_samples
Is list endpoint (returns paginated results): True
Cache directory: /Users/phanthanourak/Library/Caches/mgnipy/5ba3912237f2b3ec1baa3a302cd5c6ff7340cfc88d6512cd2c1eae5f8aa29648

Retrieving pages: 100%|██████████| 5/5 [00:00<00:00, 4464.88it/s]

Advancing to request num 1
Advancing to request num 2
Advancing to request num 3
Advancing to request num 4
Advancing to request num 5
MGnifier instance for resource: analyses
I.e., mgnipy.V2.proxies.analyses.Analyses
----------------------------------------
Base URL: https://www.ebi.ac.uk/
Parameters: {'accession': 'MGYS00006231'}
Example request URL: https://www.ebi.ac.uk/metagenomics/api/v2/studies/MGYS00006231/analyses?page=1
Endpoint module: mgnipy.emgapi_v2_client.api.studies.list_mgnify_study_analyses
Is list endpoint (returns paginated results): True
Cache directory: /Users/phanthanourak/Library/Caches/mgnipy/e17f20b39bbe95d0d44c64473835e35ad2343868b51e44ecaca4d021a1a8cdd9

taking a look at the analyses metadata

In [18]:
example_study_analysis_list.to_df()

,experiment_type,study_accession,accession,run,sample,assembly,pipeline_version
0,Assembly,MGYS00006231,MGYA00645526,None,"{'accession': 'SAMN24114695', 'ena_accessions'...",{'updated_at': '2026-04-30T22:25:40.680000+00:...,V5
1,Assembly,MGYS00006231,MGYA00645548,None,"{'accession': 'SAMN24114734', 'ena_accessions'...",{'updated_at': '2026-04-30T22:25:41.667000+00:...,V5
2,Assembly,MGYS00006231,MGYA00645551,None,"{'accession': 'SAMN24114802', 'ena_accessions'...",{'updated_at': '2026-04-30T22:25:42.609000+00:...,V5
3,Assembly,MGYS00006231,MGYA00645559,None,"{'accession': 'SAMN24114786', 'ena_accessions'...",{'updated_at': '2026-04-30T22:25:43.561000+00:...,V5
4,Assembly,MGYS00006231,MGYA00645571,None,"{'accession': 'SAMN24114738', 'ena_accessions'...",{'updated_at': '2026-04-30T22:25:44.649000+00:...,V5
...,...,...,...,...,...,...,...
109,Assembly,MGYS00006231,MGYA00793502,None,"{'accession': 'SAMN24114780', 'ena_accessions'...",{'updated_at': '2026-04-30T22:27:23.689000+00:...,V5
110,Assembly,MGYS00006231,MGYA00793503,None,"{'accession': 'SAMN24114748', 'ena_accessions'...",{'updated_at': '2026-04-30T22:27:24.599000+00:...,V5
111,Assembly,MGYS00006231,MGYA00793504,None,"{'accession': 'SAMN24114732', 'ena_accessions'...",{'updated_at': '2026-04-30T22:27:25.517000+00:...,V5
112,Assembly,MGYS00006231,MGYA00793505,None,"{'accession': 'SAMN24114749', 'ena_accessions'...",{'updated_at': '2026-04-30T22:27:26.440000+00:...,V5
113,Assembly,MGYS00006231,MGYA00793506,None,"{'accession': 'SAMN24114800', 'ena_accessions'...",{'updated_at': '2026-04-30T22:27:27.357000+00:...,V5

then we can get the details and so on

### On Repeat: Getting all analyses metadata

- loop through every study in `filtered_studies.detail`
- for each study get the details on all sample analyses appending to a list `analyses_details`
- then we will take a look as a dataframe

In [19]:
import asyncio

study_details_dict = filtered_studies.details

analyses_details = []

for study_id, study_detail in study_details_dict.items():

    # verbose
    print(f"Study {study_id}")

    # populating list of analyses for the study
    study_analyses_list = study_detail.analyses

    # get the analyses details
    while True:
        # get details for the next analysis
        det = await study_analyses_list.aget_detail()
        # adding a delay to avoid overwhelming the API
        await asyncio.sleep(0.5)
        # if no more analyses to fetch details for, break the loop
        if det is None:
            print("Finished fetching details for all analyses.")
            break

    print(
        f"Number of analyses for study {study_id}: {len(study_analyses_list)}\n"
    )

    analyses_details.append(study_analyses_list.details_df)

Study MGYS00010296

Retrieving pages: 0it [00:00, ?it/s]

Finished fetching details for all analyses.
Number of analyses for study MGYS00010296: 0

Study MGYS00010297

Retrieving pages: 0it [00:00, ?it/s]

Finished fetching details for all analyses.
Number of analyses for study MGYS00010297: 0

Study MGYS00006231

Retrieving pages: 100%|██████████| 5/5 [00:00<00:00, 5235.03it/s]

Advancing to request num 1
Advancing to request num 2
Advancing to request num 3
Advancing to request num 4
Advancing to request num 5

Finished fetching details for all analyses.
Number of analyses for study MGYS00006231: 114

Study MGYS00006204

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 5412.01it/s]

Advancing to request num 1

Finished fetching details for all analyses.
Number of analyses for study MGYS00006204: 12

Study MGYS00006205

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 3518.71it/s]

Advancing to request num 1

Finished fetching details for all analyses.
Number of analyses for study MGYS00006205: 12

Study MGYS00006230

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 4544.21it/s]

Advancing to request num 1

Finished fetching details for all analyses.
Number of analyses for study MGYS00006230: 2

Study MGYS00006208

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 3876.44it/s]

Advancing to request num 1

Finished fetching details for all analyses.
Number of analyses for study MGYS00006208: 9

Study MGYS00010257

Retrieving pages: 0it [00:00, ?it/s]

Finished fetching details for all analyses.
Number of analyses for study MGYS00010257: 0

Study MGYS00010258

Retrieving pages: 0it [00:00, ?it/s]

Finished fetching details for all analyses.
Number of analyses for study MGYS00010258: 0

Study MGYS00010324

Retrieving pages: 0it [00:00, ?it/s]

Finished fetching details for all analyses.
Number of analyses for study MGYS00010324: 0

Study MGYS00010245

Retrieving pages: 0it [00:00, ?it/s]

Finished fetching details for all analyses.
Number of analyses for study MGYS00010245: 0

Study MGYS00010298

Retrieving pages: 0it [00:00, ?it/s]

Finished fetching details for all analyses.
Number of analyses for study MGYS00010298: 0

Study MGYS00010262

Retrieving pages: 0it [00:00, ?it/s]

Finished fetching details for all analyses.
Number of analyses for study MGYS00010262: 0

Study MGYS00010250

Retrieving pages: 0it [00:00, ?it/s]

Finished fetching details for all analyses.
Number of analyses for study MGYS00010250: 0

Study MGYS00010264

Retrieving pages: 0it [00:00, ?it/s]

Finished fetching details for all analyses.
Number of analyses for study MGYS00010264: 0

Study MGYS00010251

Retrieving pages: 0it [00:00, ?it/s]

Finished fetching details for all analyses.
Number of analyses for study MGYS00010251: 0

Study MGYS00010253

Retrieving pages: 0it [00:00, ?it/s]

Finished fetching details for all analyses.
Number of analyses for study MGYS00010253: 0

let's look at all the sample analyses metadata in one df

In [21]:
import pandas as pd

# concat the list of analyses details dataframes into one dataframe
tomato_analyses = pd.concat(analyses_details)
# take a look
print(tomato_analyses.shape)
tomato_analyses.head()

(149, 12)

,experiment_type,study_accession,accession,run,sample,assembly,pipeline_version,read_run,quality_control_summary,downloads,results_dir,metadata
MGYA00645526,Assembly,MGYS00006231,MGYA00645526,None,"{'accession': 'SAMN24114695', 'ena_accessions'...",{'updated_at': '2026-04-30T22:25:40.680000+00:...,V5,"[{'experiment_type': 'Metagenomic', 'instrumen...",{},"[{'file_type': 'fasta', 'download_type': 'Sequ...",https://ftp.ebi.ac.uk/pub/databases/metagenomi...,{}
MGYA00645548,Assembly,MGYS00006231,MGYA00645548,None,"{'accession': 'SAMN24114734', 'ena_accessions'...",{'updated_at': '2026-04-30T22:25:41.667000+00:...,V5,"[{'experiment_type': 'Metagenomic', 'instrumen...",{},"[{'file_type': 'fasta', 'download_type': 'Sequ...",https://ftp.ebi.ac.uk/pub/databases/metagenomi...,{}
MGYA00645551,Assembly,MGYS00006231,MGYA00645551,None,"{'accession': 'SAMN24114802', 'ena_accessions'...",{'updated_at': '2026-04-30T22:25:42.609000+00:...,V5,"[{'experiment_type': 'Metagenomic', 'instrumen...",{},"[{'file_type': 'fasta', 'download_type': 'Sequ...",https://ftp.ebi.ac.uk/pub/databases/metagenomi...,{}
MGYA00645559,Assembly,MGYS00006231,MGYA00645559,None,"{'accession': 'SAMN24114786', 'ena_accessions'...",{'updated_at': '2026-04-30T22:25:43.561000+00:...,V5,"[{'experiment_type': 'Metagenomic', 'instrumen...",{},"[{'file_type': 'fasta', 'download_type': 'Sequ...",https://ftp.ebi.ac.uk/pub/databases/metagenomi...,{}
MGYA00645571,Assembly,MGYS00006231,MGYA00645571,None,"{'accession': 'SAMN24114738', 'ena_accessions'...",{'updated_at': '2026-04-30T22:25:44.649000+00:...,V5,"[{'experiment_type': 'Metagenomic', 'instrumen...",{},"[{'file_type': 'fasta', 'download_type': 'Sequ...",https://ftp.ebi.ac.uk/pub/databases/metagenomi...,{}